devfile.yaml
make devfile fork friendly
n/a
n/a
n/a
=> make devfile fork friendly

src/components/branding/branding.constant.ts, src/components/branding/che-branding.ts, src/index.html
add a possibility to set product version from the product.json
Cherry-pick https://github.com/eclipse/che/pull/16405
=> add a possibility to set product version from the product.json

devfile.yaml
This PR updates project devfile to work correctly after moving to separate repository.
=> Update devfile to work correctly after moving to separate repository

README.md
Added build status icons for CI jobs into README.md.
=> Add CI job status badges to README.md

.ci/cico_common.sh
Add configuration for Nexus deploy automation
Utilize new Nexus Staging plugin to handle, what would be otherwise manual, the process of closing and releasing repo for non-snapshot artifacts.
https://github.com/eclipse/che/issues/16043
=> Automate deploy to Nexus during release

.ci/cico_common.sh, pom.xml
Specify project version & Fix CI script pushing to the wrong repo
=> Add version and fix repository in CI script

src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts
This PR fixes the misbehaving of modal dialogue window when it's possible to interact with form controls behind the modal window backdrop. Also it improves the dialogue content adding the checkbox which label explains that this operation cannot be reverted.
<details>
<summary>Screenshots</summary>
</details>
fixes https://github.com/eclipse/che/issues/8542
=> Fix modal dialog to delete a workspace.

pom.xml
[release] Bump to 7.12.0-SNAPSHOT in master
=> [release] Bump to 7.12.0-SNAPSHOT in master

src/components/che-pf-widget/che-pf-widget.config.ts, src/components/che-pf-widget/select/che-pf-select-single.directive.ts, src/components/che-pf-widget/select/che-pf-select-single.html, src/components/che-pf-widget/select/che-pf-select-typeahead.directive.ts, src/components/che-pf-widget/select/che-pf-select-typeahead.html, src/components/che-pf-widget/select/che-pf-select.controller.ts
This PR adds new "select" component based on PatternFly4 styles.
**Screenshot**
resolves https://github.com/eclipse/che/issues/16524
=> Added "select" component with PatternFly4 styles

src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.controller.ts, src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.html, src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.styl, src/app/workspaces/workspace-details/workspace-details.controller.ts, src/app/workspaces/workspace-details/workspace-details.html, src/app/workspaces/workspace-details/workspace-details.service.ts, src/app/workspaces/workspace-details/workspace-details.styl, src/components/attribute/monaco/monaco.directive.ts, src/components/attribute/monaco/monaco.styl, src/components/widget/edit-mode-overlay/che-edit-mode-overlay.controller.ts, src/components/widget/editor/che-editor.controller.ts, src/components/widget/editor/che-editor.directive.ts, src/components/widget/editor/che-editor.styl
Added small fixes:
- Fix Monaco editor layouts.
- Show Devfile schema validation errors as errors.
- Deny saving the invalid Devfile in the case with schema validation errors.
- Added Monaco decorators for text highlighting.
https://github.com/eclipse/che/issues/15654
https://github.com/eclipse/che/issues/14683
https://github.com/eclipse/che/issues/15662
=> Devfile editor improvements

pom.xml
=> [release] bump master to 7.13.0-SNAPSHOT

pom.xml
[release] Bump to 7.11.1-SNAPSHOT in 7.11.x
=> [release] Bump to 7.11.1-SNAPSHOT in 7.11.x

pom.xml
Fix parent after migrating dependencies to che repository
https://github.com/eclipse/che/issues/16780
=> Fix parent after migrating dependencies to che repository

src/app/index.module.ts
Fix the style for an unknown error.
=> Fix the style for an unknown error

.dockerignore
Add Docker.apache to ignore
I just need to trigger CI
=> Add Docker.apache to ignore

src/assets/branding/product.json, src/components/branding/branding.constant.ts
Updates documentation links to point to online doc.
fixes https://github.com/eclipse/che/issues/16896
=> [UD] Fixed documentation links

src/app/get-started/custom-workspace-tab/custom-workspace-tab.controller.ts
Fix creating a new custom workspace from the text. 
fixes https://github.com/eclipse/che/issues/16878
=> Fix a new custom workspace flow

src/components/service/browser-detect.ts
- Improve browser detection service not to detect Opera as Chrome.
- Fix import.
=> fix browser detection

apache.Dockerfile
Replace alpine based image which can handle PhantomJS tests
Fixes https://github.com/eclipse/che/issues/16877
=> Enable tests during build

src/app/get-started/get-started-config.ts, src/app/get-started/get-started.controller.ts, src/app/navbar/navbar.controller.ts, src/assets/branding/product.json, src/components/branding/branding.constant.ts
Fix the URL syntax.
fixes https://github.com/eclipse/che/issues/16957
=> Fix the URL syntax

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Add CI job that checks github pull requests
=> Add CI job that checks github pull requests

src/components/service/browser-detect.ts
Cherry-picks of https://github.com/eclipse/che-dashboard/commit/e5674f2be99ceb3b2aa2c5e360f4b438ce5ed22d and https://github.com/eclipse/che-dashboard/commit/f75e632e8fc1c55f1991bdcd143fcd70a9a14d31 from master.
=> Cherry-picks of browser detection fixes

.github/workflows/pr.yaml
Do not trigger pr job on master changes
=> Do not trigger pr job on master changes

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Removed build for s390x added retry timeout 60 sec
https://github.com/eclipse/che/issues/16987
Related to eclipse/che#16983
=> Removed build for s390x && added retry timeout 60 sec

src/components/service/browser-detect.ts
Fix typo in browser detection.
cherry-pick of https://github.com/eclipse/che-dashboard/commit/d698787c5e0f05592925daa1cfbe1610447dd6f8
=> Fix typo in browser detection

src/app/factories/load-factory/load-factory.controller.ts, src/app/navbar/recent-workspaces/recent-workspaces.controller.ts, src/app/navbar/recent-workspaces/recent-workspaces.html, src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.controller.ts, src/app/organizations/organization-details/organization-workspaces/list-organization-workspaces.html, src/app/teams/team-details/team-workspaces/list-team-workspaces.controller.ts, src/app/teams/team-details/team-workspaces/list-team-workspaces.html, src/app/workspaces/list-workspaces/list-workspaces.controller.ts, src/app/workspaces/list-workspaces/list-workspaces.html, src/assets/branding/product.json, src/components/branding/branding.constant.ts
Fix creation links.
https://github.com/eclipse/che/issues/17018
=> Fix creation links

package.json
=> Update supported nodejs version in package.json

src/app/stacks/stack-details/stack.styl, src/app/workspaces/workspace-details/workspace-details-config.ts, src/app/workspaces/workspace-details/workspace-details.controller.ts, src/app/workspaces/workspace-details/workspace-details.directive.spec.ts, src/app/workspaces/workspace-details/workspace-details.html, src/components/widget/edit-mode-overlay/che-edit-mode-overlay.controller.ts, src/components/widget/toolbar/che-row-toolbar.directive.ts
Fix routing errors.
https://github.com/eclipse/che/issues/17007
=> Fix routing errors

src/app/index.module.ts
This PR improves error handling so now SSO-related errors will look similarly to the following screenshot:
fixes https://github.com/eclipse/che/issues/17154
=> Better error handling

src/app/ide/ide-iframe/ide-iframe.service.ts
This changes proposal adds ability to post message to dashboard with instruction to open a specific workspace by workspace id.
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
https://github.com/eclipse/che/issues/17361
N/A
N/A
=> Message handler to start workspace by id in dashboard

README.md
Remove mention to IntellJ in README file.
Che should not be considered as an alternative to IntelliJ. We are not targeting the same developer community and we are not implementing the same features that IntelliJ has.
=> Remove mention to IntelliJ from README

src/components/widget/devfile-editor/devfile-editor.controller.ts
Fix unneeded things appear during autocomplete.
Fixes https://github.com/eclipse/che/issues/17056
=> Fix unneeded things appear during autocomplete

src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.controller.ts, src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.html, src/app/get-started/get-started-tab/get-started-tab.controller.ts, src/app/get-started/get-started-tab/get-started-tab.html, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.component.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.controller.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.html, src/components/che-pf-widget/switch/che-pf-switch.directive.ts, src/components/che-pf-widget/switch/che-pf-switch.html, src/components/service/storage-type/storage-type.service.ts
Storage type fixes that are cherry-picked from https://github.com/eclipse/che-dashboard/pull/84
=> Storage Type fixes and improvements

src/app/factories/load-factory/load-factory.controller.ts, src/app/navbar/navbar.controller.ts
Fix errors handling while loading a factory.
fixes https://github.com/eclipse/che/issues/17646
=> Fix errors handling while loading a factory

src/components/widget/devfile-editor/devfile-editor.controller.ts
This PR sets preferable order of top-level fields in the devfile editor.
resolves https://github.com/eclipse/che/issues/17726
=> Set preferable order of top-level fields in the devfile editor

src/app/factories/load-factory/load-factory.controller.ts, src/app/factories/load-factory/load-factory.styl, src/components/steps-container/steps-container.html
This PR makes resolved factory source filename more visible: 
resolves https://github.com/eclipse/che/issues/17606
=> More visible factory source filename

src/app/get-started/get-started-config.ts, src/app/get-started/get-started.controller.ts, src/app/get-started/get-started.html, src/app/navbar/navbar.html
Fix two headers bug on Get Started page. Avoid unnecessary page reloading.
fixes https://github.com/eclipse/che/issues/17544
=> Fix Get Started page bugs

src/components/api/che-factory.factory.ts
This PR aims to expand an error message on factory loading page.
more context's here https://github.com/eclipse/che/issues/17508#issuecomment-693249641
=> Handle an error happened while requesting `/api/factory/resolver`

src/components/api/workspace/che-workspace.factory.ts
Fix a minor typo I noticed while starting an ephemeral workspace
N/A
=> Fix minor typo in ephemeral workspace warning

src/components/api/che-factory.factory.ts
Improved the error message shown while factory resolving failed due to network issues. 
The proposed message is `Failed to fetch the devfile due to network issues while requesting "/api/factory/resolver".`
=> Improved error message for factory loading flow

src/app/keycloak-setup.ts
Looks like user dashboard is broken in multi-user mode: https://github.com/eclipse/che-dashboard/commit/459959915c5e60e39a436668bc09042a6e4f097f
fixes https://github.com/eclipse/che/issues/18075
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>
=> Fix retrieving keycloak settings.

src/app/keycloak-setup.ts
Do not fail in Single-User Mode
https://github.com/eclipse/che/issues/18095
=> Do not fail in Single-User Mode

src/app/factories/load-factory/load-factory.controller.ts
Add extra factory parameters to control workspace deployment.
fixes  https://github.com/eclipse/che/issues/18153
=> Add extra factory parameters to control workspace deployment

make-release.sh
Fix commit creation for the release of Dashboard, add all file to git index instead of non-existent "VERSION"
=> Fix commit creation during release

make-release.sh
Minor fixes for the GH Actions release workflow
=> Small fixes to release workflow

devfile.yaml
Upgraded typescript plugin to 1.35.1
Fixes https://github.com/eclipse/che/issues/18478
N/A
N/A
=> Upgrade typescript plugin to latest

devfile.yaml, webpack.config.dev.js
Fix development mode for the main-react branch.
https://github.com/eclipse/che/issues/18824
=> Fix development mode for the 'main-react' branch

.github/workflows/ci.yaml, .github/workflows/pr.yaml, README.md, devfile.yaml, package.json
This PR improves GH workflows in order to:
- use GH actions to build and push images;
- build multi-platform images using isolated builders;
- build test image of che-server if che-dashboard image is built successfully for at least the default platform.
=> update GH workflows

webpack.config.common.js
Fix an error with webpack prettier plugin for development with CHE.
fixed https://github.com/eclipse/che/issues/18829
=> fix an error with webpack prettier plugin

make-release.sh
Restore make-release.sh script that is required for release
=> Restore make-release.sh script

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, apache.Dockerfile, devfile.yaml, license-tool/licenseTool.Dockerfile, package.json, src/services/keycloak/setup.ts, src/services/storageTypes.ts, webpack.config.dev.js, webpack.config.prod-dev.js, yarn.lock
Fix errors for development Dashboard with CHE.
fixed https://github.com/eclipse/che/issues/18829
=> Fix development flow for Dashboard

src/index.tsx, src/services/assets/branding.ts, src/services/bootstrap/PreloadData.ts, src/services/bootstrap/branding.constant.ts, src/services/resource-fetcher/__tests__/index.spec.ts, src/services/resource-fetcher/index.ts, src/store/configureStore.ts
Adds CDN resources prefetching.
https://github.com/eclipse/che/issues/18728
=> implemented CDN resources prefetching

.github/workflows/ci.yaml, .github/workflows/pr.yaml, apache.Dockerfile
This PR updates dockerfile in order to fix multiplatform build.
N/a
=> Update dockerfile for multiplatform build

.deps/EXCLUDED/prod.md, .deps/prod.md, devfile.yaml, package.json, src/Layout/Header/Tools/__tests__/index.spec.tsx, src/Layout/Header/Tools/index.tsx, src/Layout/Navigation/__tests__/RecentList.spec.tsx, src/Routes.tsx, src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, src/pages/GetStarted/GetStartedTab/__tests__/SamplesListToolbar.spec.tsx, src/pages/GetStarted/GetStartedTab/__tests__/TemporaryStorageSwitch.spec.tsx, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/pages/UserAccount/__tests__/__snapshots__/index.spec.tsx.snap, src/pages/UserAccount/__tests__/index.spec.tsx, src/pages/UserAccount/index.tsx, src/route.enum.ts, src/services/bootstrap/PreloadData.ts, src/store/UserProfile.ts, src/store/__mocks__/store.ts, src/store/__mocks__/storeBuilder.ts, src/store/index.ts, yarn.lock
Add a new User Account page.
The related  [PR](https://github.com/eclipse/che-workspace-client/pull/52)
fixes https://github.com/eclipse/che/issues/18685
=> Add User Account

.github/workflows/ci.yaml
Fixes CI workflow to properly build the multi-platform image.
fixes https://github.com/eclipse/che/issues/18964
=> Fix multi-platform build in CI workflow

src/services/cheWorkspaceClient/index.ts
This PR provides a refresh token when receiving an activity event from the CHE Editor.
https://github.com/eclipse/che/issues/18946
=> Add refreshing of the token on an activity event from Che Editor

README.md
Adds in header.warning explanation to the readme
=> Update readme with header.warning explanation

.deps/EXCLUDED/dev.md, .deps/dev.md, .deps/prod.md, jest.config.js, package.json, src/containers/FactoryLoader.tsx, src/pages/UserPreferences/RegistryUrl/__tests__/__snapshots__/index.spec.tsx.snap, src/pages/UserPreferences/RegistryUrl/index.tsx, src/pages/UserPreferences/index.tsx, yarn.lock
Quick fixes:
- Propagate override parameters to the factory.
- Remove  URL validation check for the container registry.
fixed https://github.com/eclipse/che/issues/18959
=> Quick fixes

src/app/navbar/navbar.controller.ts
Use cheCli from branding instead of hard-coded.
It fixes https://issues.redhat.com/browse/CRW-1583
=> Use cheCli from branding instead of hard-coded

src/components/DevfileEditor/index.tsx
This PR fixes https://github.com/eclipse/che/issues/19021 by adding in the range locations
https://github.com/eclipse/che/issues/19021
=> Use positions when converting to completion result

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json
This PR upgrades to the latest workspace client with logs publishing fix.
Fixes https://github.com/eclipse/che/issues/19028
=> Use the latest workspace client with logs publishing fix

src/containers/IdeLoader.tsx, src/containers/WorkspaceDetails.tsx, src/containers/WorkspacesList.tsx, src/pages/UserPreferences/index.tsx, src/services/bootstrap/PreloadData.ts, src/services/cheWorkspaceClient/index.ts, src/store/Branding.ts
This PR fixed preload data queue.
fixed https://github.com/eclipse/che/issues/19020
=> fix preload data queue

src/services/keycloak/auth.ts, src/store/Workspaces/index.ts
This PR forces UD to update the token before performing the start workspace request.
fixes https://github.com/eclipse/che/issues/19045
=> Force update token on before workspace start

src/store/Workspaces/index.ts
Fix listening to workspace logs and statuses.
It fixes the issue that workspace status is not updated when it's started.
The reason why we must not unsubscribe - unsubscribe does not have scope: 
https://github.com/eclipse/che/blob/master/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/notification/RemoteSubscriptionManager.java#L79
We potentially could stop listening to runtime logs when workspace is started, but it will work until user won't get two starting workspaces, which is possible with configuration.
Issue is created to make workspace client clearer https://github.com/eclipse/che/issues/19349
I've just created on https://github.com/eclipse/che/issues/19348
=> Fix listening to workspace logs and statuses

.deps/dev.md, .deps/prod.md, license-tool/src/bump-deps.js, package.json, src/containers/FactoryLoader.tsx, src/containers/__tests__/FactoryLoader.spec.tsx, src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/DevfileSelect.tsx, src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx, src/pages/GetStarted/CustomWorkspaceTab/index.tsx, src/pages/GetStarted/GetStartedTab/__tests__/GetStartedTab.spec.tsx, src/pages/GetStarted/GetStartedTab/index.tsx, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/services/__tests__/storageTypes.spec.ts, src/services/storageTypes.ts, src/store/__mocks__/devfile.ts, src/typings/che.d.ts, yarn.lock
Apply the preferred type for creating a new workspace from a sample flow.
fixes get started case in https://github.com/eclipse/che/issues/19069
fixes https://github.com/eclipse/che/issues/19250
=> Apply the preferred type for creating a new workspace from a sample flow

src/pages/UserPreferences/index.tsx
Fix typos in registry action errors
No issue is created.
=> Fix typos in registry action errors

src/services/workspace-client/cheWorkspaceClient.ts
Fix the refresh token callback
fixes https://github.com/eclipse/che/issues/19403
=> Fix the refresh token callback

README.md, webpack.config.prod-dev.js
Update documentation on how to develop against a remote server
Also remove che.openshift.io reference as it has been deleted
N/A
N/A
N/A
=> chore(commands): Update documentation about how to develop che-dashboard

src/Layout/Header/__tests__/__snapshots__/index.spec.tsx.snap, src/Layout/Header/__tests__/index.spec.tsx, src/Layout/Header/index.tsx, src/Layout/Navigation/RecentItem.tsx, src/Layout/Navigation/RecentItemWorkspaceActions.tsx, src/Layout/Navigation/RecentList.tsx, src/Layout/Navigation/__tests__/RecentItem.spec.tsx, src/Layout/Navigation/__tests__/RecentList.spec.tsx, src/Layout/Navigation/__tests__/__snapshots__/RecentItem.spec.tsx.snap, src/Layout/Navigation/index.module.css, src/Layout/Navigation/index.tsx, src/Layout/index.tsx, src/components/DevfileEditor/index.tsx, src/containers/IdeLoader.tsx, src/containers/WorkspaceActions/index.tsx, src/containers/WorkspaceDetails.tsx, src/containers/__tests__/IdeLoader.spec.tsx, src/pages/FactoryLoader/FactoryLoader.styl, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/pages/GetStarted/index.tsx, src/pages/IdeLoader/IdeLoader.styl, src/pages/WorkspaceDetails/DevfileTab/DevfileTab.styl, src/pages/WorkspaceDetails/index.tsx, src/services/helpers/types.ts, src/store/Workspaces/index.ts
Add navbar actions.
fixes https://github.com/eclipse/che/issues/19072
=> Add navbar actions

.github/workflows/codecov.yaml, README.md
- GH workflow to upload test coverage reports to [app.codecov.io](https://app.codecov.io/gh/eclipse/che-dashboard)
- test coverage badge in README.md
=> add codecov workflow

src/Layout/Header/__tests__/__snapshots__/index.spec.tsx.snap, src/Layout/Header/__tests__/index.spec.tsx, src/Layout/Header/index.tsx, src/Layout/Navigation/RecentItem.tsx, src/Layout/Navigation/RecentItemWorkspaceActions.tsx, src/Layout/Navigation/RecentList.tsx, src/Layout/Navigation/__tests__/RecentItem.spec.tsx, src/Layout/Navigation/__tests__/RecentList.spec.tsx, src/Layout/Navigation/__tests__/__snapshots__/RecentItem.spec.tsx.snap, src/Layout/Navigation/index.module.css, src/Layout/Navigation/index.tsx, src/Layout/index.tsx, src/components/DevfileEditor/index.tsx, src/containers/IdeLoader.tsx, src/containers/WorkspaceActions/index.tsx, src/containers/WorkspaceDetails.tsx, src/containers/__tests__/IdeLoader.spec.tsx, src/pages/FactoryLoader/FactoryLoader.styl, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/pages/GetStarted/index.tsx, src/pages/IdeLoader/IdeLoader.styl, src/pages/WorkspaceDetails/DevfileTab/DevfileTab.styl, src/pages/WorkspaceDetails/index.tsx, src/services/helpers/types.ts, src/store/Workspaces/index.ts
Add navbar actions.
fixes https://github.com/eclipse/che/issues/19072
=> [7.28.x] Add navbar actions

src/Layout/Header/__tests__/__snapshots__/index.spec.tsx.snap, src/Layout/Header/index.tsx, src/Layout/Navigation/MainItem.tsx, src/Layout/Navigation/MainList.tsx, src/Layout/Navigation/RecentList.tsx, src/Layout/Navigation/__tests__/MainItem.spec.tsx, src/Layout/Navigation/__tests__/MainList.spec.tsx, src/Layout/Navigation/index.module.css, src/Layout/Navigation/index.tsx, src/Routes/index.tsx, src/pages/GetStarted/index.tsx, src/store/Workspaces/selectors.ts
Restyle left-nav bar.
fixes https://github.com/eclipse/che/issues/18980
=> Restyle left-nav bar

.deps/dev.md, license-tool/licenseTool.Dockerfile, yarn.lock
Upgrade y18n from 4.0.0 to 4.0.1
=> Upgrade y18n from 4.0.0 to 4.0.1

package.json, src/containers/FactoryLoader.tsx, src/containers/__tests__/FactoryLoader.spec.tsx, src/store/FactoryResolver.ts, yarn.lock
Add Che Server functionality for devfile v1 overrides.
fixed https://github.com/eclipse/che/issues/19424
=> Add Che Server functionality for devfile v1 overrides

src/Layout/Navigation/index.tsx, src/Routes/__tests__/index.spec.tsx, src/Routes/index.tsx, src/containers/FactoryLoader.tsx, src/containers/IdeLoader.tsx, src/containers/WorkspaceActions/context.tsx, src/containers/WorkspaceActions/index.tsx, src/containers/WorkspaceDetails.tsx, src/pages/WorkspaceDetails/index.tsx, src/pages/WorkspacesList/Rows.tsx, src/pages/WorkspacesList/index.tsx, src/services/helpers/location.ts
This PR fixes unwanted switching to the Overview tab after saving changes in the Editor tab. 
depends on https://github.com/eclipse-che/che-dashboard/pull/217
fixes https://github.com/eclipse/che/issues/19589
=> Fix unwanted switching to the Overview tab

src/Layout/index.tsx, src/pages/WorkspaceDetails/EditorTab/EditorTab.styl, src/services/workspace-client/cheWorkspaceClient.ts, src/store/Workspaces/cheWorkspaces/index.ts
Fix token refresher for single-user.
fixes https://github.com/eclipse/che/issues/19499
=> Fix token refresher for single-user

src/services/workspace-client/devWorkspaceClient.ts
This PR switches to using patch instead of update when creating devworkspaces
https://github.com/eclipse/che/issues/19788
=> Use patch instead of update when creating devworkspaces

package.json, src/services/workspace-client/devWorkspaceClient.ts, src/services/workspaceAdapter/index.ts, src/store/__mocks__/devWorkspaceBuilder.ts, yarn.lock
This PR updates all devworkspace instances from ideUrl to mainUrl.
Part of https://github.com/devfile/devworkspace-operator/issues/399
=> Rename devworkspace url instances from ideUrl to mainUrl

src/containers/FactoryLoader.tsx
This PR switches from using workspace.status to other workspace event booleans. This fixes an issue where a running devworkspace created by a factory url isn't automatically opened
Fixes https://github.com/eclipse/che/issues/19800
=> Fix devworkspace factories not opening ide when the devworkspace is running

src/pages/WorkspacesList/__tests__/index.spec.tsx, src/pages/WorkspacesList/index.tsx
Fixes inconsistent capitalization.
[Restart in Verbose Mode link #19428](https://github.com/eclipse/che/issues/19428)
[Fix inconsistent capitalization #1972](https://github.com/eclipse/che-docs/pull/1972)
[Fix inconsistent capitalization #1974](https://github.com/eclipse/che-docs/pull/1974)
=> Fix inconsistent capitalization

src/Routes/__tests__/index.spec.tsx, src/components/Head/__tests__/Head.spec.tsx, src/components/Head/__tests__/__snapshots__/Head.spec.tsx.snap, src/pages/GetStarted/GetStartedTab/ImportFromGit/GitRepoLocationInput.tsx, src/pages/GetStarted/GetStartedTab/ImportFromGit/index.tsx, src/pages/GetStarted/GetStartedTab/SampleCard.tsx, src/pages/GetStarted/GetStartedTab/SamplesListHeader.tsx, src/pages/GetStarted/GetStartedTab/index.tsx, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/pages/GetStarted/index.tsx
Redesign Get Started page & Introduce Import from git
fixed https://github.com/eclipse/che/issues/18975
=> redesign Get Started page & Introduce Import from git

src/services/bootstrap/PreloadData.ts
This PR provides the tiny refactoring for PreloadData class: requests for user info and workspaces list are performed at one time with the rest of the requests.
=> Reorganised preloading sequence

src/Layout/Navigation/index.tsx, src/Routes/__tests__/index.spec.tsx, src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/DevfileLocationInput.tsx, src/pages/GetStarted/GetStartedTab/ImportFromGit/GitRepoLocationInput.tsx, src/pages/GetStarted/GetStartedTab/ImportFromGit/index.tsx, src/pages/GetStarted/GetStartedTab/index.tsx, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/pages/GetStarted/index.tsx, src/route.enum.ts, src/services/helpers/location.ts, src/services/helpers/types.ts
Quick fix for the create workspace page:
- prevent page refresh when when we click Enter;
- add a placeholder;
- rename routes;
fixes https://github.com/eclipse/che/issues/18975
=> Quick fix for the create workspace page

package.json, src/containers/FactoryLoader.tsx, src/containers/__tests__/FactoryLoader.spec.tsx, src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx, src/pages/GetStarted/CustomWorkspaceTab/index.tsx, src/pages/GetStarted/GetStartedTab/ImportFromGit/index.tsx, src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, src/pages/GetStarted/GetStartedTab/__tests__/GetStartedTab.spec.tsx, src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, src/pages/GetStarted/GetStartedTab/index.tsx, src/pages/GetStarted/index.tsx, src/services/helpers/types.ts, src/services/workspace-client/devWorkspaceClient.ts, src/store/FactoryResolver.ts, src/store/Workspaces/devWorkspaces/index.ts, src/store/Workspaces/index.ts, yarn.lock
Resolve che-theia plug-ins
It embeds the che-theia and devfile library to update devWorkspace templates if there are some che-theia plug-ins
It also resolve optional files content
https://user-images.githubusercontent.com/436777/121185653-9364ac80-c866-11eb-8c60-813f4fc74657.mp4
https://github.com/eclipse/che/issues/19927
1. Use sample from get started page
OR
2. Use $CHE_HOST/#https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/devfile.yaml as factory link and make sure redhat/java plugin is present after workspace is started
=> feat(che-theia): Resolve plug-ins for che-theia editor

src/store/DevfileRegistries/index.ts
This PR updates the editor in the dashboard to use schema version 2.1.0.
It depends on https://github.com/eclipse-che/che-server/pull/25
=> feat: add support for all available devfile schema versions

package.json, src/app.styl, src/overrides.styl, src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/index.tsx, src/pages/GetStarted/CustomWorkspaceTab/index.tsx, src/pages/GetStarted/GetStartedTab/ImportFromGit/index.tsx, src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, src/pages/GetStarted/__tests__/updateDevfileMetadata.spec.ts, src/pages/GetStarted/updateDevfileMetadata.ts, src/store/DevfileRegistries/selectors.ts, src/store/FactoryResolver/getDevfile.ts, src/store/FactoryResolver/index.ts, src/store/__tests__/FactoryResolver/getDevfile.spec.ts, src/typings/che.d.ts, yarn.lock
This PR provide adding a metadata about the origin of the devfile with DevWorkspace(it depends on the case):
1. From devfile location (https://gist.githubusercontent.com/l0rd/71a04dd0d8c8e921b16ba2690f7d5a47/raw/d520086e148c359b18c229328824dfefcf85e5ef/spring-petclinic-devfile-v2.0.0.yaml)
```
annotations:
che.eclipse.org/devfile-source: |
url:
location:  >-https://gist.githubusercontent.com/l0rd/71a04dd0d8c8e921b16ba2690f7d5a47/raw/d520086e148c359b18c229328824dfefcf85e5ef/spring-petclinic-devfile-v2.0.0.yaml
```
2. From project location (https://github.com/l0rd/spring-petclinic/tree/bfbad6a85aee019018e9c67bcec7ff759af7de1d)
```
annotations:
che.eclipse.org/devfile-source: |
scm:
repo: 'https://github.com/l0rd/spring-petclinic.git'
revision: …
```
=> Provide metadata about the origin of the devfile with DevWorkspace

.vscode/launch.json, src/containers/WorkspaceDetails.tsx, src/pages/GetStarted/index.tsx, src/services/helpers/__tests__/getErrorMessage.spec.ts, src/services/helpers/getErrorMessage.ts, src/store/Workspaces/index.ts
Cherry-pick from the main branch 73f536d4e1e228b56ecad4293e72b916b89b1ffa
=> Fix error messages

src/pages/GetStarted/index.tsx
this PR fixes create workspace page title according to https://marvelapp.com/prototype/9a777d1/screen/75805138
fixes https://github.com/eclipse/che/issues/19890
N/A
I'll update doc in the scope of https://github.com/eclipse/che/issues/19949
=> fix create workspace page title

src/pages/IdeLoader/__tests__/__snapshots__/IdeLoader.spec.tsx.snap, src/pages/IdeLoader/index.tsx
added acces for clipboard in iframe
https://github.com/eclipse/che/issues/17475
=> feat: fix for copy paste  issue in chromium environment

.ci/common.sh, .ci/oci-dashboard-happy-path.sh, .ci/openshift-ci/Dockerfile, .ci/resources/htpasswdProvider.yaml, .ci/resources/pod-che-happy-path.yaml, .ci/resources/users.htpasswd
Create base PR for check triggering and launching PROW CI JOB
=> Create CI JOB for checkiing happy path testflow of the che-dashbpard project

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
fix: upgrade devworkspace client to one which correctly handles namespaces creation
it's the last piece for, so it fixes https://github.com/eclipse/che/issues/20014
=> fix: upgrade devworkspace client to one which correctly handles namespaces creation

.ci/common.sh, .ci/oci-dashboard-happy-path.sh, .ci/openshift-ci/Dockerfile, .ci/resources/htpasswdProvider.yaml, .ci/resources/pod-che-happy-path.yaml, .ci/resources/users.htpasswd
Add scripts and resources in .ci folder for running the factory-happy-path test on th PROW CI
=> Add scripts of PROW ci job for checking PR

.ci/oci-dashboard-happy-path.sh
fix bumping info after happy path test
N/A
=> fix bumping info after happy path test

build/dockerfiles/rhel.Dockerfile
Added command to install yarn from the npm registry.
=> Fix rhel.Dockerfile

build/dockerfiles/Dockerfile
=> Increase network timeout for installing dependencies

.github/workflows/release.yml, make-release.sh
Fixes for Che Dashboard release script
- fix sed that didn't work on linux
- add npm and lerna installation into GH workflow runner
N / A
=> fix: Fixes for release script and workflow

packages/dashboard-frontend/src/store/BannerAlert/index.ts, packages/dashboard-frontend/src/store/Branding/index.ts, packages/dashboard-frontend/src/store/DevfileRegistries/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/index.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/index.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts, packages/dashboard-frontend/src/store/User/index.ts, packages/dashboard-frontend/src/store/UserPreferences/index.ts, packages/dashboard-frontend/src/store/UserProfile/index.ts, packages/dashboard-frontend/src/store/Workspaces/Settings/index.ts, packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts, packages/dashboard-frontend/src/store/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/store/helpers.ts
This PR makes registries objects metadata to be merged to prevent the cause when the following piece of metadata overwrites the previous one.
fixes https://issues.redhat.com/browse/CRW-2116
=> Merge registries metadata

packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/index.tsx, packages/dashboard-frontend/src/components/BannerAlert/index.tsx, packages/dashboard-frontend/src/services/helpers/detectBrowser.ts, packages/dashboard-frontend/src/store/Branding/index.ts
Cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/315
https://issues.redhat.com/browse/CRW-2086
=> Dashboard warns users that Safari is not supported

make-release.sh
- Fix version not bumped in main branch after major release
- use semantic commit messages in release script
=> fix: Release script fixes

packages/dashboard-frontend/src/services/workspace-client/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
Provides CHE_PLUGIN_REGISTRY_INTERNAL_URL env variable to dev containers
https://github.com/eclipse/che/issues/20402
=> feat: provides CHE_PLUGIN_REGISTRY_INTERNAL_URL into devContainers

.ci/resources/pod-che-happy-path.yaml, .github/workflows/pr.yml, packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/types/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
See bellow
It backports the following PRs:
- https://github.com/eclipse-che/che-dashboard/pull/331;
- https://github.com/eclipse-che/che-dashboard/pull/332;
=> feat: provides CHE_PLUGIN_REGISTRY_INTERNAL_URL into devContainers & fix dw happy path test

README.md
Fix links for branding related resources in README.md.
none.
No need.
none.
=> Fix links for branding related resources.

packages/dashboard-frontend/src/services/workspace-client/cheWorkspaceClient.ts, packages/dashboard-frontend/src/services/workspace-client/devWorkspaceClient.ts, packages/dashboard-frontend/src/services/workspaceAdapter/helper.ts, packages/dashboard-frontend/src/services/workspaceAdapter/index.ts
Prevent crashing UD in the following cases:
1. DevWorkspace status is not present.
2. KubernetesNamespace default attribute is not present.
=> fix: prevent crashing UD

README.md
=> docs: fix command

.deps/EXCLUDED/prod.md, lerna.json, package.json, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json, packages/static-server/package.json
Bump version to 7.37.0-SNAPSHOT
N/A
=> Bump version to 7.37.0-SNAPSHOT

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/services/helpers/getErrorMessage.ts
Fix factory error messages.
fixed https://github.com/eclipse/che/issues/20365
=> Fix factory error messages

packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts
Fix wrong devfile doc url
https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/ is 404
=> fix: Fix wrong devfile doc url

packages/dashboard-backend/src/devworkspace-client/__tests__/errors.spec.ts, packages/dashboard-backend/src/devworkspace-client/__tests__/utils/suite.ts, packages/dashboard-backend/src/devworkspace-client/services/api/workspace-api.ts
fix: better handle K8s client error while watching.
N/A
=> fix: better handle K8s client error while watching

.github/PULL_REQUEST_TEMPLATE.md
feat: add a section into PR templates about test cases
N/A
that's not tested since it's just PR template changes.
=> feat: add a section into PR templates about test cases

packages/common/tsconfig.json, packages/dashboard-backend/jest.config.js, packages/dashboard-backend/package.json, packages/dashboard-backend/tsconfig.json, packages/dashboard-backend/webpack.config.common.js, packages/dashboard-backend/webpack.config.dev.js, packages/dashboard-frontend/webpack.config.dev.js
- generates a source map for the `common` package
- uses that source map while debugging frontend or backend packages.
=> Improve dashboard debugging convenience 

README.md, local-start.sh, packages/dashboard-backend/src/index.ts, packages/dashboard-backend/src/local-run/che-server.ts, packages/dashboard-frontend/package.json, packages/dashboard-frontend/webpack.config.common.js, packages/dashboard-frontend/webpack.config.dev-server.js, packages/dashboard-frontend/webpack.config.dev.js, packages/dashboard-frontend/webpack.config.prod.js
The goal of this PR is to make running local Frontend and Backend easier and more straightforward.
=> Improve dev flow

.deps/prod.md, make-release.sh
fix: make-release now respect up to date common package.
No issue is created
=> fix: make-release now respect up to date common package

packages/dashboard-frontend/src/store/Branding/index.ts
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/362
https://issues.redhat.com/browse/CRW-1948
=> Fix updating branding data

packages/dashboard-frontend/package.json
Back port of https://github.com/eclipse-che/che-dashboard/pull/366
Part of https://github.com/eclipse-che/che-theia/pull/1222
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
https://issues.redhat.com/browse/CRW-1731
TBD
=> Bump version of @eclipse-che/che-theia-devworkspace-handler to the latest released

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.debugMode.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
=> Escape slashes in paths

.github/workflows/codecov.yml, .github/workflows/next-build-multiarch.yml, .github/workflows/pr.yml, .github/workflows/release.yml
Update runners to fixed Ubuntu 20.04 version
https://github.com/eclipse/che/issues/20516
=> chore: update runners to ubuntu 20.04

.deps/dev.md, .deps/problems.md, .deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Update che-theia library using devfile API
only a dependency has been updated, no code change in che-theia library logic
N/A
Tried to start a workspace with che-theia and it was working
=> feat: use newer theia lib

packages/dashboard-frontend/src/containers/FactoryLoader/__tests__/converter.spec.ts, packages/dashboard-frontend/src/containers/FactoryLoader/devfile-converter.ts, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/Workspaces/Settings/selectors.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
This is cherry-picked https://github.com/eclipse-che/che-dashboard/pull/387
https://issues.redhat.com/browse/CRW-2411
=> Convert devfile v2 to devfile v1

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Use the newer theia library
https://github.com/eclipse-che/che-theia/pull/1249
Fixes https://github.com/eclipse/che/issues/20725
It was tested using the repositories listed in the issue (using the factory workflow)
=> chore: bump to the latest theia DW library

.deps/dev.md, .deps/prod.md, packages/dashboard-backend/package.json, yarn.lock
Upgrade "fastify-static" to version 4.4.2 to fix potential security vulnerabilities.
=> chore(deps): upgrade fastify-static

packages/dashboard-backend/src/services/kubeclient/dwClientProvider.ts, packages/dashboard-backend/src/services/kubeclient/keycloak.ts
Added native auth on kubernetes.
fixes https://github.com/eclipse/che/issues/20677
=> Added native auth on kubernetes

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/406
https://issues.redhat.com/browse/CRW-2411?focusedCommentId=19350430&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19350430
=> fix devfile converter usage

packages/dashboard-frontend/src/services/registry/devfiles.spec.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts
Handle cases where links are not only with string type
Fixes https://github.com/eclipse/che/issues/20827
Click on any 'sample'
=> fix: handle links that may not be string but objects

packages/dashboard-backend/src/api/templateApi.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/devWorkspaceTemplateApi.ts
=> Remove unused API endpoints

local-start.sh, packages/common/src/dto/api.ts, packages/dashboard-backend/src/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/index.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/services/helpers/index.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-backend/src/index.ts
Added server config API to dashboard-backend.
=> Added serverConfig API

packages/dashboard-frontend/src/components/LogsTab/__tests__/__snapshots__/LogsTab.spec.tsx.snap, packages/dashboard-frontend/src/components/LogsTab/index.tsx, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/IdeLoader.tsx, packages/dashboard-frontend/src/containers/WorkspaceActions/index.tsx, packages/dashboard-frontend/src/containers/__tests__/IdeLoader.spec.tsx, packages/dashboard-frontend/src/pages/FactoryLoader/__tests__/__snapshots__/FactoryLoader.spec.tsx.snap, packages/dashboard-frontend/src/pages/FactoryLoader/index.tsx, packages/dashboard-frontend/src/pages/IdeLoader/index.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Fix devworkspace startup failure handler.
fixes https://github.com/eclipse/che/issues/19684
https://user-images.githubusercontent.com/6310786/144446250-3741485c-5f29-428f-b45d-e8557bc1f99c.mov
=> Fix devworkspace startup failure handler

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json, yarn.lock
We have `dash-licenses` check failing for a while, this PR does the following changes to fix that check:
- removes `tslint` as it's not used anymore
- upgrades `umd-compat-loader` to v2.1.2
- adds a few dependencies to the exclusions list (those scored highly by clearlydefined)
=> review dependencies

README.md
documentation on memory for devserver
N/A
using it to develop che-dashboard
=> docs: memory issue

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SampleCard.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/SampleCard.spec.tsx
Add a relevant tag into the sample card.
fixes https://github.com/eclipse/che/issues/19633
=> Add a relevant tag into the sample card

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SampleCard.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.module.css
=> Fix workspacesList styles

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Update che-code dependency
N/A
yes, starts with a che code repository
https://che-server#https://github.com/che-incubator/che-code (ensure cpu and memory is enough on the cluster)
=> feat: update che-code dependency

lerna.json, make-release.sh, package.json, packages/common/package.json, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json
Instead of `SNAPSHOT`, use `next` prefix, to signify development version in `main` branch
Fix updating the next version, as PR may not get greated due to a specific error message
https://github.com/eclipse/che/issues/21044
=> fix: fix update to next version

README.md, package.json, packages/dashboard-backend/src/index.ts, packages/dashboard-backend/src/local-run/dexHelper.ts, packages/dashboard-backend/src/services/kubeclient/dwClientProvider.ts, packages/dashboard-backend/src/services/kubeclient/kubeConfigProvider.ts, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/components/Workspace/Indicator/index.module.css, packages/dashboard-frontend/src/pages/WorkspacesList/index.module.css, run/prepare-local-run.sh, run/revert-local-run.sh, yarn.lock
This PR fixes local start flow with OpenShift and upgrade vulnerable libraries.
```
yarn
yarn start:prepare
yarn start
yarn start:revert
```
=> Fix local start flow

make-release.sh
Fix remaining mistakes to version update script
=> fix: fix release version bumpinb errors

.deps/dev.md, .deps/prod.md, README.md, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR decreases the time of workspaces conversion by removing an unnecessary patch request.
https://user-images.githubusercontent.com/16220722/151791733-6d196541-6e45-4587-bf00-88eaef26563f.mov
fixes https://github.com/eclipse/che/issues/21092
=> Decrease workspaces converting time

.github/workflows/codecov.yml
=> Bump codecov-action

packages/dashboard-frontend/src/containers/IdeLoader.tsx, packages/dashboard-frontend/src/containers/__tests__/IdeLoader.spec.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.changeWorkspaceStatus.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/471 to the 7.44.x branch
Fixes https://github.com/eclipse/che/issues/21134 in 7.44.x
See process in original PR
N/A
N/A
=> Cherry-pick changes for #471 to 7.44.x branch

packages/dashboard-backend/src/api/clusterConfig.ts, packages/dashboard-backend/src/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts
=> Code refactoring

packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/containers/__tests__/IdeLoader.spec.tsx, packages/dashboard-frontend/src/services/helpers/jestUtils.ts
This PR fixes unit tests for the IdeLoader container in order to make sure that defined mocks are not called.
=> Fix unit tests

packages/common/src/helpers/__tests__/errors.spec.ts, packages/common/src/helpers/errors.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/selectors.ts
This PR is cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/483
=> Fix "blank" screen regression

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
backport fix of https://github.com/eclipse/che/issues/21290
Fixes https://github.com/eclipse/che/issues/21290
=> fix: handle ephemeral in devfile converter

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/selectors.ts
Fix devWorkspace status update flow.
=> Fix devWorkspaces update flow

packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/Dropdown/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/selectors.ts
Cherry-pick for [Fix workspace details page status update](https://github.com/eclipse-che/che-dashboard/pull/497)
Cherry-pick for [Fix devWorkspaces update flow](https://github.com/eclipse-che/che-dashboard/pull/496)
=> Fix workspace details page status update 

packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/ConversionButton/index.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.tsx, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/helpers/__tests__/types.spec.ts, packages/dashboard-frontend/src/services/helpers/types.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/495
=> fix: regression with deleting a devworkspace from the list

packages/dashboard-frontend/src/pages/WorkspaceDetails/InlineAlerts/index.tsx
fix: Updating broken link for the devfile v2 migration docs
Should be also cherry-picked in 7.44.x
related to https://github.com/eclipse/che/issues/21005#issuecomment-1070554147
=> fix: Updating broken link for the devfile v2 migration docs

packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.conversion.spec.tsx, packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/507 to the 7.46.x branch
Fixes https://github.com/eclipse/che/issues/21032 in 7.46.x
See the process in original PR
=> fix: single running workspace restriction for DevWorkspaces

lerna.json, package.json, packages/common/package.json, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json
bumping the version in the package.json
related to https://github.com/eclipse/che/issues/21339
=> chore: bumping the version

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, build/dockerfiles/Dockerfile, build/dockerfiles/rhel.Dockerfile, packages/dashboard-backend/src/factory.ts, packages/dashboard-backend/src/index.ts, packages/dashboard-backend/src/local-run/che-server.ts, packages/dashboard-backend/src/local-run/dexHelper.ts, packages/dashboard-backend/src/static.ts, packages/dashboard-frontend/index.html, packages/dashboard-frontend/src/Routes/__tests__/index.spec.tsx, packages/dashboard-frontend/src/Routes/index.tsx, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx, packages/dashboard-frontend/src/preload/__tests__/location.spec.ts, packages/dashboard-frontend/src/preload/index.html, packages/dashboard-frontend/src/preload/index.ts, packages/dashboard-frontend/src/services/helpers/location.ts, packages/dashboard-frontend/static/loader.html, packages/dashboard-frontend/webpack.config.common.js, packages/dashboard-frontend/webpack.config.dev-server.js, run/local-run.sh, yarn.lock
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/501 to the 7.46.x branch.
These changes depend on https://github.com/eclipse-che/che-operator/commit/2f0183e32bdfcd309b2cb2497e8d203560328fb7.
Fixes https://github.com/eclipse/che/issues/20463 in 7.46.x
See the process in original PR
=> Handle new factory link while unauthorized  (#501)

.deps/EXCLUDED/dev.md, .deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/src/services/devfile/__tests__/devfileAdapter.spec.ts, packages/dashboard-frontend/src/services/devfile/converters.ts
This PR adds a sidecar policy `mergeImage` to converted devfiles v2 to run plug-ins in sidecar containers (it's important if there isn't any dev container).
fixes https://github.com/eclipse/che/issues/21120
1. Create Che7 workspaces using swagger (`https://che-host/swagger`) from these devfiles: [apache-camel-k](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/apache-camel-k/devfile.yaml), [che4z](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/che4z/devfile.yaml), [rust](https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/rust/devfile.yaml)
2. Convert each workspace and make sure there aren't any errors.
=> Fix conversion issue

make-release.sh
Fix the script not pushing the bumping PR branch correctly
=> fix: fix version bumping during release

packages/dashboard-frontend/src/Routes/index.tsx, packages/dashboard-frontend/src/preload/index.ts
Add a new route for Factory flow
fixes https://issues.redhat.com/browse/CRW-2907
=> Add a new route for Factory flow

.deps/EXCLUDED/dev.md, .deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/devWorkspaceSpecTemplates.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/typings/che.d.ts
cherry-picked PR https://github.com/eclipse-che/che-dashboard/pull/522
=> fix: add registries and dashboard url to all containers

packages/dashboard-frontend/src/components/Header/__tests__/__snapshots__/Header.spec.tsx.snap, packages/dashboard-frontend/src/components/Header/index.tsx, packages/dashboard-frontend/src/pages/FactoryLoader/__tests__/__snapshots__/FactoryLoader.spec.tsx.snap, packages/dashboard-frontend/src/pages/IdeLoader/__tests__/__snapshots__/IdeLoader.spec.tsx.snap, packages/dashboard-frontend/src/pages/IdeLoader/index.tsx
Add breadcrumbs to IDE and Factory loaders.
fixes https://github.com/eclipse/che/issues/21368
https://user-images.githubusercontent.com/6310786/166315628-c004b117-2e61-4acd-9ef8-e019c8af8bf7.mov
=> Add breadcrumbs the factory loading page.

packages/dashboard-frontend/src/services/helpers/__tests__/getProjectName.spec.ts, packages/dashboard-frontend/src/services/helpers/getProjectName.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV1.ts
Modify a regular expression for the project name.
fixes https://github.com/eclipse/che/issues/21338
Try to create a factory with uppercase characters in the name.
For example ```<CHE-URL>/#/https://github.com/SkorikSergey/TestRepo```
=> Modify a regular expression for the project name

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
update zip location to match local network
https://issues.redhat.com/browse/CRW-3011
[unit test in devfile-converter library](https://github.com/che-incubator/devfile-converter/commit/158532917deec3183193142791f8413a021aefe2)
=> fix: handle zip locations when migrating from v1 to v2

.deps/EXCLUDED/dev.md, .deps/dev.md, .deps/prod.md, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json, yarn.lock
=> Upgrade vulnerable libraries

.github/workflows/pr.yml
cherry-pick https://github.com/eclipse-che/che-dashboard/pull/536
=> Skip licenses check

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
update zip location to match local network
https://issues.redhat.com/browse/CRW-3011
[new unit tests in devfile-converter library](https://github.com/che-incubator/devfile-converter/commit/d624e3ed3b5e8a8e9857ae36de783c39aa2fd67c)
=> fix: Update devfile converter to handle zip location updates

packages/dashboard-backend/webpack.config.common.js, packages/dashboard-backend/webpack.config.dev.js, packages/dashboard-backend/webpack.config.prod.js, packages/dashboard-frontend/package.json, packages/dashboard-frontend/webpack.config.dev.js
=> Fix backend build

.github/workflows/codecov.yml, packages/dashboard-backend/jest.config.js, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/services/registry/devfiles.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts, yarn.lock
Fix test coverage report.
fixes https://github.com/eclipse/che/issues/21437
=> Fix test coverage report

.deps/dev.md, .deps/prod.md, README.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/webpack.config.dev.js, yarn.lock
Fix dashboard-frontend build for local development.
=> Fix dashboard-frontend build for local development

README.md, packages/dashboard-frontend/src/Layout/Header/Tools/index.tsx, packages/dashboard-frontend/src/pages/UserAccount/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserAccount/index.tsx, packages/dashboard-frontend/src/services/workspace-client/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/services/workspace-client/helpers.ts, packages/dashboard-frontend/src/services/workspace-client/index.ts, packages/dashboard-frontend/src/store/UserProfile/index.ts
Add handler for 403 server error.
fixes https://issues.redhat.com/browse/CRW-2690
=> Add isForbidden status check

README.md, packages/dashboard-frontend/src/Layout/Header/Tools/index.tsx, packages/dashboard-frontend/src/pages/UserAccount/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserAccount/index.tsx, packages/dashboard-frontend/src/services/workspace-client/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/services/workspace-client/helpers.ts, packages/dashboard-frontend/src/services/workspace-client/index.ts, packages/dashboard-frontend/src/store/UserProfile/index.ts
* feat: add isForbidden status check
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/555 to the 7.46.x branch
=> Add isForbidden status check (#555)

.deps/EXCLUDED/dev.md, .deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-backend/webpack.config.common.js, packages/dashboard-frontend/package.json, packages/dashboard-frontend/webpack.config.common.js, yarn.lock
It fixes the frontend build running in watch mode.
=> fix: frontend build:watch

packages/dashboard-frontend/src/preload/index.ts
Fix redirect to the dashboard.
fixes https://github.com/eclipse/che/issues/21490
=> Fix redirect to the dashboard

packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts
Fix an unstable bug that could happen depending on API response time.
=> fix: change sequence of requests

.deps/dev.md, packages/common/package.json, yarn.lock
=> Upgrade client-node lib

packages/dashboard-frontend/src/pages/UserPreferences/index.tsx
=> Update index.tsx - Fix typo for container vs containter in user prefs dashboard

packages/dashboard-frontend/src/Layout/ErrorReporter/Issue/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/Layout/ErrorReporter/Issue/index.tsx, packages/dashboard-frontend/src/Layout/ErrorReporter/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/Layout/ErrorReporter/index.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/Toolbar/index.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.module.css, packages/dashboard-frontend/src/pages/WorkspacesList/index.tsx
<details>
<summary>Workspace inactivity</summary>
**Before**
**After**
</details>
<details>
<summary>Certificate issues</summary>
**Before**
**After**
</details>
<details>
<summary>SSO issues</summary>
**Before**
**After**
</details>
<details>
<summary>Other issues</summary>
**Before**
**After**
</details>
<details>
<summary>Workspaces List</summary>
**Before**
**After**
</details>
=> Fix styles for ErrorReporter and WorkspacesList

devfile.yaml
Updates `devfile.yaml` to devfile v2.
To test, create a workspace with the new devfile:
```
{CHEHOST}/#https://github.com/eclipse-che/che-dashboard/tree/devfilev2-pr
```
When the editor starts, run each task:
* `installdependencies`
* `build`
* `runtests`
=> chore: update devfile to devfile v2

packages/common/src/dto/api.ts, packages/dashboard-backend/src/constants/examples.ts, packages/dashboard-backend/src/devworkspace-client/services/api/dockerConfigApi.ts, packages/dashboard-frontend/src/store/DockerConfig/dw/index.ts
Fix adding a container registry from _Dashboard_/_User Preferences_.
fixes https://github.com/eclipse/che/issues/21589
=> Fix adding a container registry flow

packages/dashboard-frontend/src/pages/WorkspaceDetails/InlineAlerts/index.tsx
fix: fixing link to devfile v2 migration docs
https://github.com/eclipse/che/issues/21670
=> fix: fixing link to devfile v2 migration docs

packages/common/src/dto/api.ts, packages/dashboard-backend/src/constants/examples.ts, packages/dashboard-backend/src/devworkspace-client/services/api/dockerConfigApi.ts, packages/dashboard-frontend/src/store/DockerConfig/dw/index.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/610 to the 7.52.x branch
fixes https://github.com/eclipse/che/issues/21589
=> fix: devworkspace-container-registry-dockercfg secret (#610)

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SampleCard.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/SampleCard.spec.tsx
Sort samples by visible tag.
fixes https://issues.redhat.com/browse/CRW-2782
=> fix: sort samples by visible tag

packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/570 to the 7.50.x branch
fixes https://issues.redhat.com/browse/CRW-3299
=> fix: Code refactoring

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Prevent patching DevWorkspace during startup.
fixes https://github.com/eclipse/che/issues/21664
=> Prevent patching DevWorkspace during startup

packages/common/src/dto/api.ts, packages/dashboard-backend/src/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
Add external attributes to workspaces
fixes https://github.com/eclipse/che/issues/21691
fixes https://github.com/eclipse/che/issues/21692
=> Add external attributes to workspaces

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Check and update OPENVSX_REGISTRY_URL on created workspaces before starting.
fixes https://github.com/eclipse/che/issues/21654
=> Check and update OPENVSX_REGISTRY_URL  before starting

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/GetStartedTab.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/StorageType/index.tsx, packages/dashboard-frontend/src/services/devfile/__tests__/devfileAdapter.spec.ts, packages/dashboard-frontend/src/services/devfile/adapter.ts, packages/dashboard-frontend/src/services/storageTypes.ts, packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/Settings/selectors.ts, packages/dashboard-frontend/src/typings/che.d.ts
Fix storage type select widget.
=> fix: storage type select widget

packages/dashboard-backend/src/api/devworkspaceWebsocketWatcher.ts, packages/dashboard-backend/src/services/kubeclient/helpers/index.ts, packages/dashboard-backend/src/services/kubeclient/kubeConfigProvider.ts
This PR will prevent the dashboard backend from crashing while parsing some JSONs and preserve logs for further investigation.
https://github.com/eclipse/che/issues/21703
=> fix: prevent the dashboard backend from crashing

packages/dashboard-backend/src/api/devworkspaceWebsocketWatcher.ts, packages/dashboard-backend/src/services/kubeclient/helpers/index.ts, packages/dashboard-backend/src/services/kubeclient/kubeConfigProvider.ts
reverts commit https://github.com/eclipse-che/che-dashboard/commit/aa4d90d8b542f1df0959ddf8fe2e4318a4bd1085
=> Revert "fix: prevent the dashboard backend from crashing (#632)"

packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/services/storageTypes.ts, packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/typings/che.d.ts
Add 'Not defined' storage type
It needs for https://github.com/eclipse/che/issues/21714
=> fix: add 'Not defined' storage type

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Fix workspace status update.
fixes https://github.com/eclipse/che/issues/21748
=> Fix workspace status update

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Fix attributes patch.
fixes https://github.com/eclipse/che/issues/21748
=> fix: attributes patch

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/645 and https://github.com/eclipse-che/che-dashboard/pull/644 to the 7.54.x branch
fixes https://github.com/eclipse/che/issues/21748
=> Fix workspace status update and attributes patch

packages/dashboard-backend/src/api/devworkspaceWebsocketWatcher.ts, packages/dashboard-backend/src/constants/examples.ts, packages/dashboard-backend/src/index.ts, packages/dashboard-backend/src/services/SubscriptionManager.ts, packages/dashboard-backend/src/services/kubeclient/helpers/index.ts
This PR adds logging to the dashboard backend to preserve all JSON.parse errors for further investigation.
https://github.com/eclipse/che/issues/21703
=> Log JSON parsing errors

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/DropdownEditors.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/dropdown-editors.module.css
Fix dropdown editor group styles.
fixes https://issues.redhat.com/browse/CRW-3448
=> Fix dropdown editor group styles

packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/StorageType/index.tsx
Fix copy/paste typos.
fixes https://github.com/eclipse/che/issues/21744
=> Fix copy/paste typos

packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/StorageType/index.tsx
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/651  to the 7.54.x branch
fixes https://github.com/eclipse/che/issues/21744
=> fix: copy/paste typos

build/dockerfiles/Dockerfile
chore: update to node:16.16.0-alpine3.15 to remove dangerous versions of ansi-regex < 5.0.1 (#[20876](https://github.com/eclipse/che/issues/20876))
Change-Id: I79a1ff8e533d88d4e51f97f5f7c6a10b35983849
N/A
https://github.com/eclipse/che/issues/20876
N/A
=> chore: #20876 update to node:16.16.0-alpine3.15 (ansi-regex >=5.0.1)

README.md
chore: badges link to workflows (#21790)
Change-Id: Ie024d8a97cc0cd787d1fd1d82dfac0a6a1a1cd7e
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: badges link to workflows (#21790)

packages/dashboard-frontend/package.json, yarn.lock
Upgrade devworkspace-handler libraries
=> Upgrade devworkspace-handler libraries

packages/dashboard-frontend/package.json, yarn.lock
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/667 to the 7.56.x branch
=> fix: upgrade devworkspace-handler libraries (#667)

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/helpers/retryableExec.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/retryableExec.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceTemplateApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/dockerConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/helpers/prepareCoreV1API.ts, packages/dashboard-backend/src/devworkspaceClient/services/helpers/prepareCustomObjectAPI.ts, packages/dashboard-backend/src/devworkspaceClient/services/helpers/prepareCustomObjectWatch.ts, packages/dashboard-backend/src/devworkspaceClient/services/helpers/retryableExec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/namespaceApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/userProfileApi.ts
Add retry for Kubernetes API requests.
fixes https://github.com/eclipse/che/issues/21532
=> Add retry for Kubernetes API requests

packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
* fix the bootstrap queue
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/679 to the 7.56.x branch
fixes https://github.com/eclipse/che/issues/21809
=> Fix the bootstrap queue (#679)

packages/dashboard-backend/src/constants/schemas.ts
Fixes the regex for devfile schema versions.
=> fix: regex for devfile schema versions

.github/workflows/pr.yml
=> fix: upgrade docker login action

.ci/oci-dashboard-puppeteer.sh
Trival commit for replacing hardcoding of DashBoard image
=> Replace hardocoded image from the puppeteer script

packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/index.ts
Backport of #718 (remove extra request for namespace provision)
=> Backport: remove extra request for namespace provision

packages/common/src/dto/api/index.ts, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/index.tsx
feat: Support Azure DevOps git provider
https://issues.redhat.com/browse/CRW-3927
N/A
N/A
=> feat: Support Azure DevOps git provider

.github/workflows/next-build-multiarch.yml
Disable the cache to fix the build
=> fix: disable cache for image

build/dockerfiles/brew.Dockerfile
Adds brew.Dockerfile to Che-Dashboard so it is consistent between upstream and midstream, and has a consistent folder structure with other repos.
https://issues.redhat.com/browse/CRW-4043
=> chore: CRW-4043 Add brew.Dockerfile to upstream.

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Upgrade the '@eclipse-che/devfile-converter' lib to version '0.0.1-ff55f9a'.
fixes https://issues.redhat.com/browse/CRW-3440
=> Upgrade devfile-converter

.github/workflows/pr.yml
Set provenance:false for remaining buildx builds
https://github.com/eclipse/che/issues/21954
=> Set provenance:false for remaining buildx builds

package.json
Upgrade the sha256 code of  ```quay.io/che-incubator/dash-licenses```.
=> fix: upgrade dash-licenses version

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Resources/prepareResources.ts
Update DevWorkspace contribution name.
=> fix: devWorkspace contribution name

packages/dashboard-frontend/src/services/helpers/__tests__/location.spec.ts, packages/dashboard-frontend/src/services/helpers/location.ts
Fix the sanitizeLocation method for encoded values.
fixes https://github.com/eclipse/che/issues/21655
=> Fix the sanitizeLocation method for encoded values

packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts
feat: Set the namespace in generated kubeconfig
https://github.com/eclipse/che/issues/22083
1. Deploy Eclipse Che `chectl server:deploy -p openshift`
2. Use custom dashboard image: `oc patch checluster/eclipse-che --patch '{"spec": {"components": {"dashboard": {"deployment": {"containers": [{"image": "quay.io/abazko/che-dashboard:22083"}]}}}}}' --type=merge -n eclipse-che`
3. Star a new workspace
4. Check the kubeconfig in the terminal
```
cat ~/.kube/config
{
"apiVersion": "v1",
"kind": "Config",
"clusters": [
{
"name": "inCluster",
"cluster": {
"server": "https://172.30.0.1:443",
"certificate-authority": "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
"insecure-skip-tls-verify": false
}
}
],
"users": [
{
"name": "developer",
"user": {
"token": "<redacted>"
}
}
],
"contexts": [
{ …
```
=> feat: Set the namespace in generated kubeconfig

packages/dashboard-frontend/src/components/DevfileEditor/index.tsx
https://github.com/eclipse/che/issues/22115
=> fix: make Devfile editor readonly

packages/dashboard-frontend/src/components/DevfileEditor/index.tsx
https://github.com/eclipse/che/issues/22115
=> fix: Make Devfile on User Dashboard uneditable

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/src/components/DevfileEditor/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/DevfileEditorTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR includes code refactoring and fixes the next small bugs: 
1. removed unused "Save" and "Cancel" buttons (devworkspace details page)
2. fixed default value for the storage type widget
3. fixed the wrong ```schemaVersion``` in the  **devfile editor** after creation a new **devWorkspace**(```devfile.schemaVersion``` '2.1.0' or '2.0.0')
It needs for https://issues.redhat.com/browse/CRW-3864
=> fix: small fixes

packages/dashboard-frontend/src/services/dashboard-backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR fixes the route for podmanLogin API.
https://github.com/eclipse/che/issues/22140
=> Fix the route for podmanLogin API

packages/common/package.json, packages/common/src/dto/api/index.ts, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/getProjectFromUrl.ts, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/services/devfileApi/devfile/index.ts, packages/dashboard-frontend/src/services/devfileApi/devfile/metadata.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV2.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts, yarn.lock
Upgrade '@devfile/api' version.
=> fix: upgrade @devfile/api version

packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Change the sequence of injections
https://github.com/eclipse/che/issues/22140
1. Deploy
2. Create and open a new workspace
3. Execute ```podman pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest --tls-verify=false```
=> fix: change the sequence of injections

run/build-and-patch.sh
This PR fixed the ``` run/build-and-patch.sh ``` script.
=> fix: build_and_patch script

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Prevent creating a workspace if we have some errors in the components.
=> fix: create devworkspace flow

packages/dashboard-frontend/src/Layout/Navigation/RecentItemWorkspaceActions.tsx, packages/dashboard-frontend/src/Layout/Navigation/__tests__/__snapshots__/RecentItem.spec.tsx.snap, packages/dashboard-frontend/src/contexts/WorkspaceActions/Provider.tsx, packages/dashboard-frontend/src/services/helpers/types.ts
See https://github.com/eclipse/che/issues/22222#issuecomment-1554540060
=> fix: Changing 'Edit Workspace' to 'Workspace Details'

devfile.yaml
=> chore: adding more RAM / CPU to the devfile

.vscode/extensions.json
=> Adding Import Cost Pack

.deps/EXCLUDED/prod.md, .github/workflows/pr.yml, package.json
Change node version.
fixes https://github.com/eclipse/che/issues/22226
=> feat: change node version

lerna.json
chore: remove useWorkspaces:true as `lerna ERR! ECONFIGWORKSPACES The useWorkspaces option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration.`
if this doesn't work, we will need to `manually provide a list of package globs to be used instead via the packages option in lerna.json`
Change-Id: I647f2828c3a333865a37ea5273a051cdee92da9c
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: remove useWorkspaces:true from lerna.json

packages/dashboard-backend/package.json, yarn.lock
Bump version of devworkspace generator tool to pick up changes made by https://github.com/eclipse-che/che-devfile-registry/pull/755
https://github.com/eclipse/che/issues/22155
- Create any workspace (using factory link)
- Workspace should start as usual and editor should be opened 
N/A
N/A
=> chore: upgrade version of devworkspace generator tool

packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/__tests__/helpers.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/helpers.ts
This PR fixed the access token filter.
fixes https://github.com/eclipse/che/issues/22343
=> fix: access token filter

packages/dashboard-frontend/src/containers/WorkspacesList.tsx
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/879
=> [cherry-pick] fix: avoid workspaces page blinking

.deps/dev.md, .deps/prod.md, README.md, devfile.yaml, package.json, scripts/container_tool.sh, yarn.lock
This PR includes several fixes:
- upgrade 'word-wrap' from 1.2.3 to 1.2.4
- upgrade  'semver' from 5.7.1 to 5.7.2
- upgrade node requirement from '16' to '16.14'
- fix devfile commands
includes changes from https://github.com/eclipse-che/che-dashboard/pull/860 and https://github.com/eclipse-che/che-dashboard/pull/868
=> Upgrade node version

packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/StepTitle/index.module.css, packages/dashboard-frontend/src/components/WorkspaceProgress/Wizard/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/WorkspaceProgress/Wizard/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/Wizard/index.module.css, packages/dashboard-frontend/src/components/WorkspaceProgress/Wizard/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/WorkspaceProgress/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/878 and https://github.com/eclipse-che/che-dashboard/pull/884
=> [cherry-pick] Fix duplicating requests

build/dockerfiles/brew.Dockerfile
=> [cherry-pick] Update brew.Dockerfile

packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV2.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts, run/prepare-local-run.sh
Cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/898
=> fix: support devfiles without metadata

make-release.sh
merge only after https://github.com/eclipse-che/che-devfile-registry/pull/751 is merged
https://github.com/eclipse/che/issues/22279
=> feat: enable new devworkspace generator release

packages/dashboard-frontend/src/components/EditorTools/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/EditorTools/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorTools/index.module.css, packages/dashboard-frontend/src/components/EditorTools/index.tsx, packages/dashboard-frontend/src/contexts/ToggleBars/__mocks__/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/DevfileEditorTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/DevworkspaceEditorTab/index.tsx, packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, run/local-run.sh
https://github.com/eclipse-che/che-dashboard/assets/16220722/9c60aa3d-c92f-4202-a340-c996a53e615d
fixes https://github.com/eclipse/che/issues/22422
=> Navigate to cluster console DevWorkspace object

.github/workflows/next-build-multiarch.yml, .github/workflows/pr.yml, .github/workflows/release.yml
chore: since we don't have all the che images for ppc64le, no point building just the dashboard
Change-Id: I66e4a8d8dcc07f96fdedbdfb8f686f4af753b84e
N/A
N/A (or see commit message above for issue number)
N/A
=> chore: since we don't have all the che images for ppc64le, no point building just the dashboard

packages/dashboard-backend/package.json
Fix 7.74.x feature branch by using proper floating tag for dwo generator dependency
=> fix: fix dwo generator dependency

packages/dashboard-frontend/src/Layout/Header/Tools/AboutMenu/Modal.tsx, packages/dashboard-frontend/src/Layout/Header/Tools/AboutMenu/index.tsx, packages/dashboard-frontend/src/Layout/Header/Tools/index.tsx, yarn.lock
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/916
=> fix: logo for the About modal window

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/serverConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts
Fix relative links for samples.
fixes https://github.com/eclipse/che/issues/22515
1. Deploy Eclipse CHE.
2. Open `Create Workspace`.
3. Create a new workspace from the samples from [che-devfile-registry](https://github.com/eclipse-che/che-devfile-registry) with IntelliJ IDEA.
=> Fix relative links

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/serverConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts
Cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/923
=> fix: relative links

devfile.yaml
=> fix: devfile commands

.deps/prod.md, packages/dashboard-frontend/src/components/InputGroupExtended/index.module.css, packages/dashboard-frontend/src/services/registry/__tests__/devfiles.spec.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/index.spec.ts
Fix registry index URL.
fixes https://github.com/eclipse/che/issues/22454
=> fix: registry index URL

README.md
Update README.md - fix broken status link for CI build
Open README.md  in a browser or other markdown renderer. 
Note this now non-broken badge:
[![Next](https://github.com/eclipse-che/che-dashboard//workflows/Next%20container%20image/badge.svg)](https://github.com/eclipse-che/che-dashboard/actions/workflows/next-build-multiarch.yml)
=> Update README.md - fix broken status link for CI build

.github/workflows/next-build-multiarch.yml, .github/workflows/release.yml, make-release.sh
chore: minor tweaks to be consistent w/ new configbump build
Change-Id: If5170c7d93625ef37d49a108ccce6192eced1550
N/A
https://github.com/eclipse/che/issues/21988
N/A
=> chore: minor tweaks to be consistent w/ new configbump build

package.json, run/patch.sh
Fix patch script
Fix patch script.
=> fix: patch script

packages/dashboard-frontend/src/services/backend-client/__tests__/axiosWrapper.spec.ts, packages/dashboard-frontend/src/services/backend-client/__tests__/kubernetesNamespaceApi.spec.tsx, packages/dashboard-frontend/src/services/backend-client/axiosWrapper.ts, packages/dashboard-frontend/src/services/backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/services/backend-client/devWorkspaceTemplateApi.ts, packages/dashboard-frontend/src/services/backend-client/eventsApi.ts, packages/dashboard-frontend/src/services/backend-client/gitConfigApi.ts, packages/dashboard-frontend/src/services/backend-client/kubernetesNamespaceApi.ts, packages/dashboard-frontend/src/services/backend-client/personalAccessTokenApi.ts, packages/dashboard-frontend/src/services/backend-client/podsApi.ts, packages/dashboard-frontend/src/services/backend-client/userProfileApi.ts
fix: Retry request when token is missed. Part 2.
https://github.com/eclipse/che/issues/22353
N/A
N/A
N/A
=> fix: Retry request when token is missed. Part 2.

packages/dashboard-frontend/src/store/SanityCheck/index.ts
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/961
=> [cherry-pick] fix: namespace provision

packages/dashboard-backend/src/routes/__tests__/factoryAcceptanceRedirect.spec.ts, packages/dashboard-backend/src/routes/factoryAcceptanceRedirect.ts
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/973
=> [cherry-pick] fix: workspace URL parameters after the the OAuth authorization

packages/dashboard-backend/package.json, packages/dashboard-backend/src/localRun/hooks/authorizationHooks.ts, packages/dashboard-backend/src/localRun/routes/dexCallback.ts, packages/dashboard-backend/src/localRun/routes/signOut.ts, yarn.lock
Fix local run for minikube.
fixes https://github.com/eclipse/che/issues/22650
=> fix: local run for minikube

packages/dashboard-backend/package.json, packages/dashboard-backend/src/localRun/hooks/authorizationHooks.ts, packages/dashboard-backend/src/localRun/routes/dexCallback.ts, packages/dashboard-backend/src/localRun/routes/signOut.ts, yarn.lock
This fix restores the ability to use the local development flow against a minikube cluster.
This PR is an alternative to https://github.com/eclipse-che/che-dashboard/pull/974.
=> fix: local development flow against a minikube cluster

.github/workflows/pr.yml
This pull request extends the PR check comment to provide the `kubectl patch` command. This command can be used then in the `Is it tested? How?` section in the PR description.
=> feat: provide kubectl patch command on PR check

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/serverConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-frontend/src/services/bootstrap/__tests__/index.spec.tsx
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1009
=> [cherry-pick] fix: getting pluginRegistry

packages/common/src/dto/cluster-config.ts, packages/dashboard-backend/src/routes/api/__tests__/clusterConfig.spec.ts, packages/dashboard-backend/src/routes/api/clusterConfig.ts, packages/dashboard-frontend/index.html, packages/dashboard-frontend/src/services/bootstrap/index.ts
feat: Allow to adjust favicon
https://github.com/eclipse/che/issues/22675
<details>
<summary>CheCluser CR</summary>
```xml
spec:
components:
dashboard:
branding:  
logo:
base64data: iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAgAElEQVR4nO2dB5heRfXGTzbZtE3Z3fTNJrvpbbOppBGS0Hsv0ptUEUG6SJPeEQVRFKRKld5BQu+9995BEUFQ1P/9z/vNBpbw7e5X5szc8v6e531AE3bnzJ07M3fmFBFCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBBCCCGEEEIIIYQQQgghhBDihy5GNS0aYjSyRZONZiyl8a3+vH/Lf1Ptv8mEEEIIqTQaKnbBXmS0gdGORj8zOtHobKOrje42es7oA6NPjSIF/cfob0bvGD1pdLvR5Ua/NTrKaG+jbY3WNlpW7IZigOsOIYQQQt …
```
=> feat: Allow to adjust favicon

packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/ClusterConfig/selectors.ts, packages/dashboard-frontend/static/loader.html
fix: Use selector to update dashboard favicon
https://github.com/eclipse/che/issues/22675
N/A
N/A
=> fix: Use selector to update dashboard favicon

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-backend/.eslintrc.js, packages/dashboard-backend/package.json, packages/dashboard-frontend/.eslintrc.js, packages/dashboard-frontend/package.json, packages/dashboard-frontend/webpack.config.common.js, yarn.lock
Clean up some unnecessary dependencies.
=> chore: clean up dependencies

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/index.tsx
Fix creating a new workspace from the sample flow.
fixes https://github.com/eclipse/che/issues/22789
https://github.com/eclipse-che/che-dashboard/assets/6310786/5a58fe7f-801b-42ab-b61f-8f7a0b027b94
=> Fix create a new workspace from the sample flow

.deps/dev.md, .deps/prod.md, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/updateEditor.spec.ts
Improve Git+SSH factory loading flow
fixes https://github.com/eclipse/che/issues/22773
3. Open the **Chrome Menu** and select **More Tools** > **Developer Tools**.
Select **Network** > **XHR and Fetch** and paste ```resolver``` into the filter.
4. Create a new workspace with the custom editor from the next link
```bash
{CHE-server}#git@github.com:eclipse-che/che-dashboard.git
```
5. We should not have requests to ```{CHE-server}/api/factory/resolver```.
Git+SSH
https://youtu.be/hK8NGDsv0R0
HTTPS
https://youtu.be/Vs7rhqhWN1Q
=> fix: Git+SSH factory loading flow

packages/dashboard-backend/src/routes/api/dataResolver.ts, packages/dashboard-backend/src/routes/api/devworkspaceResources.ts, packages/dashboard-backend/src/routes/api/helpers/getCertificateAuthority.ts
Fix data resolver. Apply two tries for data requests.
fixes https://github.com/eclipse/che/issues/22814
=> Fix data resolver

.deps/dev.md, .deps/prod.md, package.json, yarn.lock
=> chore: bump dependencies

build/dockerfiles/Dockerfile, build/dockerfiles/skaffold.Dockerfile
Change base image `node:18.16.1-alpine3.18` -> `node:18.19.1-alpine3.19`
=> chore: update dockerfile

devfile.yaml
Update the tools container image in the devfile.yaml with the latest universal developer image.
=> Update the tools container image

packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV1.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV1.ts
This PR fixed the normalizeDevfileV1 method.
fixes https://github.com/eclipse/che/issues/22758
1. Open the Create Workspace page.
2. Paste an unexisted URL ```https://github.com/olexii4/che-editor-theiahkhjkhkjhkjhjhghjhgfghfhgfhgjfghfghjfghjfhgfghfghjfhgfghfhgjfhgjfhg```.
3. Press 'Create & Open'.
4. A new workspace should be created with a name shorter than 63 characters.
=> fix: normalizeDevfileV1 method

.github/workflows/release.yml, make-release.sh
yarn lock must be regenerated during release, so that new dependencies with release versions are included in it.
Also, make the build stage of setting release version of dependencies first, so that images will be built with those dependencies
https://github.com/eclipse/che/issues/22842
=> fix: fix release causing dependency inconsistency

.github/workflows/codecov.yml, .github/workflows/next-build-multiarch.yml, .github/workflows/pr.yml, .github/workflows/release.yml
Update actions to use Node.js 20.
https://github.com/eclipse-che/che-dashboard/actions/runs/8231263984
=> chore: update actions to use Node.js 20

.deps/dev.md, .deps/prod.md, packages/dashboard-backend/package.json, yarn.lock
Removing the [`request`](https://www.npmjs.com/package/request) package as it is deprecated.
fix https://github.com/eclipse/che/issues/22844
=> fix: remove deprecated package

.deps/prod.md, yarn.lock
Bump some vulnerable dependencies.
=> Bump dependencies

packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/__tests__/helpers.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/helpers.ts, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/index.tsx
This PR adds sanitization for the git provider endpoint URL on the adding/updating personal access tokens dialog window.
fixes https://github.com/eclipse/che/issues/22851
=> Sanitize the git provider endpoint

packages/dashboard-frontend/src/pages/GetStarted/ImportFromGit/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/ImportFromGit/index.tsx
=> fix: more explicit error message when SSH keys not found

packages/dashboard-frontend/src/pages/GetStarted/ImportFromGit/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/ImportFromGit/index.tsx
Trim spaces in the input value.
fixes https://github.com/eclipse/che/issues/22805
=> fix: trim spaces in the input value

scripts/container_tool.sh
This PR changes Podman's priority for the container_tools script.  It allows users to use Podman as default if both tools are installed and running.
=> Changes Podman's priority for the container_tools script

packages/dashboard-frontend/src/pages/GetStarted/SamplesList/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/SamplesList/index.tsx
This PR fixes the bug that prevents applying pre-built resources from the devfile registry pod.
It is related to https://issues.redhat.com/browse/CRW-6228
=> Apply DevWorkspace resources

packages/dashboard-frontend/src/pages/GetStarted/SamplesList/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/SamplesList/index.tsx
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1091
=> fix: apply devworkspaces (#1091)

packages/dashboard-frontend/jest.config.js
Fix the frontend coverage threshold to pass the Codecov PR check.
=> fix: frontend coverage threshold

.ci/openshift-ci/Dockerfile
Fix URL where E2E tests is downloading chectl install script from.
https://github.com/eclipse-che/che/issues/22925
=> Download chectl install script from che-incubator.github.io in tests

packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/eventApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/podApi.ts
Destroy request in case of error
https://issues.redhat.com/browse/CRW-6292
N/A
N/A
N/A
=> fix: destroy request in case of error

packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/StatusIcon/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/const.ts
This reverts commit 5ee747a6aa101f3c910fd3b4cf9c8ccb2c20b2c2.
=> Revert "Align the oauth items filter with changes from server"

.deps/prod.md, packages/dashboard-frontend/src/services/factory-location-adapter/__tests__/factoryLocationAdapter.spec.ts, packages/dashboard-frontend/src/services/factory-location-adapter/index.ts, yarn.lock
This PR fixes the regular expression for SSH URLs.
fixes https://issues.redhat.com/browse/CRW-6566
=> fix: the regular expression for SSH URLs

.github/PULL_REQUEST_TEMPLATE.md
Add `Screenshot/screencast of this PR` section into the PR's template
=> chore: update PR's template

devfile.yaml, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/GitRepoOptions/AdditionalGitRemotes/__tests__/gitRemote.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/helpers.ts
Fix typos.
N/A
fixes https://github.com/eclipse-che/che/issues/23072
=> fix: typos

packages/dashboard-frontend/src/components/TextFileUpload/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/TextFileUpload/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/index.tsx
Cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1168
=> cherry-pick of fix: check if ssh key has newline at the end

.deps/dev.md, .deps/prod.md, package.json, packages/dashboard-frontend/webpack.config.common.js, yarn.lock
This PR upgrades the next libs:
- axios@1.7.1 -> axios@1.7.5
- webpack@5.91.0 -> webpack@5.94.0
fixes https://issues.redhat.com/browse/CRW-6928
=> fix: upgrade axios

build/dockerfiles/skaffold.Dockerfile, packages/dashboard-frontend/src/components/ImportFromGit/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/UntrustedSourceModal/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/UntrustedSourceModal/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Resources/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx, packages/dashboard-frontend/src/pages/Loader/index.tsx, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/selectors.ts
Cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1172
=> Do not show modal for trusted repositories (#1172)

packages/dashboard-frontend/src/components/UntrustedSourceModal/index.tsx
This PR fixes the following problems (see [comment](https://github.com/eclipse-che/che-dashboard/pull/1180#issuecomment-2321451825)):
- "Create & Open" button didn't work second time when leave git repo URL unchanged
- "Untrusted author" warning appeared unexpectedly at the Create Workspace page when start modifying URL
Watch [the screencast](https://github.com/eclipse-che/che-dashboard/pull/1180#issuecomment-2321451825) for steps to reproduce.
=> fix: untrusted modal

packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/store/Plugins/chePlugins/__tests__/helpers.convertToEditorPlugin.spec.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/helpers.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/index.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1205 and https://github.com/eclipse-che/che-dashboard/pull/1207 to the 7.92.x branch
=> [cherry-pick]  fix: hasTechPreviewTag filter and fix: Unexpected error message No IDE URL

packages/dashboard-frontend/src/components/UntrustedSourceModal/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx, packages/dashboard-frontend/src/store/Workspaces/Preferences/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/Workspaces/Preferences/helpers.ts, packages/dashboard-frontend/src/store/Workspaces/Preferences/selectors.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1210
=> fix: factory URL flow with untrusted repository

packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/WorkspaceConditions/index.tsx
=> Update index.tsx ( 'Downloading IDE binaries... (it can take a few minutes)')

packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/WorkspaceConditions/index.tsx
=> Update index.tsx (drop 'connection')

.deps/EXCLUDED/prod.md, packages/dashboard-frontend/jest.setup.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.module.css, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/index.tsx, scripts/yarn/old_version/.deps/EXCLUDED/prod.md
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1246 to the 7.92.x branch
=> [cherry-pick] fix: editor selector cards

.deps/dev.md, .deps/prod.md, package.json, packages/dashboard-backend/package.json, packages/dashboard-frontend/package.json, scripts/yarn/old_version/.deps/dev.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
=> Upgrade dependencies

packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx
This PR fixes the Git Services page with the list of the available Git providers.
fixes https://github.com/eclipse-che/che/issues/23262
See `Steps to reproduce` at https://github.com/eclipse-che/che/issues/23262
=> fix: git services page

packages/dashboard-backend/src/routes/api/kubeConfig.ts
=> Update kubeConfig.ts - fix typo cube -> Kube

.deps/prod.md, package.json, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
This PR pins the version of the nanoid package.
=> chore: pin nanoid

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx
This PR fixes the ability to create workspaces using SSH URLs.
fixes https://github.com/eclipse-che/che/issues/23294
See steps to reproduce https://github.com/eclipse-che/che/issues/23294
=> Fix factory flow with SSH URL

packages/dashboard-backend/jest.config.js, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspaceApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspaceClusterApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspaceTemplateApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceClusterApiService.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceTemplateApi.ts, packages/dashboard-backend/webpack.config.common.js
cherry-pick from https://github.com/eclipse-che/che-dashboard/pull/1280
=> fix: import constants from @devfile/api (#1280)

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/devWorkspaceSpecTemplates.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/editorDefinitions.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/getEditor.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/const.ts, packages/dashboard-frontend/src/store/DevfileRegistries/getEditor.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1310 to 7.98.x branch
=> [cherry-pick] Fix editor update flow

packages/dashboard-frontend/src/services/axios-wrapper/getAxiosInstance.ts
cherry-picking https://github.com/eclipse-che/che-dashboard/pull/1319 for 3.19
=> fix: axios instance timeout

packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/selectors.ts
This PR provides url  parameter filter as url parameter  for samples.
fixes https://github.com/eclipse-che/che/issues/23269
=> fix: add URL filter for samples

package.json, packages/dashboard-frontend/src/__tests__/const.ts, packages/dashboard-frontend/src/__tests__/workspaceCreationTimeCheck.check.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/DeleteWarning/__tests__/index.spec.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/DeleteWarning/index.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/Provider.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/contexts/WorkspaceActions/helpers.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/helper.isDevfileRegistryLocation.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/__tests__/createWorkspaceFromResources.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/createWorkspaceFromResources.ts
Fix delete workspace flow.
fix https://github.com/eclipse-che/che/issues/23337
=> fix: delete workspace flow

build/dockerfiles/Dockerfile, build/dockerfiles/brew.Dockerfile, build/dockerfiles/rhel.Dockerfile
This PR fixes entrypoint errors.
Before:
After:
a2-4045-a4c8-015fbb0bf167" />
fixes https://github.com/eclipse-che/che/issues/23460
1.  Deploy Eclipse-Che.
2. Open the dashboard logs.
3. The Dashboard server should start without any errors.
=> fix: entrypoint errors

README.md
=> fix: Update badges in README.md

README.md, yarn.lock
Update brace-expansion from 1.1.11 to 1.1.12.
=> Update brace-expansion from 1.1.11 to 1.1.12

packages/dashboard-frontend/src/pages/GetStarted/SamplesList/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/SamplesList/index.tsx
This PR fixed `handleSampleCardClick` method by encoding parameters of target request.
fix https://issues.redhat.com/browse/CRW-9473
1. Install Dev Spaces with dashboard-image includes current changes. As an alternative solution, it will be enough to simply deploy Eclipse-Che and apply these two patches:
```sh
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/dashboard/deployment", "value": {containers: [{image: "docker.io/olexii4dockerid/che-dashboard:CRW9473", name: che-dashboard}]}}]"
```
```sh
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/devfileRegistry/disableInternalRegistry", "value": "false"}]"
```
2. Open User Dashboard and create workspace from …
=> fix: handleSampleCardClick method
