src/app/get-started/get-started.controller.ts, src/app/get-started/sample-card/sample-card.html, src/app/get-started/sample-card/sample-card.styl, src/app/stacks/list-stacks/list-stacks.controller.ts, src/app/stacks/list-stacks/list-stacks.styl, src/app/stacks/stacks-config.ts, src/app/workspaces/create-workspace/ready-to-go-stacks/devfile-selector/devfile-selector.controller.ts, src/app/workspaces/create-workspace/ready-to-go-stacks/devfile-selector/devfile-selector.html, src/app/workspaces/create-workspace/ready-to-go-stacks/devfile-selector/devfile-selector.styl, src/components/api/devfile-registry.factory.ts, src/components/service/registry-checking.service.ts
This PR allows multiple devfile registries to be specified as a space separated list, for example in values.yml we can have:
```yaml
che: 
workspace: 
devfileRegistryUrl: "https://che-devfile-registry.openshift.io/ https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/"
```
The registry location is then stored so that the devfile can be read from the correct location.
The initial implementation is taken from https://github.com/eclipse/che/pull/16390, https://github.com/eclipse/che/pull/14059
It contains only Dashboard related changes. Che Server and Che Operator changes will be made separately.
Fixes https://github.com/eclipse/che/issues/13961
=> Multiple devfile registries

src/components/api/workspace/che-workspace.factory.ts
This PR fixes bug which happens when refreshing a workspace details page.
fixes https://github.com/eclipse/che/issues/15920
=> Fixed refreshing a workspace details page.

src/assets/branding/product.json
This PR fixes documentation link for installing Che in TLS mode with self-signed certificates
N/A
=> Fixed documentation link for Che in TLS mode

Dockerfile.apache
Fix link in index.html. That will allow load dashboard from `/dashboard` instead of `/`.
Do exactly the same thing 
https://github.com/eclipse/che-dashboard/blob/master/pom.xml#L235-L236
=> Fix link in index.html

src/app/index.module.ts, src/components/service/browser-detect.ts, src/components/service/service-config.ts
This PR adds a service that detects user's browser and warns them if that browser is not supported.
*Screenshot from Safari*
resolves https://github.com/eclipse/che/issues/16840
=> Added detection of unsupported browser.

src/components/service/browser-detect.ts
This PR slightly changes the wording of message for unsupported browsers, so now user will see: 
**«You're using a web browser we don't support. Consider using Chrome or Firefox instead.»**
=> Fix wording of warning for unsupported browser.

README.md, src/app/navbar/navbar.controller.ts, src/app/navbar/navbar.html, src/app/organizations/organizations-config.service.spec.ts, src/app/teams/navbar-teams/navbar-teams.controller.ts, src/app/teams/teams-config.ts, src/app/workspaces/list-workspaces/list-workspaces.controller.ts, src/app/workspaces/workspace-details/workspace-details.service.ts, src/components/api/che-team.factory.ts, src/components/branding/branding.constant.ts, src/components/branding/che-dashboard-configuration.service.ts
This PR hides `organizations` and `teams` UI on dashboard and prevents fetching organizations on dashboard start.
https://github.com/eclipse/che/issues/16973
=> Hide organizations UI on dashboard

src/app/get-started/custom-workspace-tab/workspace-name-row/workspace-name-row.controller.ts, src/components/che-pf-widget/text-input/che-pf-text-input.directive.ts, src/components/che-pf-widget/text-input/che-pf-text-input.html
- updates validation message when workspace name doesn't match provided pattern;
- adds validations for min and max length of workspace name;
- trigger validation after changing workspace name in devfile editor.
<details>
<summary>Animated demo</summary>
</details>
https://github.com/eclipse/che/issues/16303
=> Fix workspace name validation on Custom Workspace page

src/components/service/global-warning-banner.service.ts, src/components/typings/che.d.ts, src/components/widget/description/che-description.html, src/components/widget/global-warning-banner/global-warning-banner.styl, src/components/widget/global-warning-banner/global-warning-message.directive.ts, src/components/widget/global-warning-banner/global-warning-message.html, src/components/widget/global-warning-banner/global-warning-message.styl, src/components/widget/widget-config.ts, src/index.html
This PR adds ability to hide any warning banner for current session.
resolves https://github.com/eclipse/che/issues/16978
=> Allows to close a warning banner for current session.

src/app/stacks/stack-details/stack.styl
Fix stack-editor styles.
before
with these changes
=> Fix stack-editor styles

Dockerfile, apache.Dockerfile
Signed-off-by: Bivas Das <bivasda1@in.ibm.com>
Installation of phantomjs-prebuilt fails as phantomjs binary for ppc64le is not available at the provided CDN URLs. Also, we tried installing phantomjs using apt-get install phantomjs but phantomjs crashes while executing yarn test. So currently skipping yarn test for ppc64le.
This PR is part of [this](https://github.com/eclipse/che/issues/16655) initiative and also fixes phantomjs failure for ppc64le.
=> Fix PhantomJS failure for ppc64le

src/components/api/devfile-registry.factory.ts
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>
In case of single host the devfile registry url looks like `https://domain/devfile-registry`
Using `URL` leads to image href `https://domain/images/someimage.svg` but not to `https://domain/devfile-registry/images/someimage.svg`
https://github.com/eclipse/che/issues/14564
N/A
N/A
=> Fix updating devfile icons in case of single host

.github/workflows/ci.yaml
Signed-off-by: Prabhav Thali <Prabhav.Thali1@ibm.com>
Increases timeout_minutes from 20 to 40 as build fails on `yarn build` for s390x.
Timeout is increased to 40 mins as `yarn build` takes approximately 34-35 mins for s390x in github actions. 
Fixes the build failure in https://github.com/eclipse/che-dashboard/runs/893425657?check_suite_focus=true
=> Fix build in Github Actions

src/app/get-started/custom-workspace-tab/custom-workspace-tab.controller.ts, src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.controller.ts
- storage type selector gets initialized with a preferred storage type
- changing storage type attributes in the devfile editor makes storage type selector properly update its value
=> Fix storage type selector update and initialization on Custom Workspace tab

src/app/get-started/get-started-tab/toolbar/get-started-toolbar.controller.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.html, src/assets/branding/product.json, src/components/branding/branding.constant.ts, src/components/service/storage-type.service.ts
This PR add links to the documentation page about storage types wherever storage type switcher or selector is used within the UD.
<details>
<summary>Screenshots</summary>
</details>
resolves https://github.com/eclipse/che/issues/17498
=> Add documentation link for storage types

src/app/get-started/custom-workspace-tab/custom-workspace-tab.controller.ts, src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.component.ts, src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.controller.ts, src/app/get-started/get-started-tab/get-started-tab.controller.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.component.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.controller.ts, src/app/index.module.ts, src/app/workspaces/workspace-details/workspace-overview/workspace-details-overview.controller.ts, src/components/service/service-config.ts, src/components/service/storage-type/storage-type.service.ts, src/components/service/storage-type/storage-type.styl
Inline CSS rules get removed from the template when modal box is shown. This PR extracts them into a stylus module to avoid losing correct styles.
**Before**
**After**
=> Extracted inline styles from template into stylus module

src/app/workspaces/list-workspaces/list-workspaces.html
Shows 'Delete' button on "Workspaces" page if workspaces are available.
It is hidden until checkbox is checked.  Che beginners can't figure out they can remove their workspaces.
After applied this PR, "Delete" button is shown and disbabled if workspaces are available.
"Delete" button is enabled if checkboxes are checked.
"Delete" button is hidden if there is no workspace. (This behavior is same as the search box.) 
None.
=> Show delete button on the workspace list

src/app/factories/load-factory/load-factory.controller.ts, src/app/factories/load-factory/load-factory.service.ts
The UD now handles the error happened during the factory acceptance and displays it on the factory loader screen.
fixes https://github.com/eclipse/che/issues/17502
=> Show errors happened during factory acceptance

src/assets/branding/product.json
Fixes the link on the certificate error page, which was broken by https://github.com/eclipse/che-docs/pull/1451:
**Note: this PR depends on https://github.com/eclipse/che-docs/pull/1493**
Fixes https://github.com/eclipse/che/issues/17712
https://github.com/eclipse/che-docs/pull/1493
=> Fix link to self-signed certs documentation in cert error page

src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.controller.ts, src/app/get-started/custom-workspace-tab/storage-type-row/storage-type-row.html, src/app/get-started/get-started-tab/get-started-tab.controller.ts, src/app/get-started/get-started-tab/get-started-tab.html, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.component.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.controller.ts, src/app/get-started/get-started-tab/toolbar/get-started-toolbar.html, src/components/che-pf-widget/switch/che-pf-switch.directive.ts, src/components/che-pf-widget/switch/che-pf-switch.html, src/components/service/storage-type/storage-type.service.ts
PatternFly switch component:
- added attribute to disable the component
Storage Type switch on Get Started tab:
- correctly initialize the toggle with the default storage type
- disable the toggle in case when the only storage type is available
Storage Type select on Custom Workspace tab:
- correctly initialize storage type select with the default storage type value
- disable the select in case when the only storage type is available
- fixes updating the devfile editor on selecting the storage type
fixes https://github.com/eclipse/che/issues/17725
=> Storage type improvements

.github/workflows/pr.yaml
This PR updates the GitHub workflow action triggered on pull request. This action now builds two docker images for `che-dashboard` and `che-server` and pushes them to `docker.io/maxura` organization. After the successful build the GH bot leaves a comment with `che-server` image name that can be used for testing.
`docker.io/maxura/{PRODUCT}>:che-dashboard-pull-{PULL_NUMBER}`
e.g. for this particular pull request two images are built:
`docker.io/maxura/che-dashboard>:che-dashboard-pull-85`
`docker.io/maxura/che-server>:che-dashboard-pull-85`
=> update pull request action

src/components/widget/devfile-editor/devfile-editor.controller.ts
This PR makes the devfile editor to use literal style for all block scalars while displaying yaml files.
resolves https://github.com/eclipse/che/issues/15999
=> Block scalar literal style in the devfile editor

src/app/index.module.ts, src/app/keycloak-setup.ts
Makes dashboard don't fail if api/keycloak/settings is not found
It fixes https://github.com/eclipse/che/issues/18095
I've tested multiuser and single-user run on minikube with deployed Helm chart
=> Do not fail in Single-User Mode is keycloak is not found

src/app/ide/ide.service.ts
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>
Allows the embedded IDEs to go into a fullscreen mode by specifying a corresponding feature policy for the nested ide iframe.
`fullscreen` feature policy allows the nested context to use the browser's Clipboard API.
fixes https://github.com/eclipse/che/issues/18330
=> Dashboard should allow IDEs going to fullscreen mode

.github/workflows/release.yml
Authenticate to docker.io to prevent failing the build on Centos CI due to pull limits
* https://github.com/eclipse/che/issues/18292
* https://github.com/eclipse/che/issues/18409
=> Add docker login to avoid dockerhub pull limit

src/components/branding/branding.json
Even though "Factories" menu item in left navigation bar is disabled, this PR updates the branding configuration to disable this menu item in downstream projects as well because persistent factories are based on workspace config and currently this feature doesn't work.
However, factory loading flow `/f?url=` still works.
https://issues.redhat.com/browse/CRW-1383
=> Hide "Factories" menu item in sidenav bar

.github/workflows/ci.yaml, .github/workflows/pr.yaml
This PR fixes github workflows by using docker/login-action@v1 instead of shell login.
=> Use docker/login-action@v1 to login to docker registries

src/components/api/che-factory.factory.ts
Makes Dashboard propagate Che Server error on resolving factory failure;
https://github.com/eclipse/che/issues/18164
N/A
N/A
=> Propagate Che Server error on resolving factory failure

.github/workflows/ci.yaml, apache.Dockerfile
For time being, until react based Dashboard is not moved to the master, it's needed to return back `/next` suffix for target directory to make it compatible with Che master branch.
Also, we need to keep building the latest React Based Dashboard, and this PR does it as well. Note that in che-incubator it's already disabled by https://github.com/che-incubator/che-dashboard-next/commit/b1ba50279fbb481963b159e778d4cc3699a3d9f1
N/A
=>  Build next react in the same manner as it used to be

src/services/bootstrap/branding.constant.ts
Remove websocket context from branding.
Its usage is already removed in https://github.com/che-incubator/che-dashboard-next/pull/112/files#diff-8fd62774061c06dca4b4214eb5a933c2338f87f63268c342f8ccee358f3a92e3R125
but that time I forget to remove it from the branding :man_facepalming:  
N/A
=> Remove websocket context from branding

src/Layout/index.tsx, src/components/WebSocketBannerAlert/__tests__/WebSocketBannerAlert.spec.tsx, src/components/WebSocketBannerAlert/index.tsx, src/services/cheWorkspaceClient/index.ts, yarn.lock
This PR adds a new component called WebSocketBannerAlert that is used for showing the banner alert when a WebSocket is failing to connect
Pre-req PRs:
https://github.com/che-incubator/che-dashboard-next/pull/109
https://github.com/eclipse/che-dashboard/pull/127
https://github.com/eclipse/che-workspace-client/pull/50
https://github.com/eclipse/che/issues/18490
Added WebSocket troubleshooting banner that triggers when WebSockets are not available
=> Add banner that triggers when websockets arent available

src/services/cheWorkspaceClient/index.ts, yarn.lock
This PR in conjunction with https://github.com/eclipse/che-workspace-client/pull/51 makes it so that you can refresh a token when a websocket is reconnecting. That way, the token used when establishing the websocket connection is always valid. It also removes websocket context.
Part of https://github.com/eclipse/che/issues/18490#issuecomment-760079244
Fix an issue where tokens aren't refreshed before websockets are reconnected
=> Provide refresh token arg to che workspace client

src/Layout/index.tsx, src/components/BannerAlert/WarningBanner/__tests__/WarningBanner.spec.tsx, src/components/BannerAlert/WarningBanner/index.tsx, src/components/BannerAlert/WebSocketBanner/__tests__/WebSocketBanner.spec.tsx, src/components/BannerAlert/WebSocketBanner/index.tsx, src/components/BannerAlert/index.tsx, src/services/bootstrap/branding.constant.ts
This PR adds an optional warning banner and allows you to show multiple banners at once. I'm not entirely sure if it makes sense to allow the product.json to render the warning text as html as requested, otherwise it could open up the dashboard to an xss attack
https://github.com/eclipse/che/issues/18769
Add in the ability to add warning banner on Che Dashboard
=> Add in ability to add warning banner

license-tool/src/entrypoint.sh, package.json, src/Layout/Navigation/__tests__/RecentList.spec.tsx, src/containers/IdeLoader.tsx, src/containers/__tests__/IdeLoader.spec.tsx, src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, src/pages/GetStarted/GetStartedTab/__tests__/SamplesListToolbar.spec.tsx, src/pages/GetStarted/GetStartedTab/__tests__/TemporaryStorageSwitch.spec.tsx, src/pages/GetStarted/__tests__/GetStarted.spec.tsx, src/pages/IdeLoader/index.tsx, src/services/bootstrap/PreloadData.ts, src/services/keycloak/setup.ts, src/services/storageTypes.ts, src/store/Environment/index.ts, src/store/Environment/selectors.ts, src/store/__mocks__/store.ts, src/store/__mocks__/storeBuilder.ts, src/store/index.ts, webpack.config.common.js, webpack.config.dev.js, yarn.lock
This PR removes redundant loader that hides the IDE iframe while IDE is loading.
https://github.com/eclipse/che/issues/18734
=> Remove redundant loader

license-tool/licenseTool.Dockerfile, license-tool/run.sh, license-tool/src/entrypoint.sh
It makes dash-licenses more stable and sanitize-html/ from https://github.com/eclipse/che-dashboard/pull/152 can be resolved without CQ :tada: 
N/A
=> Upgrade dash-licenses to the latest master

.deps/dev.md, .deps/prod.md, package.json, src/components/BannerAlert/WarningBanner/__tests__/WarningBanner.spec.tsx, src/components/BannerAlert/WarningBanner/index.tsx, yarn.lock
This PR makes it so that anything in the warning message is rendered as html
~~CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23018~~ ended up not being needed
https://github.com/eclipse/che/issues/18769
=> Render warning message as html

src/Layout/ErrorBoundary/__tests__/__snapshots__/index.spec.tsx.snap, src/Layout/ErrorBoundary/__tests__/index.spec.tsx, src/Layout/ErrorBoundary/index.tsx, src/Layout/Header/Tools/index.tsx, src/Layout/index.tsx, src/index.tsx, src/services/keycloak/setup.ts, src/services/storageTypes.ts
Wrapping UD page components with error boundary to handle uncaught exceptions that may happen in runtime in components. 
**Screenshots**
*expanded component stack*
fixes https://github.com/eclipse/che/issues/18758
=> Wrap dashboard pages with error boundary

src/containers/IdeLoader.tsx
Fix search params for the ide-loader tab.
=> fix search params for the ide-loader tab

.github/workflows/ci-multiarch.yaml, .github/workflows/ci.yaml, apache.Dockerfile
The CI workflow that utilized the Docker Build & Push Action to build multiarch image is rather unstable that prevents to propagate latest changes into next tag. Hense, the CI workflow is updated in order to build image for amd64 architecture only. 
Same time the Docker Build & Push Action used in PR workflow to build simultaneously single arch images for four platforms works well. This pull request adds new workflow intended to build a multiarch image using same approach. 
https://github.com/eclipse/che/issues/19049
=> updated github workflows

src/Routes/index.tsx, src/pages/WorkspacesList/__tests__/index.spec.tsx, src/pages/WorkspacesList/index.tsx
This PR fixes bug that causes to show in confirmation window an incorrect number of workspaces to be deleted.
fixes https://github.com/eclipse/che/issues/19057
=> Fix incorrect number of workspaces in confirmation window

src/containers/IdeLoader.tsx, src/containers/WorkspaceDetails.tsx, src/containers/__tests__/IdeLoader.spec.tsx, src/services/bootstrap/PreloadData.ts
This PR provides an additional API request in the case if we cannot find the target workspace in the storage. These additional requests fixed errors with opening workspace details/IDE pages after it's created out of the current tab.
=> Fix opening workspace details/IDE after it's created out of the current tab

src/index.tsx, src/services/bootstrap/PreloadData.ts, src/services/cheWorkspaceClient/index.ts, src/services/keycloak/setup.ts
This PR fixes the issue when API calls use an expired token. It improves the application pre-start set up so the `che-workspace-client` gets initialized in the correct order, after the keycloak adapter setup. That allows `che-workspace-client` to correctly register a request interceptor that does token refreshing.
fixes https://github.com/eclipse/che/issues/19058
=> Fix ability to refresh token on API calls

src/services/cheWorkspaceClient/index.ts
Fix refresh token callback in single-user mode.
Deploy Single User Che with the following CheCluster patch
```yaml
spec:
server:
customCheProperties:
CHE_MULTIUSER: "false"
```
fixes https://github.com/eclipse/che/issues/19038
=> Fix refresh token callback

.deps/EXCLUDED/dev.md, .deps/dev.md, package.json, src/containers/FactoryLoader.tsx, src/containers/__tests__/FactoryLoader.spec.tsx, yarn.lock
Add factory policies support: `perclick`, `peruser`.
Note `peraccount` is not migrated since it does not really make sense after deprecating organizations.
This PR implements a similar algorithm to the previous version of the dashboard.
For example: ```http://che-eclipse-che.192.168.49.2.nip.io/f?url=https://github.com/eclipse/che-dashboard.git&policies.create=peruser```
fixed https://github.com/eclipse/che/issues/18961
=> Add factory policies support

src/services/registry/devfiles.ts
Fix URIs for devfile icon and devfile self-link in single-host mode.
Deploy Single Host Che with the following CheCluster patch
```yaml
spec:
k8s: 
singleHostExposureType: 'gateway'
server:
serverExposureStrategy: single-host
```
fixes https://github.com/eclipse/che/issues/18084
=> Fix URIs for devfile icon and devfile self-link in single-host mode

.github/workflows/release.yml, make-release.sh
Enables docker buildx support in GitHub Actions release job to build and publish multiarch docker image.
This refers to [#17124](https://github.com/eclipse/che/issues/17124).
=> Multiarch build support by docker buildx

src/Layout/Header/Tools/__tests__/about-modal.spec.tsx, src/Layout/Header/Tools/about-modal.tsx
Removes duplicating product name from version title.
It seems to be what Parvathy suggested in https://github.com/eclipse/che/issues/18567#issuecomment-742640132
and it's what Nick suggests in https://issues.redhat.com/browse/CRW-1676
=> Remove duplicating product name from version title

src/containers/IdeLoader.tsx
Fix a bug with restart the target workspace when it is stopping.
resolves https://github.com/eclipse/che/issues/19379
=> Fix a bug with restart the target workspace when it is stopping

src/services/workspace-client/devWorkspaceClient.ts
This PR fixes the devworkspacetemplate ownerReference so that it is set correctly
https://github.com/eclipse/che/issues/19328
=> Fix apiVersion in ownerReference so that devworkspacetemplates cleaned up

src/Layout/Navigation/MainList.tsx, src/Layout/Navigation/__tests__/MainList.spec.tsx
This PR removes Page word from Get Started title, it's what was recommended initially
Related PR that changes e2e tests https://github.com/eclipse/che/pull/19433
Fixes https://github.com/eclipse/che/issues/19412
=> Fix Get Started page title

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json, src/services/helpers/devworkspace.ts, src/services/workspace-client/devWorkspaceClient.ts, yarn.lock
This PR finalized workspace to devworkspace renaming.
In addition, it also adapts to newer DevWorkspace Client where Che API is introduced + client is initialized in a different way.
It's done in the scope of https://github.com/devfile/devworkspace-operator/issues/321.
It depends on https://github.com/che-incubator/devworkspace-client/pull/19
:warning: After ^ is merged, dependencies should be updated and it should fix PR checks.
=> Finalize workspace to devworkspace renaming

src/services/helpers/types.ts, src/services/workspace-client/devWorkspaceClient.ts
This PR makes it so that a devworkspace will error when a devworkspace is stuck on `'Waiting for workspace routing objects'`. This is because when the devworkspace che controller isn't installed the devworkspace-controller loops and never get's past the starting state. It's not ideal to depend on the exact message from the devworkspace controller but I don't really see any other way.
To test:
```
echo "spec:
devWorkspace:
enable: true" > devworkspace-config.yaml
chectl server:deploy --installer=operator --platform=openshift --che-operator-cr-patch-yaml=devworkspace-config.yaml
```
then scale down both deployments in the devworkspace-che namespace and then create a devworkspace with:
``` …
```
=> Enhance error handling for when che workspace routing isn't installed

src/pages/GetStarted/index.tsx, src/store/Workspaces/index.ts
Fixed bug that caused the alert message "Failed to find the target workspace." on the IDE loading page while the workspace was loading successfully.
fixes https://github.com/eclipse/che/issues/19603
=> Fixed the IDE loading page can't find the target workspace.

src/containers/FactoryLoader.tsx, src/services/helpers/types.ts, src/services/workspace-client/devWorkspaceClient.ts, src/services/workspaceAdapter/index.ts, src/store/Workspaces/devWorkspaces/index.ts
This PR makes it so that devworkspace messages are logged both through normal workspace startup and the factory flow. For now the PR is made against the workspace-adapter branch but once that PR is merged I'll switch the base to be master
https://github.com/eclipse/che/issues/19327
=> Show devworkspace logs when starting a devworkspace

.github/workflows/ci-multiarch.yaml, .github/workflows/ci.yaml, .github/workflows/codecov.yaml, .github/workflows/pr.yaml, make-release.sh
Adapt dashboard to default branch renaming
it's done in the scope of https://github.com/eclipse/che/issues/19614
=> Adapt dashboard to default branch renaming

src/Layout/index.tsx, src/store/Workspaces/index.ts
This PR prevents unwanted hiding the navbar, which happens sometimes when a user navigates from Theia IDE that is starting to any other UD page. Now the UD checks if it's the IDE page and only then hides the navbar.
=> Don't hide the navbar if it's not the IDE page

.github/workflows/pr.yaml
This PR removes building of Che Server since dashboard is run as separate deployment.
:warning: it depends on eclipse-che/che-operator#684
It's done in a scope of https://github.com/eclipse/che/issues/17802
=> Do not build Che Server anymore

package.json, src/components/DevfileEditor/index.tsx, src/pages/WorkspaceDetails/EditorTab/index.tsx, src/pages/WorkspaceDetails/index.tsx, src/services/workspace-client/devWorkspaceClient.ts, src/services/workspaceAdapter/index.ts, src/store/Workspaces/devWorkspaces/index.ts, src/store/Workspaces/index.ts, yarn.lock
This PR makes so it so that you are able to edit devworkspaces in the dashboard and save them to your cluster.
The basic flow with editing devworkspaces is:
- If you are saving a devworkspace and the devworkspace is not running then save it directly to the cluster without asking
- If you are saving a devworkspace and the devworkspace is running then ask for confirmation if they want to restart or not
- If they say they want to restart then update the devworkspace directly on the cluster and then restart the devworkspace
- This will also remove the `che.eclipse.org/dashboard-next-run` annotation if it is present and proceed with whatever was directly in the devfile editor 
- If they say they do not want to restart then add in a `che.eclipse.org/dashboard-next-run` annotation which will …
=> Add in the ability to edit devworkspaces in the dashboard

src/services/bootstrap/PreloadData.ts
This PR removes requesting default plugins for devworkspaces, since we don't have any ATM but https://github.com/eclipse/che/pull/19725 adds Theia extension there which does not have devfile at all.
It unblocks https://github.com/eclipse/che/pull/19725
=> Do not request plugins for devworkspaces

src/containers/FactoryLoader.tsx, src/containers/IdeLoader.tsx, src/containers/__tests__/FactoryLoader.spec.tsx, src/pages/FactoryLoader/index.tsx, src/pages/IdeLoader/index.tsx, src/services/workspace-client/devWorkspaceClient.ts
Add error handlers for codes from oauth flow.
fixes https://github.com/eclipse/che/issues/19722
=> add error handlers for codes from oauth flow

.eslintrc.js, .github/workflows/ci-multiarch.yaml, .github/workflows/ci.yaml, .github/workflows/pr.yaml, .github/workflows/release.yml, .gitignore, .htaccess, .vscode/settings.json, README.md, build/dockerfiles/Dockerfile, build/dockerfiles/rhel.Dockerfile, build/dockerfiles/rhel.entrypoint.sh, tsconfig.json, webpack.config.common.js, webpack.config.prod-dev.js
This PR adds in a rhel dockerfile that will be used downstream. ~~The reason why its added to /dockerfiles instead of build/dockerfiles is that build is currently being [used for something else](https://github.com/eclipse-che/che-dashboard/blob/main/tsconfig.json#L8).~~ In the newest version I've made the build output into the /lib folder like che-theia does and use build/dockerfiles for the dockerfiles
Part of https://issues.redhat.com/browse/CRW-1728
=> Add in a rhel dockerfile

.github/workflows/pr.yaml
This PR simply removes the `test-coverage-diff` job from the `PR` workflow in favor of `codecov` workflow.
=> Remove test-coverage-diff job in favor of codecov workflow

src/components/DevfileEditor/__tests__/DevfileEditor.spec.tsx, src/components/DevfileEditor/index.tsx, src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx, src/pages/GetStarted/CustomWorkspaceTab/index.tsx, src/pages/WorkspaceDetails/EditorTab/index.tsx
Fix DevfileEditor onChange callback.
Fixes https://github.com/eclipse/che/issues/19873
=> Fix Devfile Editor

build/dockerfiles/rhel.Dockerfile
Currently, running `yum -y -q update` in the rhel Dockerfile results in errors like:
```
Error: 
Problem 1: package perl-threads-1:2.21-2.el8.x86_64 requires libperl.so.5.26()(64bit), but none of the providers can be installed
- cannot install both perl-libs-4:5.30.1-451.module+el8.3.0+6961+31ca2e7a.x86_64 and perl-libs-4:5.26.3-419.el8.x86_64
- cannot install the best update candidate for package perl-threads-1:2.21-2.el8.x86_64
- cannot install the best update candidate for package perl-libs-4:5.26.3-419.el8.x86_64
......
```
because of a known issue with ubi8 images: https://access.redhat.com/solutions/6079011
There are 3 ways to work around it (that I can find):
1. Add in `--nobest` flag which is done here since it's pretty simple …
=> fix: Add in --nobest flag to fix a build issue with rhel Dockerfile

src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/DevfileLocationInput.tsx, src/pages/GetStarted/GetStartedTab/ImportFromGit/GitRepoLocationInput.tsx, src/store/Workspaces/__tests__/logs.spec.tsx, src/store/__tests__/helpers.spec.tsx, src/store/helpers.ts
This PR fixed several bugs some improvement:
- Fix the create state helper function. Add a test.
- Fix handing 'enter' button when using invalid URL.
- Added handling 'enter' button for 'Load Devfile' on 'Custom Workspace' page.
fixes https://github.com/eclipse/che/issues/19833
=> Fix deleting workspace flow

src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, src/pages/GetStarted/__tests__/devfileMetadata.json, src/services/registry/devfiles.ts, src/store/DevfileRegistries/selectors.ts
Display in getting started the `v2` links of devfile registries if DevWorkspace support is enabled.
Fixes https://github.com/eclipse/che/issues/19923
=> feat(getting-started): Display devfile v2 if che-server has devWorkspace support enabled

src/services/workspace-client/devWorkspaceClient.ts, src/store/Workspaces/devWorkspaces/index.ts
…ers in the initial devworkspace templates
This PR propagates the plugin registry and dashboard urls to every container in the initial devworkspacetemplate
https://github.com/eclipse/che/issues/19933
=> feat: Propagate the plugin registry and dashboard urls to the containers in the initial devworkspace templates

package.json, src/services/workspaceAdapter/__tests__/index.spec.ts, yarn.lock
Use newer dwclient to one with 2.1.0 schemaVersion. https://github.com/che-incubator/devworkspace-client/pull/24
=> feat: upgrade dwclient to one with 2.1.0 schemaVersion

src/services/workspace-client/devWorkspaceClient.ts
Dashboard tries to add a component to the current list of components but this list may be undefined with case of 'empty devfile' like:
```yaml
schemaVersion: 2.1.0-alpha
metadata:
name: devfile
```
note: I've added a trace for customers/end-users so they might look at what is happening under the hood (I just used a breakpoint)
Fixes https://github.com/eclipse/che/issues/19964
=> fix(devfilev2): Handle case when there is no component in the devfile

src/store/DevfileRegistries/index.ts
Adapts dashboard to getting rid of alpha suffix in schemaVersion for unreleased devfiles.
Depends on https://github.com/eclipse-che/che-server/pull/27
=> feat: get rid of -alpha suffix in schemaVersion for unreleased version

.vscode/launch.json, src/containers/WorkspaceDetails.tsx, src/pages/GetStarted/index.tsx, src/services/helpers/__tests__/getErrorMessage.spec.ts, src/services/helpers/getErrorMessage.ts, src/store/Workspaces/index.ts
This PR fixes messages for the errors happening while creating a new workspace, or updating an existing one.
fixes https://github.com/eclipse/che/issues/19945
provides a clearer error message for https://github.com/eclipse/che/issues/19922
=> Fix error messages

CONTRIBUTING.md, devfile.yaml
This PR moves contributing.md from eclipse/che repo.
Note that it contains a few fixes but still after them contributing flow is not working due:
https://github.com/eclipse/che/issues/20011 and https://github.com/eclipse/che/issues/18086
Fixes https://github.com/eclipse/che/issues/16431
=> feat: move contributing.md from eclipse/che repo

src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, src/store/Workspaces/index.ts
Fix devfile V1 update flow when devworkspace is enabled.
fixes https://github.com/eclipse/che/issues/19922
=> Fix devfile V1 update flow when devworkspace is enabled

package.json, yarn.lock
feat: use newer devworkspace client which created namespace if it does not exist
To test this PR you need to deploy specially configured che on minikube, commands from Platform team:
```
cp -R /Users/skabashn/dev/src/eclipse-che/che-operator/deploy/*  $TMP_DIR'/che-operator'
cp -R /Users/skabashn/dev/src/eclipse-che/devworkspace-operator/deploy/*  $TMP_DIR'/devworkspace'
echo $TMP_DIR 
chectl server:deploy --platform=minikube --installer=operator --workspace-engine=dev-workspace --che-operator-image=quay.io/skabashn/che-operator:che19944 --templates $TMP_DIR 
rm -rf $TMP_DIR
kubectl patch checluster/eclipse-che -n eclipse-che --type=json -p \
'[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]'
kubectl patch checluster/eclipse-che --patch …
```
=> feat: use newer devworkspace client which created namespace if it does not exist

packages/dashboard-frontend/src/Layout/Header/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/__tests__/WorkspacesList.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/GetStartedTab.spec.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/__tests__/index.spec.tsx, packages/dashboard-frontend/src/services/workspaceAdapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspaceAdapter/index.ts, packages/dashboard-frontend/src/store/__mocks__/cheWorkspaceBuilder.ts
The PR fixes a regression when changing workspace storage type on the workspace overview tab doesn't change the workspace devfile.
fixes https://github.com/eclipse/che/issues/19939
=> Fix changing workspace storage type from the overview tab

packages/dashboard-frontend/src/components/WorkspaceStatusLabel/index.module.css, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/FactoryLoader/updateDevfileMetadata.ts, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/pages/FactoryLoader/__tests__/__snapshots__/FactoryLoader.spec.tsx.snap, packages/dashboard-frontend/src/pages/FactoryLoader/index.tsx, packages/dashboard-frontend/src/services/helpers/devworkspace.ts, packages/dashboard-frontend/src/services/workspace-client/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/getDevfile.ts
Add factory create policies for devWorkspaces.
fixes https://github.com/eclipse/che/issues/19711
1. Create several workspaces from the same sample. 
* expected result: Workspace names should have generated parts at the end.
2. Resolve the factory with 'policies.create=peruser'
```{che-server}/f?url=https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml&policies.create=peruser```
several times.
* expected result: A new workspace was created only in the first attempt.
=> Add factory create policies for devWorkspaces

.github/dependabot.yml
Remove Dependabot for dockerfiles, which will be replaced by update-base-images.yml workflow in eclipse-che/che-release project (to manage all updates from one place)
https://github.com/eclipse/che/issues/18831
=> chore: Remove Dependabot for dockerfiles

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/pages/FactoryLoader/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/pages/FactoryLoader/__tests__/__snapshots__/FactoryLoader.spec.tsx.snap, packages/dashboard-frontend/src/pages/FactoryLoader/index.tsx
fix: better report resolved devfile during factory flow.
Mainly there are three cases:
1. devfile is found in git repo
$CHE_HOST/#https://github.com/eclipse-che/che-server
^ note now we report resolved devfile filename
2. devfile is not found, using default configuration
$CHE_HOST/#https://github.com/eclipse/che-dashboard
3. devfile is specified with raw content url
$CHE_HOST/#https://raw.githubusercontent.com/l0rd/spring-petclinic/devfile2/devfile.yaml
fixes https://github.com/eclipse/che/issues/20209
fixes https://github.com/eclipse/che/issues/19753
=> fix: better report resolved devfile during factory flow

packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/index.tsx, packages/dashboard-frontend/src/components/BannerAlert/index.tsx, packages/dashboard-frontend/src/services/helpers/detectBrowser.ts, packages/dashboard-frontend/src/store/Branding/index.ts
In this PR I added the fix that allows Dashboard to run in Safari. And since Safari is not supported users will always see the permanent banner with the warning message at the top of the page.
fixes https://github.com/eclipse/che/issues/20123
=> Dashboard warns users that Safari is not supported 

build/dockerfiles/rhel.Dockerfile
fix: fix link to nodejs 12 from redhat container catalog.
https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/ubi8/nodejs-12:1-90.1626843814 leads to 404
while the value used for base image is correct https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/ubi8/nodejs-12
N/A
=> fix: fix link to nodejs 12 from redhat container catalog

README.md
I thought I did it but I did not ¯\_(ツ)_/¯
So, this PR fix add namespace into configmap needed to allow connections from localhost
=> fix: add namespace into configmap needs to allow connections from localhost

packages/dashboard-frontend/src/Layout/index.tsx, packages/dashboard-frontend/src/services/keycloak/setup.ts
This PR provides users the ability to logout from Che Dashboard if Che is deployed with nativeUserMode.
https://user-images.githubusercontent.com/16220722/128518582-c7de09b3-3a89-4cb1-8917-f77d8f209729.mov
fixes https://github.com/eclipse/che/issues/20071
=> Fix logout for Che if it's been deployed with nativeUserMode enabled

packages/dashboard-frontend/src/services/workspace-client/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
Axios is returning a JSON object even if we specify a raw content
https://github.com/axios/axios/issues/907
Need to workaround with a custom transformResponse
Also, provide a better error message to isolate the root cause
Fixes https://github.com/eclipse/che/issues/20271
=> fix(scm): Always get raw content from scm resolver

packages/static-server/src/index.ts
This PR adds a hook for the static server that updates the `cache-control` header for resources that should not be cached by browsers.
Additionally, added redirection from `/dashboard` to `/dashboard/`.
fixes https://github.com/eclipse/che/issues/20266
=> Prevent browser to cache index.html and product.json

.ci/oci-dashboard-happy-path.sh
fix: fix devworkspace happy path by using up to date sample.
l0rd's sample is updated https://github.com/l0rd/spring-petclinic/pull/3 
but we depend on commit which is outdated. So, now we rely on the latest version of Che sample
No issues was created.
=> fix: fix devworkspace happy path by using up to date sample

packages/common/src/helpers/__tests__/errors.spec.ts, packages/common/src/helpers/errors.ts, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx
Fix getter for error messages.
fixes https://github.com/eclipse/che/issues/20365
=> Fix getter for error messages

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/StorageType/index.module.css, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/StorageType/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/GetStartedTab.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/__tests__/GetStarted.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/__tests__/Actions.spec.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx, packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts, packages/dashboard-frontend/src/services/devfileApi/devfile/index.ts, packages/dashboard-frontend/src/services/devfileApi/typeguards.ts, packages/dashboard-frontend/src/services/storageTypes.ts, packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-adapter/helper.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/getDevfile.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/selectors.ts, packages/dashboard-frontend/src/store/__mocks__/cheWorkspaceBuilder.ts, packages/dashboard-frontend/src/store/__mocks__/devWorkspaceBuilder.ts
This PR brings a new default devfile template for the custom workspace panels. Now it depends on enabling DevWorkspaces.
If DevWorkspaces is enabled it will suggest a devfile V2.1.0.
If DevWorkspaces is disabled it will suggest a devfile V1.
fixes https://github.com/eclipse/che/issues/19996
=> Suggest devfile v2 template when enabling DevWorkspaces

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
Allow to specify a custom editor in the repository or being inlined in the devfile.
With it, it's really convenient to try new editor or editor settings with DevWorkspace mode
Fix https://github.com/eclipse/che/issues/20258
With this PR enabled
I'm using `https://che-host#https://github.com/benoitf/dev-workspace-custom-editor/tree/ee1646a487c93a9fa1bcbda16e0dd50d0f1442a1` link
I've a custom che-theia starting with more memory (2048Mi vs 512Mi)
=> feat: Handle custom editor in repository or inlined in devfile

.deps/dev.md, .deps/problems.md, .deps/prod.md, packages/dashboard-backend/package.json, packages/dashboard-backend/src/services/che-http/CertsProvider.ts, packages/dashboard-backend/src/services/che-http/CheAxiosFactory.ts, packages/dashboard-backend/src/services/kubeclient/keycloak.ts, packages/dashboard-backend/tslint.json, yarn.lock
This PR makes dashboard backend uses internal Che Server URL when available and respect CAs, Http proxy settings in the same way as Theia does.
Probably it makes sense to move that logic to workspace-client library, but at this point I decided to take easier/quicker way since workspace-client has a lot of outdated stuff. So, I see that possible it will land to newer Che Typescript client, with devworkspaces and newer stuff.
Prereq for merging is https://github.com/eclipse-che/che-operator/pull/1073
Fixes https://github.com/eclipse/che/issues/20367
This is copied/pasted from Che operator PR:
Http proxy and custom certs are not easy to test, so I just copied Theia solution on dashboard side and assume it works.
1. For Che Self Signed certs verification you need to test Che on minikube: …
=> feat: make backend respect internal URL, CAs and http proxy settings

packages/dashboard-backend/src/devworkspace-client/services/api/workspace-api.ts
Avoid crashing backend on some errors due to NPE failure
Using development mode I had
```
TypeError: Cannot read property 'message' of null
at eval (webpack-internal:///./src/devworkspace-client/services/api/workspace-api.ts:165:27)
at doneCallOnce (webpack-internal:///../../node_modules/@kubernetes/client-node/dist/watch.js:72:21)
at LineStream.eval (webpack-internal:///../../node_modules/@kubernetes/client-node/dist/watch.js:83:38)
at LineStream.emit (events.js:315:20)
at emitCloseNT (internal/streams/destroy.js:87:10)
at processTicksAndRejections (internal/process/task_queues.js:79:21)
[nodemon] app crashed - waiting for file changes before starting..
```
and then the backend crashed
N/A
I've tested that with my fix, I never had backend crashing again
=> fix: avoid potential npe

README.md, local-start.sh, package.json, packages/dashboard-backend/src/local-run/che-server.ts, packages/dashboard-backend/src/local-run/dashboard.ts, packages/dashboard-backend/src/local-run/index.ts, packages/dashboard-backend/src/services/kubeclient/keycloak.ts, packages/dashboard-frontend/webpack.config.dev-server.js
Add an ability to run local dashboard against Che behind OpenShift OAuth.
It's achieved by using port-forward and using token from the current kubeconfig.
Possible alternative - run locally docker container with OpenShift OAuth and configure it with OAuth client from the cluster. It also requires modifying OAuthClient CR. It does not see easier, so post poning for time we'll see need for that.
<details>
<summary>Details</summary>
```yaml
- resources: {}
terminationMessagePath: /dev/termination-log
name: oauth-proxy
securityContext:
capabilities:
drop:
- KILL
- MKNOD
- SETGID
- SETUID
runAsUser: 1000630000
ports:
- containerPort: 8080
protocol: TCP
imagePullPolicy: Always
volumeMounts:
- name: oauth-proxy-config
mountPath: /etc/oauth-proxy
- name: kube-api-access-sp8cg
readOnly: true …
```
=> Add an ability to run local dashboard against Che behind OpenShift OAuth

.github/workflows/pr.yml
Images that are build during PR checks, will be now pushed to quay.io/eclipse/che-dashboard:pr-<pull_request_number>, instead of Docker.io
This would help normalize secrets usage across all repos https://github.com/eclipse/che/issues/20530
=> chore: change PR check image repository to quay.io

packages/dashboard-frontend/src/store/Branding/index.ts
Branding on the Dashboard now gets updated immediately with any portion of data received without waiting for the complete set of data.
https://issues.redhat.com/browse/CRW-1948
1. Deploy multi-host Che Server with a custom product.json on minikube
2. Do not import the certificate
3. Go to the Dashboard, open the About widget. There you should be able to see the custom product name.
=> Fix updating branding data

packages/dashboard-frontend/package.json
Bump version of `@eclipse-che/che-theia-devworkspace-handler` to the https://www.npmjs.com/package/@eclipse-che/che-theia-devworkspace-handler/v/0.0.1-1632729321 which doesn't contains vsix-installer image.
Part of https://github.com/eclipse-che/che-theia/pull/1222
Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>
https://issues.redhat.com/browse/CRW-1731
TBD
=> Bump version of @eclipse-che/che-theia-devworkspace-handler to the latest released

packages/common/tsconfig.json, packages/dashboard-frontend/src/pages/WorkspacesList/Rows.tsx, packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts, packages/dashboard-frontend/src/services/workspace-adapter/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.changeWorkspaceStatus.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.create.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.update.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/selectors.ts, packages/dashboard-frontend/src/store/__mocks__/devWorkspaceBuilder.ts, tsconfig.json, yarn.lock
The timestamp of a devworkspace last modification is stored as the annotation and gets updated each time it's started or changed using the devfile editor. 
fixes https://github.com/eclipse/che/issues/19815
1. Start frontend dev-server against Che deployed with devworkspaces enabled
2. Create devworkspace, go to workspaces list and see that its "Last Modified" time is "less than a minute ago"
3. Wait for a few minutes and (re)start the workspace, the "Last Modified" time should be updated.
=> Save timestamp of the last modification as a devworkspace annotation

packages/dashboard-frontend/src/services/helpers/location.ts
Allow to specify the name of the devfile to use in the repositories
so if there are .devfile.yaml (using v1) you can add a `.devfile.v2` or `.devfilev2.yaml` in your repository and then specify the path to this file to load DevFile v2 workspaces
Appending `?devfilePath=devfilev2.yaml` or `?df=devfilev2.yaml`
Fixes https://github.com/eclipse/che/issues/20607
Tested using `http://che-host/#https://github.com/benoitf/che-server?devfilePath=devfilev2.yaml`
Also use short query `df` `http://che-host/#https://github.com/benoitf/che-server?df=devfilev2.yaml`
In that case it's fetching a totally different devfile than the default one (it's the one coming from spring petclinic) so at the end the workspace is named "spring-petclinic"
if you just provide …
=> feat: Allow to specify the path to the devfile with factory workflow

packages/dashboard-frontend/src/containers/IdeLoader.tsx, packages/dashboard-frontend/src/containers/__tests__/IdeLoader.spec.tsx, packages/dashboard-frontend/src/pages/IdeLoader/index.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR adds the ability to restart a failed workspace directly on the IDE loading page. 
fix https://github.com/eclipse/che/issues/19105
1. Modify an existing workspace devfile to make it broken, e.g. change a container image name to a non-existing one.
2. Try to load the workspace.
=> Add "Restart" action to the IDE loading flow

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Handle id, reference, inline and override properties
Fixes https://github.com/eclipse/che/issues/20715
Tested with default samples and in addition:
+ https://github.com/benoitf/override-editor-memory (id definition + override)
+ https://github.com/benoitf/use-reference-editor (external definition + override)
+  https://github.com/benoitf/exvscd (ide is not displayed directly but we can see that it's using the inline definition)
=> fix: complete support of che-editor.yaml file

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Use last version of the library:
- Add volume components if plug-ins have defined volumeMounts
- Handle override of che-theia-plugins
Fixes https://github.com/eclipse/che/issues/20805
Fixes https://github.com/eclipse/che/issues/20596
Use tests provided by the two PRs:
https://github.com/eclipse-che/che-theia/pull/1262
https://github.com/eclipse-che/che-theia/pull/1263
I tested using:
- start from `https://<che-host>#https://github.com/l0rd/spring-petclinic?devfilePath=.devfilev2.yaml` should succeed instead of reporting an error as today
- start from `https://<che-host>#https://github.com/svor/java-spring-petclinic/tree/sv-che-preferences` and check that java language server is started with LightWeight mode
=> feat: update to the latest theia DW library

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx
For the factory flow, covert any devfile v2 to v1 when Che is running in che-server mode
This PR fixes when the dashboard should convert devfiles v2 to v1 while performing factory flow in che-server mode.
https://issues.redhat.com/browse/CRW-2411?focusedCommentId=19350430&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19350430
Create workspaces using factory flow with following devfiles:
`https://raw.githubusercontent.com/crw-samples/quarkus-quickstarts/devfilev2/devfile.yaml`
`https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml`
=> fix: devfile converted usage

packages/dashboard-frontend/src/containers/FactoryLoader/devfile-converter.ts, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/DevfileSelector/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/ImportFromGit/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, packages/dashboard-frontend/src/services/helpers/__tests__/getDefaultDevfile.spec.ts, packages/dashboard-frontend/src/services/helpers/getDefaultDevfile.ts, packages/dashboard-frontend/src/services/helpers/types.ts, packages/dashboard-frontend/src/services/storageTypes.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/getDevfile.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/getDevfile.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
When Che is running devworkspace mode, the dashboard should supply the default devfile v2 instead of a devfile v1 resolved by Che Server.
fixes https://github.com/eclipse/che/issues/20705
Create a workspace using factory flow from `<che-host>#https://github.com/eclipse/che`
=> Provide default devfile v2 in the devworkspace mode

packages/common/src/helpers/__tests__/errors.spec.ts, packages/common/src/helpers/errors.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
This PR fixes the regression caused by https://github.com/eclipse-che/che-dashboard/commit/61f0902c6305c35e6496e194d31c7d5e689dc596. 
fixes https://github.com/eclipse/che/issues/20835
see https://github.com/eclipse-che/che-server/pull/178
=> fix: factory resolver to respect the OAuth response

.deps/prod.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/inversify.config.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/DevWorkspaceEditorProcessCode.ts, yarn.lock
Adds VS code devfile enhancement into dashboard
fixes https://github.com/eclipse/che/issues/20679
Using the image built by this PR:
Clicking with the che-editor link to the current editor devfile from the plug-in registry
```
https://<che-cluster>#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?che-editor=https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/insiders/devfile.yaml
```
https://user-images.githubusercontent.com/436777/144198130-f73a69c8-f452-4790-ba82-2b9a70b8f459.mp4
=> feat: Adds vscode library processing into dashboard

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Handle v2.2.0 -> v1 devfiles (even invalid devfiles like the one in OpenShift console)
For che-server workspaces. Do not try with devWorkspace mode
depends on https://github.com/eclipse-che/che-server/pull/189
closes https://github.com/eclipse/che/issues/20856
2.2.0 example with invalid workingdirectory
https://che-server#https://github.com/devfile-samples/devfile-sample-code-with-quarkus
2.2.0 example with invalid workingdirectory
https://che-server#https://github.com/devfile-samples/devfile-sample-java-springboot-basic 
invalid place-holder image and invalid image
https://che-server#https://github.com/devfile-samples/devfile-sample-java-springboot-basic/tree/03d097ddbe0c8b4e6a413c75199b48a3086b7afd
=> feat: fix v2.2.0 -> v1 devWorkspaces

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/services/helpers/__tests__/location.spec.ts, packages/dashboard-frontend/src/services/helpers/location.ts
**only for devWorkspace mode* Change default policy to only create only one workspace when we click on a link
To create a new workspace, allow to use `?new` at the end of the short URL
ie: 
```
http://che-server#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 : only one workspace
http://che-server#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2?new ==> create a new workspace
```
fixes https://github.com/eclipse/che/issues/20867
yes clicking first
http://localhost:3000#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2
then clicking on http://localhost:3000#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2 is reopening the same workspace
and http://localhost:3000#https://github.com/che-samples/java-spring-petclinic/t …
=> feat: change default policy and add ?new for starting a new workspace using short syntax

packages/dashboard-frontend/src/pages/WorkspaceDetails/EditorTab/index.tsx, packages/dashboard-frontend/src/store/DevfileRegistries/getDevfileSchema.ts, packages/dashboard-frontend/src/store/DevfileRegistries/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__tests__/DevfileRegistries/getDevfileSchema.spec.ts
Fix the ability to edit DevWorkspaces in the dashboard.
fixes https://github.com/eclipse/che/issues/20737
fixes https://github.com/eclipse/che/issues/20889
1. Create a new devworkspace.
2. Do some changes (e.g. change an image in the conteiner) in the devfile editor and pres 'save' button.
https://user-images.githubusercontent.com/6310786/145601785-f14e19fd-0566-4354-b584-b0ac257b0bd8.mov
=> Fix the ability to edit devworkspaces

packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/fetchAndUpdateDevfileSchema.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/fetchAndUpdateDevfileSchema.ts, packages/dashboard-frontend/src/store/DevfileRegistries/index.ts
This PR fixes the issue that the dashboard is not able ot fetch a devfile schema.
fixes https://github.com/eclipse/che/issues/20919
Use the dashboard image from this PR
=> fix: request devfile JSON schema

packages/dashboard-frontend/src/store/Workspaces/index.ts
https://github.com/eclipse/che/issues/20900
Hiding devfile v1 che-server based workspaces if DevWorkspace engine is enabled
Before:  
After:
Hiding devfile v1 che-server based workspaces if DevWorkspace engine is enabled
N / A
=> feat: Hiding devfile v1 che-server based workspaces if DevWorkspace engine is enabled

devfile.yaml, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/CustomWorkspaceTab/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/index.tsx, packages/dashboard-frontend/src/services/__tests__/storageTypes.spec.ts, packages/dashboard-frontend/src/services/devfile/converters.ts, packages/dashboard-frontend/src/services/devfileApi/__mocks__/index.ts, packages/dashboard-frontend/src/services/helpers/getDefaultDevfile.ts, packages/dashboard-frontend/src/services/storageTypes.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV1.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts, packages/dashboard-frontend/src/store/__mocks__/cheWorkspaceBuilder.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts, yarn.lock
With this PR it's possible to start devworkspaces using factory flow for repositories with devfile v1. 
resolves https://github.com/eclipse/che/issues/20784
fixes https://github.com/eclipse/che/issues/20893
Deploy Eclipse Che with devworkspaces mode enabled and create workspaces using factory links below:
*devfiles v1*:
1.  ✅ `[che-host]#https://github.com/eclipse-che/che-dashboard/tree/da713f90d68b22c339dbef9404c27dcd882da642` 
2. ✅ `[che-host]#https://github.com/eclipse-che/che-devfile-registry/raw/main/devfiles/nodejs-react/devfile.yaml`
3. ✅ `[che-host]#https://raw.githubusercontent.com/eclipse-che/che-devfile-registry/main/devfiles/java-web-spring/devfile.yaml` 
*devfiles v2*:
1. ✅ `[che-host]#https://github.com/che-samples/java-spring-petclinic/tree/devfilev2` 
2. ✅ …
=> Convert devfiles in accordance to mode which Che is running

local-start.sh, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-frontend/src/inversify.config.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/serverConfigApi.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/DevWorkspaceDefaultPluginsHandler.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.onStart.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
This PR is the same PR as https://github.com/eclipse-che/che-dashboard/pull/425, except, its source branch is in the `eclipse-che/che-dashboard` repository rather than `dkwon17/che-dashboard`.
eclipse/che#20090
=> feat: manage default uri plugins for DevWorkspaces

packages/dashboard-backend/src/api/kubeConfigAPI.ts, packages/dashboard-backend/src/devworkspace-client/index.ts, packages/dashboard-backend/src/devworkspace-client/services/api/kubeConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/services/helpers/stream.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-backend/src/index.ts, packages/dashboard-backend/src/typings/models.d.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR implements editor agnostic kubeconfig injection for devworkspaces by calling a new endpoint `/namespace/:namespace/devworkspaceId/:devworkspaceId/kubeconfig` everytime a devworkspace is loaded. This new API injects the kubeconfig into all containers associated with a devworkspaceId.
https://github.com/eclipse/che/issues/20782
Ensure that Che is running with devworkspaces enabled then either create a new devworkspace from the dashboard itself or use `https://gist.githubusercontent.com/JPinkney/d4f6e665d1239a5fc4caefbe20bf4f56/raw/96faebbd51b3bba209f8a8de8b448327f385c779/a.yaml` with a factory url (that gist has vscode-kubernetes-tools and vscode-yaml pre-installed). Wait for the workspace to start and then observe that the …
=> [feat] Implement editor agnostic kubeconfig injection

packages/dashboard-backend/src/api/authorizeInfo.ts, packages/dashboard-backend/src/api/kubeConfigAPI.ts, packages/dashboard-backend/src/api/templateApi.ts, packages/dashboard-backend/src/constants/schemas.ts, packages/dashboard-backend/src/devworkspace-client/services/api/kubeConfigApi.ts, packages/dashboard-backend/src/index.ts, run/prepare-local-run.sh
Fix kubeConfigApi error messages.
In addition, this PR includes:
- Increasing delay for the prepare-local-run script.
- Add authorized info API (for development mode only).
- Fix swagger schema for kubeConfig API.
1. Ensure that Che is running with devworkspaces enabled then either create a new devworkspace from the dashboard.
2. Wait for the workspace to start.
2. Open  swagger ```/dashboard/api/swagger``` and use 'kubeconfig'. 
3. Stop workspace and try it one more time. It should throw an error:
```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "Error occurred when attempting to retrieve pod. Could not find the requested devworkspace with id... "
}
```
=> Fix KubeConfig API error messages

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts, packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/DevWorkspaceDefaultPluginsHandler.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.create.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.onStart.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, run/local-run.sh
Adds default plugins support for devworkspaces created with resources.
1. Deploy Che with the dashboard image for this PR: quay.io/dkwon17/che-dashboard:default-plugins
2. Add this field to the existing CheCluster CR:
```
server:
workspacesDefaultPlugins:
- editor: 'eclipse/che-theia/next'
plugins: ['https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/containers/buildah/latest/devfile.yaml']
```
4. Start a sample devworkspace from the che-dashboard. 
5. Verify that the devworkspace has a plugin component for the default plugin
6. Remove `server.workspacesDefaultPlugins` from the CheCluster CR.
7. Start the same devworkspace from step 4, and verify that the devworkspace does not have the default plugin anymore
=> fix: default plugins support for devworkspaces created with resources

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/containers/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.module.css, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, run/prepare-local-run.sh, run/revert-local-run.sh
Add owner references templates and source information into devWorkspace
fixes https://github.com/eclipse/che/issues/21013
fixes https://github.com/eclipse/che/issues/21022
1. Click on a sample to create a workspace
2. Delete the workspace
3. Try to create a workspace from the previous sample
4. Click on the same sample one more time - the existing workspace would be opened
=> Add owner references into devWorkspace templates

packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/converter.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/test-devfile-parent.yaml, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/test-devworkspace-parent.yaml, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/index.ts
With this fix, the dashboard will not ignore `parent` section of a devfile while creating new workspaces.
https://github.com/eclipse/che/issues/21098
=>  Provide devfile parent section to a new devworkspace

packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/services/devfileApi/devfile/metadata.ts, packages/dashboard-frontend/src/services/devfileApi/typeguards.ts
See discussion here: https://github.com/eclipse/che/issues/21067
---
If starting a devfile v2 that has generateName instead of name v2 checks fail since they only check for `name`. See: https://github.com/nils-mosbach/che-dashboard/blob/f9c2a7c087871c6095b033729c51729f779f252c/packages/dashboard-frontend/src/services/devfileApi/typeguards.ts#L19-L24
This leads to the following message:
``` 
Failed to create a workspace. Failed to create a new workspace from the devfile, reason: Failed to create a new workspace. Unable to create devworkspace: DevWorkspace.workspace.devfile.io "devfile-test" is invalid: [<nil>: Invalid value: "": "spec.template.components" must validate one and only one schema (oneOf). Found none valid, spec.template.components.container: Required value, …
```
=> fix: generateName is not executed if devfile v2

packages/dashboard-backend/src/local-run/che-server.ts, packages/dashboard-frontend/src/containers/FactoryLoader/__tests__/FactoryLoader.privateRepo.spec.tsx, packages/dashboard-frontend/src/containers/FactoryLoader/__tests__/FactoryLoader.spec.tsx, packages/dashboard-frontend/src/containers/FactoryLoader/index.tsx, packages/dashboard-frontend/src/services/session-storage/index.ts
This PR makes the dashboard limit the number of reloads during factory flow. If there happen two reloads in a row then the dashboard stops resolving the devfile.
https://user-images.githubusercontent.com/16220722/152542768-06db0482-757a-4398-9f97-9a549430fc5d.mp4
fixes https://github.com/eclipse/che/issues/21077
1. [Configure GitHub OAuth](https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-github-oauth_che) with a wrong secret
2. Create factory using a private repo url
=> Prevent infinite reloads loop

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
After Che-Dashboard is loaded DevWorkspaceTemplates are automatically updated to their latest plugins definition. This breaks existing workspaces for editors (e.g. che-code) that use sidecarless mode.
While starting new workspaces Che-Dashboard will remove editor definitions from DevWorkspaceTemplate since these get merged to the users dev container. If DevWorkspaceTemplate get updated, DevWorkspaceTemplate and DevWorkspace both contain editor definitions. Workspace therefore will fail to start due to duplicate ports.
Quick fix is skipping the update in case of `che-code`. Maybe `intellij` and `pycharm` would also make sense.
See also: https://github.com/eclipse/che/issues/21085
=> fix: skip DevWorkspaceTemplate updates for sidecarless editors (che-code)

packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.conversion.spec.tsx, packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/containers/WorkspacesList.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts
Each new workspace created via converting an old Che7 workspace will have a new annotation (`controller.devfile.io/devworkspace_id_override`) added so Che7 workspace folder can be mounted and reused after migrating to DevWorkspace.
Additionally, the dashboard hides the "Delete" button for those old workspaces that were converted. This should prevent accidentally deleting a Che7 workspace with all related resources while they are in use by a new devworkspace.
fix https://github.com/eclipse/che/issues/21153
unit tests
=> Add annotation with workspace ID

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Fix some devfile v1 to v2 conversions
che-server engine was more permissive on rules
- handle invalid project name (needs to be lowercase with devWorkspace engine)
- handle multiple volume mount
- handle duplicated endpoints (it's an error with devWorkspace engine)
Fixes https://github.com/eclipse/che/issues/21167
Fixes https://github.com/eclipse/che/issues/21121
1 out of 3 issues of https://github.com/eclipse/che/issues/21120 (other issues are not related to this converter lib)
Unit tests added on the converter library
=> fix: Fix some devfile v1 to v2 conversions

packages/dashboard-frontend/src/services/workspace-adapter/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Add plugin registry environment variables if creating devworkspaces from generated resources.
https://github.com/eclipse/che/issues/21054
=> Add plugin registry environment variables (#446)

README.md, packages/common/src/dto/cluster-config.ts, packages/common/src/dto/cluster-info.ts, packages/dashboard-backend/src/api/clusterConfig.ts, packages/dashboard-backend/src/api/clusterInfo.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-backend/src/index.ts, packages/dashboard-frontend/src/Layout/Header/Tools/ApplicationsMenu/__tests__/index.spec.tsx, packages/dashboard-frontend/src/Layout/Header/Tools/index.tsx, packages/dashboard-frontend/src/components/BannerAlert/Custom/index.module.css, packages/dashboard-frontend/src/components/BannerAlert/Custom/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/__tests__/index.spec.tsx, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/clusterConfig.ts, packages/dashboard-frontend/src/store/BannerAlert/index.ts, packages/dashboard-frontend/src/store/ClusterConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ClusterConfig/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/ClusterConfig/index.ts, packages/dashboard-frontend/src/store/ClusterConfig/selectors.ts, packages/dashboard-frontend/src/store/ClusterInfo/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ClusterInfo/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/ClusterInfo/index.ts, packages/dashboard-frontend/src/store/ClusterInfo/selectors.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts, packages/dashboard-frontend/src/store/index.ts
The Dashboard looks into the CheCluster CR for a warning message:
```yaml
spec:
dashboard:
warning: "Eclipse Che hosted by Red Hat is going to ..."
```
and shows it as a permanent banner.
<details>
<summary>Screenshots</summary>
</details>
https://github.com/eclipse/che/issues/20724
=> Add ability to show a warning banner by configuring CheCluster CR

.github/workflows/try-in-web-ide.yaml
chore: Adding 'try-in-web-ide' ci yaml
https://github.com/eclipse/che/issues/20664
Currently failing for me with: 
```
Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "docker.io/node:12.20.1-alpine3.12": rpc error: code = Unknown desc = loading manifest for target platform: reading manifest sha256:e63dd88799eeccf4f2869963bf79fb2aa7fa24aacf22ef9d6603c0c3ee7f4a07 in docker.io/library/node: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit', 'workspace4ojyba69btvx9mqw.dashboard-dev-75c7d7894d-gktbs'"
```
The problem is related to the dockerhub pull rate limit, and I believe we need to move the devfile related images to …
=> chore: Adding 'try-in-web-ide' ci yaml

packages/dashboard-frontend/src/containers/IdeLoader.tsx, packages/dashboard-frontend/src/containers/__tests__/IdeLoader.spec.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.changeWorkspaceStatus.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
**This PR is a copy of https://github.com/eclipse-che/che-dashboard/pull/469 but based in the main repo (not a fork) in order to allow github actions to run correctly.**
* Clear error message in IdeLoader when "restart" button is clicked
* Request the DevWorkspace on load to ensure logs include the last failure reason for failed DevWorkspaces
Closes https://github.com/eclipse/che/issues/21134
1. Create a workspace (devfile v2) and update it so that it fails to start (e.g. change image tag to non-existent one)
2. Start workspace, wait for it to fail (due to ImagePullBackoff)
3. Load failed workspace from sidebar
* Verify that error message references ImagePullBackoff and is not "Unknown error."
4. Click "Restart" button in error banner
* Verify that banner is cleared as DevWorkspace …
=> fix: Improve IdeLoader banner to better reflect state of DevWorkspace

packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/test-devfile-parent.yaml, packages/dashboard-frontend/src/services/workspace-client/devworkspace/converters/__tests__/fixtures/test-devworkspace-parent.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Do not allow starting a DevWorkspace if there is already one running
https://github.com/eclipse/che/issues/21032
Based on the internal discussion, for the time being, it was decided not to add extra property similar to `CHE_LIMITS_USER_WORKSPACES_RUN_COUNT` since we only support the common PVC strategy, so by definition only a single running workspace is allowed for RWO volumes.
against the dogfooding instance:
N/A
=> feat: do not allow starting a DevWorkspace if there is already one running

packages/common/src/dto/cluster-config.ts, packages/dashboard-backend/src/api/clusterConfig.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-backend/src/swagger.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/DevWorkspaceDefaultPluginsHandler.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.onStart.spec.ts, packages/dashboard-frontend/src/store/ClusterConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ClusterConfig/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/ClusterConfig/index.ts, packages/dashboard-frontend/src/store/ClusterConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
Get running workspaces limit from the cluster.
fix https://github.com/eclipse/che/issues/21032
=> Get running workspaces limit from the cluster

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Apply env variables not only in the template components but also in the devWorkspace components
Fixes https://github.com/eclipse/che/issues/21102
Check CHE_* env variables are defined in the user container
=> fix: apply registry and dashboard URL on all components

packages/common/src/helpers/__tests__/errors.spec.ts, packages/common/src/helpers/errors.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/selectors.ts
This PR fixes the regression with with "blank" screen that happens when `CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED` is set to `false` and a user doesn't have a pre-created namespace. With this PR, the dashboard opens successfully and shows the error alert with the message: `Creating the namespace '<username>' is not allowed, yet it was not found.` 
https://issues.redhat.com/browse/CRW-2788
Deploy Che with option `CHE_INFRA_KUBERNETES_NAMESPACE_CREATION__ALLOWED: 'false'` and use this dashboard image: **quay.io/eclipse/che-dashboard:pr-483**.
=> Fix blank screen on dashboard startup failure

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Handle persistVolume in devfile v1 when converting to v2
Fixes https://github.com/eclipse/che/issues/21290
unit test in devfile converter library
https://github.com/che-incubator/devfile-converter/commit/b6a30ccc7b2a6f715c953c72695afb241cc2f22b
=> fix: handle ephemeral in devfile converter

packages/dashboard-frontend/src/components/LogsTab/__tests__/__snapshots__/LogsTab.spec.tsx.snap, packages/dashboard-frontend/src/components/LogsTab/index.tsx, packages/dashboard-frontend/src/pages/IdeLoader/__tests__/__snapshots__/IdeLoader.spec.tsx.snap
Add scroll down automatically for logs.
fixes https://github.com/eclipse/che/issues/19255
=> Add scroll down automatically for logs

packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/Dropdown/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/OverviewTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.tsx
Fix workspace details page status update.
fixes https://github.com/eclipse/che/issues/21314
1. Open the workspace overview page.
2. Start (or stop) the workspace using the Recent workspaces section in the navigation bar.
3. Pay attention to the workspace status in the main page section.
4. Workspace status should get updated on the workspace overview page as well.
=> Fix workspace details page status update

packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/ConversionButton/index.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.tsx, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/helpers/__tests__/types.spec.ts, packages/dashboard-frontend/src/services/helpers/types.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR fixes:
- bug: duplicate items appeared in the recent workspaces section after conversion
- regression: deleting devworkspaces stuck in the Terminating phase
- regression: converted workspace was started automatically
- bug: browser console error: updating React state on an unmounted component
- regression: dashboard didn't open the new workspace after conversion is done
- regression: dashboard didn't update the workspaces list after deleting a converted workspace
- bug: che7 workspace didn't have the correct status icon 
https://github.com/eclipse-che/che-dashboard/pull/479#issuecomment-1076193524
fixes https://github.com/eclipse/che/issues/21316
fixes https://github.com/eclipse/che/issues/21208
=> Fix UI glitches and regressions related to devfiles conversion

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
Some usecases (like invalid endpoint name, project name, etc) were found on analyzing devfile v1 --> v2
Fix the converter tool
Fixes https://issues.redhat.com/browse/CRW-2787
Unit tests were added in the library
https://github.com/che-incubator/devfile-converter/pull/9
=> fix: Update devfile converter libray

packages/dashboard-frontend/src/containers/WorkspaceDetails/__tests__/index.conversion.spec.tsx, packages/dashboard-frontend/src/containers/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
Fix single running workspace restriction for DevWorkspaces.
fixes https://github.com/eclipse/che/issues/21032
1. Deploy Che with DevWorkspace enabled.
2. Create several workspaces from the samples.
3. You should see the restriction alert "... You are not allowed to start more workspaces.".
=> Fix single running workspace restriction for DevWorkspaces

.deps/EXCLUDED/dev.md, .deps/dev.md, packages/dashboard-frontend/src/Routes/index.tsx, packages/dashboard-frontend/src/preload/index.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/517 to the 7.46.x branch
Fixes https://github.com/eclipse/che/issues/21032 in 7.46.x
=> feat: add a new route for Factory flow (#517)

.deps/EXCLUDED/dev.md, .deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/devWorkspaceSpecTemplates.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/typings/che.d.ts
Add environment variables to all the DevWorkspace and DevWorkspaceTemplate containers
https://issues.redhat.com/browse/CRW-2964
=> fix: add registries and dashboard url to all containers

packages/dashboard-frontend/src/preload/index.ts
Fix redirect condition for preload script.
It needs for https://github.com/eclipse/che/issues/20599#issuecomment-1130717079
=> Fix redirect condition for preload script

packages/dashboard-frontend/src/preload/index.html, packages/dashboard-frontend/webpack.config.common.js
Add preload script HTML.
fixes https://issues.redhat.com/browse/CRW-2967
1) Open Google Chrome in incognito mode
2) Go to ```<CHE-Server>``` and you will be redirected to ```<CHE-Server>/dashboard/```  without loading any images or styles.
=> Add preload script HTML

.deps/prod.md, packages/dashboard-frontend/package.json, yarn.lock
update zip location to match local network
https://issues.redhat.com/browse/CRW-3011
[unit test in devfile-converter library](https://github.com/che-incubator/devfile-converter/commit/158532917deec3183193142791f8413a021aefe2)
=> fix: handle zip locations when migrating from v1 to v2

.github/workflows/pr.yml
This PR prevents running the licenses check PR job against any branch except the `main`.
=> fix: run licenses check only on main branch

.github/workflows/codecov.yml, packages/dashboard-frontend/jest.config.js, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts
After recent upgrading dependencies, the coverage-report check started failing. Same unit tests pass successfully while running with coverage turned off. In this PR I temporarily disable the coverage report check until we can figure out how to fix it.
fixes https://github.com/eclipse/che/issues/21437
=> Disable code coverage check

packages/dashboard-frontend/package.json, packages/dashboard-frontend/webpack.config.common.js
Since webpack v5 doesn't automatically polyfill node packages (see this [doc](https://gist.github.com/ef4/d2cf5672a93cf241fd47c020b9b3066a#webpack-5-node-polyfills-upgrade-cheatsheet)), this PR introduces polyfill for the Crypto package.
This PR prevents this error message from happening on devworkspace startup:
Check out this PR and follow [these steps](https://github.com/eclipse-che/che-dashboard#running-locally-against-remote-che-cluster) to run the dashboard locally against a cluster with Che + Devworkspace engine enabled.
Create a new devworkspace from the dashboard. The devworkspace should start successfully without the error message in the screenshot above.
=> fix: polyfill crypto package

packages/dashboard-backend/src/api/devworkspaceApi.ts, packages/dashboard-backend/src/devworkspace-client/__tests__/integration.spec.ts, packages/dashboard-backend/src/devworkspace-client/services/api/workspace-api.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-frontend/src/services/devfileApi/typeguards.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts
This PR allows the dashboard to create workspaces from devfiles without the `metadata` section.
fixes https://github.com/eclipse/che/issues/21429
Open link https://eclipse-che.apps.cluster-wb6n9.wb6n9.sandbox506.opentlc.com/#https://github.com/l0rd/tilt-example-java/tree/cc88c7f683e5ab50d36722e7b8366d871f6a73d4
=> fix: allow devfiles without `metadata.name`

packages/dashboard-frontend/index.html, packages/dashboard-frontend/src/Layout/index.tsx, packages/dashboard-frontend/src/services/helpers/login.ts, packages/dashboard-frontend/src/services/workspace-client/index.ts, packages/dashboard-frontend/src/store/Branding/index.ts
Fix unauthorized errors flow.
https://issues.redhat.com/browse/CRW-3060
1. Install CHE on OpenShift.
2. Set cluster accessTokenInactivityTimeout = 5 minutes:
```oc patch OAuth/cluster -p '{ "spec": { "tokenConfig": { "accessTokenInactivityTimeout": "5m" }}}' --type merge```
3. Open CHE Dashboard page in Google Chrome.
4. Leave it along about 20 minutes.
5. Refresh CHE Dashboard page.
6. CHE Dashboard should be redirected to the login page.
You can tested it with https://eclipse-che.apps.cluster-7vz9l.7vz9l.sandbox688.opentlc.com/dashboard/
=> Fix unauthorized errors flow

packages/dashboard-frontend/src/Layout/Header/Tools/UserMenu/__tests__/index.spec.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Fix kube config flow
fixes https://github.com/eclipse/che/issues/21454
1. Deploy Eclipse CHE
2. Create a new workspace from one of the samples. 
3.  `config` file should be in `~/.kube/` 
```
$ ls ~/.kube/
```
You can test it with https://eclipse-che.apps.cluster-k865s.k865s.sandbox811.opentlc.com
=> Fix kube config flow

packages/dashboard-backend/src/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/SamplesListGallery.spec.tsx, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/serverConfigApi.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.onStart.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts, packages/dashboard-frontend/src/store/index.ts
Add workspaces default editor and component.
fixes https://github.com/eclipse/che/issues/21353
fixes https://github.com/eclipse/che/issues/21502
1. Deploy Eclipse Che with this image: ```quay.io/eclipse/che-dashboard:pr-567```
2. Add defaults(patch checluster/eclipse-che). For example:
```
devEnvironments:
defaultComponents:
- container:
image: 'quay.io/devfile/universal-developer-image:ubi8-latest'
sourceMapping: /projects
name: universal-developer-image
defaultEditor: eclipse/theia/next
```
3. Create a workspace using a GitHub repository without a devfile. 
For example: ```https://github.com/eclipse-che/che-jwtproxy```
4. You should be able to see all default components propagated to the workspace
You can test it with https://eclipse-che.apps.cluster-5s2x5.5s2x5.sandbox995.opentlc.com
=> Add workspaces default editor and component

.deps/EXCLUDED/dev.md, .deps/dev.md, .deps/problems.md, package.json, packages/dashboard-frontend/webpack.config.common.js
Updates the webpack build not to inject the chunk named 'common' into the preload page. 
https://github.com/eclipse/che/issues/21490
=> fix: preload page

packages/dashboard-backend/src/api/kubeConfigApi.ts
Fix expected response for adding kubeconfig.
fixes https://github.com/eclipse/che/issues/21480
1. Deploy Eclipse CHE on k8s platform using  ```chectl```
2. Create a new workspace from one of the samples. 
3.  `config` file should be in `~/.kube/` 
```
$ ls ~/.kube/
```
4. Open swagger ```/dashboard/api/swagger``` and try to use 'Kube Config'
5. Response code should be 204
=> Fix expected response for adding kubeconfig

packages/dashboard-frontend/index.html, packages/dashboard-frontend/src/Layout/Header/Tools/UserMenu/index.tsx, packages/dashboard-frontend/src/components/DevfileEditor/index.tsx, packages/dashboard-frontend/src/components/TagLabel/__tests__/TagLabel.spec.tsx, packages/dashboard-frontend/src/components/TagLabel/__tests__/__snapshots__/TagLabel.spec.tsx.snap, packages/dashboard-frontend/src/components/TagLabel/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/DropdownEditors.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SampleCard.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/DropdownEditors.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/__tests__/SampleCard.spec.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/sample-card.css, packages/dashboard-frontend/src/pages/WorkspaceDetails/Header/Actions/Dropdown/index.tsx, packages/dashboard-frontend/src/store/Plugins/chePlugins/selectors.ts, packages/dashboard-frontend/static/loader.html
Added the ability to select an alternative editor from the dashboard.
fixes https://github.com/eclipse/che/issues/20627
=> Added the ability to select an alternative editor from the UD

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx
Remove 'che-pycharm' editor from excludes.
=> Remove 'che-pycharm' editor from excludes

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/FetchDevfile/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Initialize/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Initialize/index.tsx
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Parse authentication status query param and pass it to the che-server's factory API.
https://github.com/eclipse/che/issues/21436
=> chore: chore: Pass error_code param to factory api instead of throwing an error

packages/dashboard-backend/src/devworkspace-client/__tests__/errors.spec.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-frontend/src/services/bootstrap/__tests__/workspaceStoppedDetector.spec.ts
Migrate CheCluster API from v1 to v2
fixes https://github.com/eclipse/che/issues/21594
=> Migrate CheCluster API from v1 to v2

packages/common/src/dto/api.ts, packages/dashboard-backend/src/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/services/api/serverConfigApi.ts, packages/dashboard-backend/src/devworkspace-client/types/index.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/serverConfigApi.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.create.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
Provides OpenVSX CheCluster URL to user containers
fixes https://github.com/eclipse/che/issues/21563
=> Provides OpenVSX CheCluster URL to user containers

packages/dashboard-frontend/src/containers/Loader/AbstractStep.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/ApplyDevfile/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/ApplyResources/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/CreateWorkspace/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/FetchDevfile/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/FetchResources/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Initialize/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/Initialize/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/StartWorkspace/index.tsx, packages/dashboard-frontend/src/pages/Loader/Workspace/__mocks__/index.tsx, packages/dashboard-frontend/src/pages/Loader/Workspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/Loader/Workspace/index.tsx, packages/dashboard-frontend/src/services/helpers/types.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Signed-off-by: dkwon17 <dakwon@redhat.com>
When starting a workspace when there is already a workspace running, since the running workspace limit is `1` by default, there are now new links to:
* go to the running workspace
* stop the running workspace and restart the current workspace
When clicking "Close running workspace (bash) and restart golang-example", if there is an error when trying to stop the workspace, and alert with an error message will be displayed on the top right:
When there is more than one running workspace, there is a 'Return to Dashboard' link instead:
<details>
<summary>Demo video</summary>
https://user-images.githubusercontent.com/83611742/184721559-4265d656-b07e-4140-99e8-20a69d6e8e0a.mov
</details>
https://github.com/eclipse/che/issues/21359
1. Check out this PR …
=> Provide links to [stop/go to] running workspace when trying to start a workspace when workspace limit reached

packages/dashboard-frontend/src/pages/WorkspaceDetails/InlineAlerts/index.tsx
Backport https://github.com/eclipse-che/che-dashboard/pull/611 to 7.52.x
=> fix: fixing link to devfile v2 migration docs

packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/StartWorkspace/index.tsx, packages/dashboard-frontend/src/pages/Loader/Workspace/__tests__/index.spec.tsx
Signed-off-by: dkwon17 <dakwon@redhat.com>
Changes the `You are not allowed to start more workspaces.` message from an error message to a warning message.
https://github.com/eclipse/che/issues/21671
1. Follow [these steps](https://github.com/eclipse-che/che-dashboard#running-locally-against-remote-che-cluster-nodejs-v16) to run this PR locally. (or, use the docker image built for this PR)
2. By default, Eclipse Che's workspace `runningLimit` is `1`. In the CheCluster spec, the value comes from `spec.components.devWorkspace.runningLimit`. Start a workspace from the dashboard, and immediately start another one. You should see the `You are not allowed to start more workspaces` warning message.
=> chore: change workspaces runningLimit error to warning

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Initialize/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Initialize/index.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
* Don't request workspace if user namespace is not created
* Update error message if user tries to start a workspace when namespace is not created
https://github.com/eclipse/che/issues/21582
N/A
N/A
N/A
=> chore: Don't request workspace if user namespace is not created

packages/dashboard-frontend/src/containers/Loader/index.tsx, packages/dashboard-frontend/src/services/helpers/__tests__/location.spec.ts, packages/dashboard-frontend/src/services/helpers/location.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, run/revert-local-run.sh
Drop 'session' and 'code' attributes during startup.
fixes https://github.com/eclipse/che/issues/21655
=> Drop 'session' and 'code' attributes during startup

packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Prints the current workspaces running limit `spec.devWorkspace.runningLimit` when 
1. Follow [these steps](https://github.com/eclipse-che/che-dashboard#running-locally-against-remote-che-cluster-nodejs-v16) to run this PR locally. (or, use the docker image built for this PR)
By default, Eclipse Che's workspace runningLimit is 1. In the CheCluster spec, the value comes from `spec.components.devWorkspace.runningLimit`.
2. Start a workspace from the dashboard, and immediately start another one. The warning message should state that the running workspaces limit is 1.
3. Increase `spec.components.devWorkspace.runningLimit` to 2.
4. From the dashboard, start two workspaces. Start a third one to see the warning message stating that the workspaces …
=> feat: display workspace runningLimit in warning message

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/621 to the 7.52.x branch
fixes https://github.com/eclipse/che/issues/21664
=> fix: prevent patching DevWorkspace during startup

packages/dashboard-frontend/src/containers/Loader/index.tsx, packages/dashboard-frontend/src/services/helpers/__tests__/location.spec.ts, packages/dashboard-frontend/src/services/helpers/location.ts
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/623 to the 7.52.x branch
fixes https://github.com/eclipse/che/issues/21655
=> feat: drop 'session' and 'code' attributes during startup

packages/dashboard-backend/src/index.ts, packages/dashboard-backend/src/workspace.ts, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/services/oauth/index.ts, packages/dashboard-frontend/src/services/session-storage/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts, yarn.lock
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
* Set a flag to the browsers `SessionStorageService` when an OAuth authorisation is requested.
* When a factory is created and stoped and started again, check if the flag is set.
* If the flag is set, send a request to `che-server` to check the OAuth token
* If `che-server` returns an error, open an authentication page to authenticate.
https://github.com/eclipse/che/issues/21640
=> chore: Check OAuth token when workspace starts

.deps/prod.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/components/ExpandableWarning/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/ExpandableWarning/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/ExpandableWarning/index.module.css, packages/dashboard-frontend/src/components/ExpandableWarning/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/CheckExistingWorkspaces/index.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/SamplesListGallery.tsx, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/dashboard-backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/store/DevfileRegistries/selectors.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/Workspaces/cheWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, yarn.lock
Add a warning message for the user and prompt him if the workspace should start anyway (ignoring the existing devfile).
fixes https://github.com/eclipse/che/issues/20738
1. Deploy Che (dashboard image: quay.io/eclipse/che-dashboard:pr-643).
2. Try to accept the factory with the wrong URL, like 
```$CHE_HOST#https://github.com/AObuchow/che-dashboardrrrr```.
An error message should be shown:
3. Try to accept the factory from the repo with an invalid devfile scheme, like 
```$CHE_HOST#https://github.com/olexii4/che-dashboard```.
A warning message about starting anyway should be shown:
4. Try to accept the factory from the repo with a valid devfile wich includes unsuported attributes for target platform, like …
=> Handle gracefully when an invalid devfile is found in a git repository

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/prepareDevfile.ts, packages/dashboard-frontend/src/services/helpers/__tests__/sanitizeName.spec.ts, packages/dashboard-frontend/src/services/helpers/sanitizeName.ts
The User Dashboard sanitizes the devworkspace name before creating the devworkspace.
fixes https://github.com/eclipse/che/issues/21750
- unit test added
- successfully created DW from https://github.com/kamlendu1982/tower_engin
=> Sanitize workspace name

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/__tests__/getProjectFromUrl.spec.ts, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/getProjectFromUrl.ts, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/index.tsx
fix getting the default project from the factory URL.
1. Deploy Che (dashboard image: quay.io/eclipse/che-dashboard:pr-643).
2. Try to accept the factory:
```$CHE_HOST#/#https://github.com/l0rd/che-operator/tree/a4f1949c33ddab5f66c19c27a844af1c46aa0820```.  
3. A warning message about starting anyway will be shown. Apply the flow with the default devfile.
4. We should have the next project section in Devfile:
```
- git:
checkoutFrom:
revision: a4f1949c33ddab5f66c19c27a844af1c46aa0820
remotes:
origin: 'https://github.com/l0rd/che-operator.git'
name: a4f1949c33ddab5f66c19c27a844af1c46aa0820
```
=> fix: getting the default project from the factory URL

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.debugMode.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR fixes a PVC bug by adding attributes ```storage-type``` and ```scc``` in the right way.
The result should be something like this:
```
...
attributes:
controller.devfile.io/devworkspace-config:
name: devworkspace-config
namespace: eclipse-che
controller.devfile.io/scc: container-build
controller.devfile.io/storage-type: per-user
...
```
You can test it with https://eclipse-che.apps.cluster-z2zcs.z2zcs.sandbox1571.opentlc.com
=> Fix a devworkspace start action

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.debugMode.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
* fix: a patches queue for the devworkspace start action
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/675 into https://github.com/eclipse-che/che-dashboard/tree/7.56.x
=> Fix a devworkspace start action (#675)

packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
Fix the bootstrap queue to guarantee to have resourceVersion before subscribing to the onChange event.
fixes https://github.com/eclipse/che/issues/21809
=> Fix the bootstrap queue

packages/dashboard-backend/src/app.ts, packages/dashboard-backend/src/constants/schemas.ts, packages/dashboard-backend/src/devfileSchemas/1.0.0/devfile.json, packages/dashboard-backend/src/devfileSchemas/2.0.0/devfile.json, packages/dashboard-backend/src/devfileSchemas/2.1.0/devfile.json, packages/dashboard-backend/src/devfileSchemas/2.2.0/devfile.json, packages/dashboard-backend/src/devfileSchemas/2.2.1-alpha/devfile.json, packages/dashboard-backend/src/routes/api/devfileSchema.ts, packages/dashboard-backend/src/routes/api/devworkspaceTemplates.ts, packages/dashboard-backend/src/routes/api/devworkspaces.ts, packages/dashboard-backend/src/routes/api/dockerConfig.ts, packages/dashboard-backend/src/routes/api/kubeConfig.ts, packages/dashboard-backend/src/routes/api/userProfile.ts, packages/dashboard-backend/src/routes/api/yamlResolver.ts, packages/dashboard-backend/src/typings/models.d.ts, packages/dashboard-backend/tsconfig.json, packages/dashboard-frontend/src/services/dashboard-backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/fetchAndUpdateDevfileSchema.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/fetchAndUpdateDevfileSchema.ts, packages/dashboard-frontend/src/store/DevfileRegistries/index.ts, tsconfig.json
Added implementation of devfileSchema API
=> Added implementation of devfileSchema API

packages/dashboard-frontend/src/store/SanityCheck/index.ts
The sanity check makes a few attempts to provision a namespace.
fixes https://github.com/eclipse/che/issues/21799
=> Re-try namespace provisioning

.github/workflows/codecov.yml, .github/workflows/next-build-multiarch.yml, .github/workflows/pr.yml, .github/workflows/release.yml, .github/workflows/try-in-web-ide.yaml
Signed-off-by: sdawley <sdawley@redhat.com>
Replaces https://github.com/eclipse-che/che-dashboard/pull/686 against origin so PR checks can pass.
Update GitHub actions to use node 16 and Ubuntu to latest
https://github.com/eclipse/che/issues/21763
=> Chore: Update GitHub actions to use node 16 and Ubuntu to latest #686

packages/common/src/dto/api.ts, packages/dashboard-backend/src/constants/server-config.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/__tests__/serverConfig.spec.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-backend/src/routes/api/serverConfig.ts, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/StartWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/StartWorkspace/index.tsx, packages/dashboard-frontend/src/containers/Loader/const.tsx, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
feat: User workspace start timeout defined in CheCluster CR (https://github.com/eclipse-che/che-operator/pull/1576)
https://github.com/eclipse/che/issues/21820
N/A
N/A
N/A
=> feat: User workspace start timeout defined in CheCluster CR

packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/index.tsx, packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/isSupportedBrowser.tsx, packages/dashboard-frontend/src/components/BannerAlert/index.tsx
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/701
=> Backport: Remove "browser you are using is not supported" warning

packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/index.tsx, packages/dashboard-frontend/src/components/BannerAlert/NotSupportedBrowser/isSupportedBrowser.tsx, packages/dashboard-frontend/src/components/BannerAlert/index.tsx
This PR removes the banner that warns users about using a not supported browser.
The banner component is not removed but improved for possible further usage.
https://github.com/eclipse/che/issues/21866
=> Remove "browser you are using is not supported" warning

packages/dashboard-frontend/src/store/Workspaces/index.ts
Signed-off-by: Igor Vinokur <ivinokur@redhat.com>
Catch only the unauthorised exception when fetching oauth token on workspace start. Do not throw any other errors.
fixes https://github.com/eclipse/che/issues/21896
1. Deploy che without any oAuth providers.
2. Start a factory from a public GitHub repo.
3. Stop the workspace.
4. Restart the che pod in the openshift console
5.  Start the workspace.
See: no error appears.
=> Do not throw oauth provider not found error on workspace start

.ci/oci-dashboard-puppeteer.sh, .ci/resources/dashboard-pod.yaml
* This PR added script and resources for running the e2e tests based on jest+puppeteer stacks on an Openshift CI. It uses RedHat PROW CI.
* This works in the next way: after setting up an OpenShift cluster, install eclipse-che  (latest version) build the dashboard image, and patch the dashboard container section for consuming the image.  The next step is to apply the script in the **oci-dashboard-puppeteer.sh** file. It adds the test pod in the cluster which includes an image with a puppeteer codebase and a headless chrome browser.
* The test-pod performs the next scenario: go to the dashboard, create the empty workspace from the samples, and waiting for starting the workspace. After this go to the dashboard again and try to create a workspace from the same sample. Waiting for the massage …
=> Add e2e puppeteer test to CHE-Dashboard project

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/getProjectFromUrl.ts, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/index.tsx
Signed-off-by: dkwon17 <dakwon@redhat.com>
Implements the functionality described in [here](https://issues.redhat.com/browse/CRW-3482?focusedCommentId=21521544&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21521544)
> If the origin remote is not provided as a parameter we should infer it (as well as the branch) from the URL:
> 
> https://<che-host>#<origin-git-url>?remotes={{upstream,https://github...}}
> The remote to checkout should be the <origin-git-url>.
> 
> Note that the URL could be a raw devfile URL too and in this case we should not use it to add a remote.
This is acheived by adding remotes to the projects[0].git.remotes
instead of replacing them.
Additionally if the 'origin' remote exists, projects[0].git.checkoutFrom.remote will be set to …
=> feat: infer origin remote if not provided in remote url paramter

.github/workflows/release.yml
Attempt to fix release by pinning buildx to 0.9.1 since it seems to have broken when the image updated to 0.10.0
=> Pin buildx to v0.9.1

packages/dashboard-frontend/webpack.config.dev-server.js
Fix dev-server webpack configuration.
fixes https://github.com/eclipse/che/issues/21939
1. Running locally against remote Che Cluster
```yarn```
```yarn start:prepare```
```yarn start```
2. Login http://localhost:8080/dashboard/
3. Run Dev Server
```yarn frontend:start```
4. Open http://localhost:3000/dashboard/
=> Fix dev-server webpack configuration

packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/InfrastructureNamespaces/index.ts
This PR prevents the UD from making a few requests for namespace provision in a row.
n/a
=> fix: remove extra request for namespace provision

README.md
Signed-off-by: Anatolii Bazko <abazko@redhat.com>
Document the usage of the che-server API
https://github.com/eclipse/che/issues/21848
N/A
N/A
N/A
=> chore: Document the usage of the che-server API

.github/workflows/next-build-multiarch.yml, .github/workflows/pr.yml
Set buildx version to 0.9.1 to fix `Next container image` and `PR` workflows.
=> fix: set buildx version to 0.9.1

packages/dashboard-frontend/src/services/bootstrap/__tests__/workspaceStoppedDetector.spec.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/bootstrap/workspaceStoppedDetector.ts, packages/dashboard-frontend/src/store/Events/index.ts
Further alleviates https://github.com/eclipse/che/issues/21796. This PR does not solve the root problem however, the root problem is described in https://github.com/eclipse/che/issues/22008
Previously, dashboard tried to go back to the mainUrl of the workspace if the user was redirected to the dashboard via traefik errors middleware https://github.com/eclipse-che/che-operator/pull/1392 if the dashboard detects the DW `status.phase` to be RUNNING.
This PR tries to go back to the mainUrl if the dashboard detects the DW `status.phase` to be `RUNNING` or `STARTING`.
<details><summary>Demo</summary>
https://user-images.githubusercontent.com/83611742/219205265-e625f556-9953-486a-9ad0-7076c5459400.mov
</details>
https://github.com/eclipse/che/issues/21796
1. On a clusterbot cluster (`launch …
=> Redirect to workspace if it is running or starting

packages/dashboard-frontend/src/services/bootstrap/__tests__/workspaceStoppedDetector.spec.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/bootstrap/workspaceStoppedDetector.ts
Backports https://github.com/eclipse-che/che-dashboard/pull/730 to 7.60.x
Please see https://github.com/eclipse-che/che-dashboard/pull/730
=> Backport 'Redirect to workspace if it is running or starting'

packages/dashboard-frontend/src/Layout/index.tsx, packages/dashboard-frontend/src/components/DevfileEditor/index.tsx, packages/dashboard-frontend/src/components/WorkspaceLogs/Tools/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/CheckRunningWorkspacesLimit/index.tsx
This PR fixes the dashboard behavior when the user clicks the "Return to Dashboard" button on the workspace startup page, so both the navigation bar and the top bar gets shown after return.
fixes https://github.com/eclipse/che/issues/21950
=> Restore the navbar and topbar when return to the quick start page

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.create.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
This PR fixes the priority of defining a custom editor. 
So the lowest priority has the `defaultEditor` parameter set in the CheCluster CR. The next option with higher priority is `.che/che-editor.yaml` file. The highest priority has the `che-editor` URL parameter of a factory link.
fixes https://issues.redhat.com/browse/CRW-3921
1. Try `https://<che-host>#https://github.com/akurinnoy/vigilant-umbrella?che-editor=eclipse/che-theia/latest`. In this case Che-Theia editor will be used because the URL param has the highest priority.
2. Try `https://<che-host>#https://github.com/akurinnoy/vigilant-umbrella`. You'll get the Che-Idea because it's defined in the `.che/che-editor.yaml` file.
3. Try `https://<che-host>#https://github.com/eclipse-che/che-dashboard`. The default editor will be used.
=> Fix custom editor priority

packages/dashboard-frontend/src/pages/GetStarted/GetStartedTab/ImportFromGit/index.tsx, packages/dashboard-frontend/src/preload/index.ts, packages/dashboard-frontend/src/services/helpers/__tests__/location.spec.ts, packages/dashboard-frontend/src/services/helpers/location.ts
Drop 'session' and 'code' attributes during startup.
fixes https://github.com/eclipse/che/issues/21655
=> feat: drop 'state', 'session' and 'code' attributes during startup

packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/index.tsx
cherry-picking https://github.com/eclipse-che/che-dashboard/pull/746 to 7.60.x
=> fix: enable automatic revoke for GitHub only

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/services/oauth/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/oauth/index.ts, packages/dashboard-frontend/src/services/session-storage/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/Workspaces/index.ts
Refreshes OAuth access token when the devWorkspace is starting/restarting.
It does in a few steps:
- sends a request to che-server to check the OAuth token
- if che-server returns an error, open an authentication page to authenticate
https://issues.redhat.com/browse/CRW-3928
1. Update CheCluster CR with `vsvydenko/che-dashboard:7` dashboard image.
2. Configure GitLab Oauth as per the documentation https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/
3. Use factory to start a workspace with private project
4. Wait 2 hours when the access token is expired 
5. Try to restart the workspace and execute `git pull` in the workspace
https://user-images.githubusercontent.com/1271546/221356558-5e2e87ec-e665-4293-b4e3-72f357d80826.mp4
=> chore: refresh access token when workspace is starting

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/index.tsx
* Improve the error when the Factory URL is not supported or restricted.
* Ask to create a workspace from the default devfile.
https://github.com/eclipse/che/issues/21997
1. Deploy che via the test image: chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next
For the testing purpose I disabled gitlab factory handler in the image.
2. Apply the dashboard changes.
3. Pass a gitlab public repo with a devfile to start a workspace e.g. 'https://gitlab.com/ivinokur/test.git'
4. See the specific error:
=> Ask to start a workpspace from the default devfile, if the factory URL is unsupported

packages/common/src/dto/cluster-info.ts, packages/dashboard-backend/src/routes/api/__tests__/clusterInfo.spec.ts, packages/dashboard-backend/src/routes/api/clusterInfo.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.create.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/ClusterInfo/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Adds cluster console Url and title as env variables to a component.
https://github.com/eclipse/che/issues/21822
Editor's container should contain `CLUSTER_CONSOLE_URL` and `CLUSTER_CONSOLE_TITLE` env variables.
=> Add Openshift console URL as env variable to a component

packages/dashboard-frontend/src/Layout/Navigation/index.module.css, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/OpenWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/buildFactoryParams.ts, packages/dashboard-frontend/src/containers/Loader/const.tsx, packages/dashboard-frontend/src/overrides.css, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV2.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts
Add a new URL parameter to specify the Workspace image.
fixes https://github.com/eclipse/che/issues/21990
1. Deploy Eclipse CHE
2. Create a new workspace from URL ```{CHE}/dashboard/#/load-factory?url=https://raw.githubusercontent.com/eclipse-che/che-dashboard/main/packages/devfile-registry/devfiles/empty.yaml&image=docker.io/olexii4dockerid/universal-developer-image:test```. 
3. Open created workspace(workspace details) and the Devfile should contain an updated image 
```
...
container: {
image: 'docker.io/olexii4dockerid/universal-developer-image:test',
},
...
```
=> Add a new URL parameter to specify the Workspace image

packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts
feat: Move some defaults out of CheCluster to env variables
https://github.com/eclipse/che/issues/22064
N/A
=> feat: Move some defaults out of CheCluster to env variables

packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts
fix: Detecting if container build capabilities are disabled
https://github.com/eclipse/che/issues/22064
N/A
N/A
N/A
=> fix: Detecting if container build capabilities are disabled

.github/workflows/pr.yml
Unpin the v0.9.1 version of build, now that provenance is set to false ( in earlier PR )
https://github.com/eclipse/che/issues/21954
=> chore: unpin the v0.9.1 version of buildx

packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV2.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts
Ignore default components when a devfile references a parent.
fixes https://github.com/eclipse/che/issues/22103
=> Ignore default components when a devfile references a parent

packages/dashboard-backend/package.json, yarn.lock
Upgrade @eclipse-che/che-devworkspace-generator library from v0.0.1-96cdbb4 to v0.0.1-1f238bb.
fixes https://github.com/eclipse/che/issues/22103
=> Upgrade @eclipse-che/che-devworkspace-generator library

.deps/prod.md, packages/dashboard-backend/package.json, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.create.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, yarn.lock
Updates version of devworkspace generator tool to **0.0.1-638fadc**. 
This version should automatically add `routingClass:che` into DevWorkspaces:
```
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
name: spring-petclinic
spec:
started: true
routingClass: che
```
https://github.com/eclipse/che/issues/22149
A devWorkspace should contain `routingClass: che`
=> chore:update version of devworkspace generator tool

packages/dashboard-frontend/src/store/SanityCheck/index.ts
This PR fixes a small typo in the 'Backend is not available' warning message:
=> Fix backend not available typo

packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Cherry-picking changes from https://github.com/eclipse-che/che-dashboard/pull/798 to 7.64.x
=> fix:use correct key to get editor's attribute from the factory parameters

packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Fetch/Devfile/index.tsx
Avoid using the `Eclipse Che` name in the Unsupported git provider error message. Minor message fixups.
https://issues.redhat.com/browse/CRW-4357
1. Deploy che via the test image: `chectl server:deploy -p=minikube -i=quay.io/ivinokur/che-server:next`
For the testing purpose I disabled gitlab factory handler in the image.
2. Apply the dashboard changes.
3. Pass a gitlab public repo with a devfile to start a workspace e.g. `https://gitlab.com/ivinokur/test.git`
4. See the specific error:
=> Fix the Unsupported git provider error message

README.md, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Factory/Steps/Apply/Devfile/index.tsx
This PR fixes regression with name conflict while creating a new workspace.
fixes https://github.com/eclipse/che/issues/22210
1. Deploy Eclipse-CHE with an image from this PR.
2. Create a new workspace with a factory URL:
```<CHE>#https://gist.githubusercontent.com/olexii4/fc3b757806e660dee0fbe1bc131df3d1/raw/1fe83a212365f86b4571e7c04e1b8bb4e5a1cd91/unsupported_feature.yaml```.
3. Stop the created workspace.
4. Repeat STEP 2 one more time.
5. Two workspaces will be created.
=> fix: devfiles name conflict

packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/OpenWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/StartWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/containers/Loader/Workspace/Steps/StartWorkspace/index.tsx, packages/dashboard-frontend/src/services/helpers/getWorkspaceLogs.ts, run/build-and-patch.sh, run/local-run.sh
Show the detailed message of a startup timeout error.
fixes https://github.com/eclipse/che/issues/22208
1. Deploy Eclipse-CHE with an image from this PR.
2. Set the 'progressTimeout', e.g., "30s". The next script could be used for patching:
```
#!/bin/bash
set -e
PROGRESS_TIMEOUT="${PROGRESS_TIMEOUT:-30}"
CHE_NAMESPACE="${CHE_NAMESPACE:-eclipse-che}"
echo "Patching checluster with the new startTimeoutSeconds '${PROGRESS_TIMEOUT}'..."
CHE_NAMESPACE="${CHE_NAMESPACE:-eclipse-che}"
DASHBOARD_POD_NAME=$(kubectl get pods -n $CHE_NAMESPACE -o=custom-columns=:metadata.name | grep dashboard)
CHECLUSTER_CR_NAME=$(kubectl exec $DASHBOARD_POD_NAME -n $CHE_NAMESPACE -- printenv CHECLUSTER_CR_NAME)
kubectl patch -n "$CHE_NAMESPACE" "checluster/$CHECLUSTER_CR_NAME" --type=json -p="[{\"op\": …
```
=> Show the detailed message of a startup timeout error

packages/dashboard-backend/src/devworkspaceClient/services/podmanApi.ts
Linking mounted certificates from '/var/run/secrets/kubernetes.io/serviceaccount' to '/$HOME/.config/containers/certs.d' before podman login
https://github.com/eclipse/che/issues/22140
Install Eclipse Che and replace the dashboard image related to the PR
```
spec:
components:
dashboard:
deployment:
containers:
- image: quay.io/eclipse/che-dashboard:pr-851
```
Create an empty workspace, open the terminal, and execute `podman pull image-registry.openshift-image-registry.svc:5000/openshift/cli:latest`
N.B. symbolic links for `ca.crt` and `service-ca.crt` are in the  `$HOME/.config/containers/certs.d/image-registry.openshift-image-registry.svc:5000` folder
Related info - https://manpages.ubuntu.com/manpages/impish/man5/containers-certs.d.5.html
=> feat: linking mounted certificates from '/var/run/secrets/kubernetes.io/serviceaccount' to '/$HOME/.config/containers/certs.d' before podman login

packages/dashboard-frontend/src/containers/Loader/index.tsx
Bugfix: show the created workspace name on the startup page.
https://github.com/eclipse-che/che-dashboard/assets/16220722/089d58fd-744b-4dfc-8b58-9d7628f7e175
=> fix: show new workspace name on startup page

packages/dashboard-backend/src/constants/schemas.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
Fix creating a new workspace from the remote registry.
it needs for https://github.com/eclipse/che/issues/22326
1. Deploy Eclipse-CHE with an image from the current PR.
2. Update CR accordingly:
```
devfileRegistry:
disableInternalRegistry: true
externalDevfileRegistries:
- url: https://registry.devfile.io/
``` 
3. Open the 'Create Workspace' page.
4. Create a new workspace from the UDI sample.
=> fix: creating a new workspace from the remote registry

run/build-and-patch.sh, run/local-run.sh
=> fix: scripts for local run

packages/dashboard-frontend/src/services/registry/__tests__/devfiles.spec.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts
This PR fixed the index URL for external devfile registries.
1. Deploy Eclipse-CHE with an image from the current PR.
2. Update CR accordingly:
```
devfileRegistry:
disableInternalRegistry: true
externalDevfileRegistries:
- url: https://registry.devfile.io/
- url: https://eclipse-che.github.io/che-devfile-registry/7.71.0/
``` 
3. Open the 'Create Workspace' page.
=> Fix the index URL for external devfile registries

.ci/oci-dashboard-happy-path.sh
* Multiplies default identity provider installation timeout three times (300s -> 900s)
* Decreases check frequency to prevent console spam (10s -> 15s)
follow-up of https://github.com/eclipse-che/che-dashboard/pull/862
will be in the pipeline on this PR
N/A
N/A
=> Increate IdentityProvider set-up timeout, decrease check frequency

packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx
This PR restores showing workspace condition messages as starting steps.
Fixes regression in https://github.com/eclipse-che/che-dashboard/pull/878
=> fix: workspace condition messages

build/dockerfiles/brew.Dockerfile
Update the brew.Dockerfile to install nodejs 16 development module to get Red Hat supplied headers so node-gyp doesn't try to download them during the brew build.
https://issues.redhat.com/browse/CRW-4644
Created a test branch with these changes in pkgs.devel and started a brew build, which succeeded.
=> CRW-4644 Fix downstream brew build

.deps/prod.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/components/WorkspaceProgress/CommonSteps/CheckRunningWorkspacesLimit/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Resources/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/CheckExistingWorkspaces/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/CreateWorkspace/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Resources/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/ProgressStep.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/Initialize/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/StartWorkspace/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/WorkspaceConditions/index.tsx, packages/dashboard-frontend/src/inversify.config.ts, packages/dashboard-frontend/src/services/helpers/debounce.ts, yarn.lock
Factory flow code refactoring.
It needs for https://github.com/eclipse/che/issues/22228
=> fix: code refactoring

packages/dashboard-frontend/src/services/factory-location-adapter/__tests__/factoryLocationAdapter.spec.ts, packages/dashboard-frontend/src/services/factory-location-adapter/index.ts
Allow to input SSH url in the Bitbucket-server format: `ssh://git@bitbucket-server.com:7999/~user/repo.git`
https://github.com/eclipse/che/issues/22354
Paste `ssh://git@bitbucket-server.com:7999/~user/repo.git` to the `Git Repo URL` input in the `Create Workspace` tab
See validation is passed.
=> Extend the SSH validation pattern for the git URL input

packages/dashboard-frontend/src/store/FactoryResolver/__tests__/normalizeDevfileV2.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/normalizeDevfileV2.ts, run/prepare-local-run.sh
This PR fixed the ability to support a Devfile without metadata.
fixes https://github.com/eclipse/che/issues/22350
1. Deploy Eclipse-CHE with an image from the current PR.
2. Open the 'Create Workspace' page. Create a new workspace with URL ```{CHE-Server}#https://gist.githubusercontent.com/olexii4/fc3b757806e660dee0fbe1bc131df3d1/raw/f0d6fdddadf4c39073b30a958790ba8f40a33cf7/devfile.yaml```.
3. A new workspace should be created without any errors.
=> fix: support devfiles without metadata

packages/dashboard-frontend/webpack.config.common.js
This PR fixes the blank page issue when trying to open the Dashboard using the `<CHE-HOST>` URL.
fixes https://github.com/eclipse/che/issues/22476
fixes https://github.com/eclipse/che/issues/22478
=> fix: prevent preload page bundle from being split

packages/dashboard-frontend/src/Layout/Header/Tools/AboutMenu/Modal.tsx, packages/dashboard-frontend/src/Layout/Header/Tools/AboutMenu/index.tsx, packages/dashboard-frontend/src/Layout/Header/Tools/index.tsx
This PR fixes the Eclipse Che logo for the About modal window.
fixes https://github.com/eclipse/che/issues/22477
1. Deploy Eclipse CHE with an image from the current PR.
2. Added a logo as a base64 encoded image into Custom Resource.
```
spec:
components:
dashboard:
branding:
logo:
base64data: 'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGhlaWdodD0iNzBweCIgd2lkdGg9IjcwcHgiIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDQ3IDU3Ij4KICAgIDxnIGZpbGwtcnVsZT0iZXZlbm9kZCIgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiPgogICAgICAgIDxwYXRoIGQ9Ik0wLjAzMjIyNywzMC44OGwtMC4wMzIyMjctMTcuMDg3LDIzLjg1My0xMy43OTMsMjMuNzk2LDEzLjc4NC0xNC42OTEsOC41MS05LjA2Mi01LjEwOS0yMy44NjQsMTMuNjk1eiIKICAgICAgICAgICAgICBmaWxsPSIjZmRiOTQwIi8+CiAgICAgICAgPHBhdGggZD0iTTAsNDMuMzU1bDIzLjg3NiwxMy42MjIsMjMuOTc0LTEzLjkzN3Yt …
```
=> fix: logo for the About modal window

packages/dashboard-frontend/src/store/SanityCheck/index.ts
Add console error logging on `che-server` failure:
fixes https://github.com/eclipse/che/issues/22423
1. Deploy che from `quay.io/ivinokur/che-server:next` image (throws an error on token provisioning).
2. Add a PAT from the dashboard page
3. Refresh the page and see an error.
4. Open the browser console and see the original exception message and trace.
=> Add console logging che-server exception messages

packages/dashboard-backend/src/app.ts, packages/dashboard-backend/src/routes/api/gettingStartedSample.ts
This PR Fixes the GettingStarted samples route for local runs for dogfooding.
We faced an error during the start of local runs from the main branch with dogfooding instance.
1. Create a new workspace with `https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/#/load-factory?url=https://github.com/eclipse-che/che-dashboard/tree/quick_fixes`
2. Execute the command 
```
yarn install --non-interactive && yarn build && oc project dogfooding && export CHE_NAMESPACE='dogfooding' && export NAMESPACE='dogfooding' && yarn start:prepare && yarn start -c
```
3. Local runs should start without errors.
=> Fix the GettingStarted samples route

packages/dashboard-frontend/src/services/dashboard-backend-client/factoryResolverApi.ts
Remove the `try catch` wrap from the factory resolver request as the exception contains data with url to redirect to oauth page.
fixes https://github.com/eclipse/che/issues/22518
1. Setup GitHub oauth flow, [see](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/)
2. Start a factory from a GitHub repository
see: authentication page appears.
=> Do not wrap factory resolver rquest exception

make-release.sh
fix incorrect condition for bumping version - only bump "next-7.x.y" https://www.npmjs.com/package/@eclipse-che/che-devworkspace-generator?activeTab=versions for bugfix release branch, while main branch will always reference "next"
this way branch alings with following dependency version of of devworkpace generator:
- main branch -> "next" dwo generator
- "7.77.0" release tag --> "7.77.0" dwo generator
- "7.77 x" bugfix branch -> "next-7.77.x" dwo generator
=> fix: fix next version updating during release

packages/dashboard-frontend/src/services/factory-location-adapter/__tests__/factoryLocationAdapter.spec.ts, packages/dashboard-frontend/src/services/factory-location-adapter/index.ts
Fixes https://github.com/eclipse/che/issues/22530 by allowing redirect to workspace creation page when `window.location.hash` contains the following characters: `{`, `}`, and `,`.
See: https://github.com/eclipse-che/che-dashboard/blob/333d6cf1142994533f6eea7f0d7568e5e6f45245/packages/dashboard-frontend/src/preload/main.ts#L30-L35
https://github.com/eclipse/che/issues/22530
1. Deploy Eclipse Che, and set the following in the Che CR to test out this PR:
```
spec:
components:
dashboard:
deployment:
containers:
- image: quay.io/dkwon17/che-dashboard:fixRemotesUrlParam
```
2. Access the following url to start a new workspace:
```
{che-host}/#https://github.com/dkwon17/quarkus-api-example?remotes={https://github.com/che-incubator/quarkus-api-example}
```
and verify that the resulting dev …
=> fix: remotes url parameter in factory url

packages/common/src/index.ts, packages/dashboard-backend/src/constants/schemas.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/__tests__/kubeConfig.spec.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-backend/src/routes/api/kubeConfig.ts, packages/dashboard-frontend/src/services/backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/devWorkspaceSpecTemplates.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
chore: Mount kubeconfig into users containers
https://issues.redhat.com/browse/CRW-4332
Manual tests on OpenShift and Minikube clusters
N/A
=> chore: Mount kubeconfig into users containers

packages/common/src/index.ts, packages/dashboard-backend/src/constants/schemas.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/__tests__/kubeConfig.spec.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-backend/src/routes/api/kubeConfig.ts, packages/dashboard-frontend/src/services/backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/devWorkspaceSpecTemplates.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This reverts commit 2c0237c0473abe4816621f80069a64f9f144ea50.
Revert "chore: Mount kubeconfig into users containers (#950)"
=> Revert "chore: Mount kubeconfig into users containers (#950)"

scripts/container_tool.sh
This PR improves the script we use to build, run, or push images either with docker or podman, depending on which is available and running.
=> chore: improve available tool detection

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/serverConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-backend/src/routes/api/serverConfig.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/index.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Fix the ability to use an external plugin registry.
fixes https://github.com/eclipse/che/issues/22589 and https://issues.redhat.com/browse/CRW-4926
=> fix: external plugin registries attribute from CR

packages/dashboard-frontend/src/services/backend-client/__tests__/kubernetesNamespaceApi.spec.tsx, packages/dashboard-frontend/src/services/backend-client/axiosWrapper.ts, packages/dashboard-frontend/src/services/backend-client/kubernetesNamespaceApi.ts
Extension of https://github.com/eclipse-che/che-dashboard/pull/946 to cover the case where a 403 error happens for the `provision` request:
https://github.com/eclipse/che/issues/22352
The issue this PR aims to fix is difficult to reproduce. To test this PR, you can apply this patch:
```
diff --git a/packages/dashboard-backend/src/routes/api/helpers/getToken.ts b/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
index 59e8d76f..1d5fcbf8 100644
--- a/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
+++ b/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
@@ -17,9 +17,5 @@ import { createFastifyError } from '@/services/helpers';
const authorizationBearerPrefix = /^Bearer /;
export function getToken(request: FastifyRequest): string {
-  const authorization …
```
=> fix: retry request for '"system:anonymous" cannot get resource' error

packages/dashboard-frontend/src/services/backend-client/__tests__/kubernetesNamespaceApi.spec.tsx, packages/dashboard-frontend/src/services/backend-client/kubernetesNamespaceApi.ts
Backport change introduced in https://github.com/eclipse-che/che-dashboard/pull/955
=> [BACKPORT] fix: retry request for '"system:anonymous" cannot get resource' error #955

packages/dashboard-frontend/src/services/backend-client/__tests__/axiosWrapper.spec.ts, packages/dashboard-frontend/src/services/backend-client/axiosWrapper.ts
I noticed that the `Bearer Token Authorization is required` message exists in `err.response.data.message`, rather than `err.message`:
Related to 401/403 issues.
Random 401 issues can be simulated by adding this git patch to the dashboard:
```
diff --git a/packages/dashboard-backend/src/routes/api/helpers/getToken.ts b/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
index 59e8d76f..71a5dd62 100644
--- a/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
+++ b/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
@@ -18,6 +18,11 @@ const authorizationBearerPrefix = /^Bearer /;
export function getToken(request: FastifyRequest): string {
const authorization = request.headers?.authorization;
+
+  if (Math.random() < 0.4) {
+    throw …
```
=> fix: use 'errors.getMessage' to determine error message in AxiosWrapper

packages/dashboard-frontend/src/services/backend-client/__tests__/axiosWrapper.spec.ts, packages/dashboard-frontend/src/services/backend-client/axiosWrapper.ts
Backports the fix introduced in fix: use 'errors.getMessage' to determine error message in AxiosWrapper #958
=> [BACKPORT] fix: use 'errors.getMessage' to determine error message in AxiosWrapper #958

.deps/EXCLUDED/dev.md, .deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/services/assets/branding.ts, packages/dashboard-frontend/src/services/axios-wrapper/__tests__/axiosWrapper.spec.ts, packages/dashboard-frontend/src/services/axios-wrapper/axiosWrapper.ts, packages/dashboard-frontend/src/services/axios-wrapper/getAxiosInstance.ts, packages/dashboard-frontend/src/services/backend-client/devWorkspaceApi.ts, packages/dashboard-frontend/src/services/backend-client/devWorkspaceTemplateApi.ts, packages/dashboard-frontend/src/services/backend-client/eventsApi.ts, packages/dashboard-frontend/src/services/backend-client/gitConfigApi.ts, packages/dashboard-frontend/src/services/backend-client/kubernetesNamespaceApi.ts, packages/dashboard-frontend/src/services/backend-client/personalAccessTokenApi.ts, packages/dashboard-frontend/src/services/backend-client/podsApi.ts, packages/dashboard-frontend/src/services/backend-client/userProfileApi.ts, packages/dashboard-frontend/src/services/bootstrap/__tests__/index.spec.tsx, packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts, packages/dashboard-frontend/src/services/resource-fetcher/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/resource-fetcher/appendLink.ts, packages/dashboard-frontend/src/services/resource-fetcher/index.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/index.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, yarn.lock
This PR fixed the preload data service and added a test for all bootstrap requests.
fixes https://github.com/eclipse/che/issues/22479
=> fix: preload data service

packages/dashboard-frontend/src/store/SanityCheck/index.ts
This PR changes behavior in the case of a "401 Unauthorized" error: it will redirect to the sign-in page instead of a page refresh.
fixes https://issues.redhat.com/browse/CRW-4943
=> fix: namespace provision

packages/common/src/dto/api/index.ts, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/const.ts
Allow to configure 2 github providers simultaneously
https://issues.redhat.com/browse/CRW-4840
N/A
=> feat: Allow to configure 2 github providers simultaneously

packages/dashboard-frontend/src/Routes/index.tsx
Loads all dashboard UI chunks when accessing the dashboard. This will prevent the user from seeing this error: https://github.com/eclipse/che/issues/22230
When comparing to lazy loading, there is a 0.09mb of difference in terms of resource transfer size when loading: `{CHE-HOST}/dashboard/#/create-workspace`
Lazy loading (left):  3.04mb
No lazy loading (right): 3.15mb
https://github.com/eclipse/che/issues/22230
1. Go to `{CHE-HOST}/dashboard/#/create-workspace`
2. In a new tab, log out of the dashboard
3. Go back to the first tab (ie from step 1) and on the left-hand side, click, 'Workspaces'.
4. There should be no `Error: Loading CSS chunk (...) failed.` error 
[lazyload.webm](https://github.com/eclipse-che/che-dashboard/assets/83611742/5df0db01-a373-44a4-a000-47abe8fe9bce)
=> chore: load all dashboard-related chunks

packages/dashboard-frontend/src/services/registry/devfiles.ts, packages/dashboard-frontend/src/services/registry/fetchData.ts
Fix registry index location.
fixes https://github.com/eclipse/che/issues/22643
1. deploy Eclipse-CHE.
2. add the target external registry:
```yaml
devfileRegistry:
disableInternalRegistry: true
externalDevfileRegistries:
- url: https://eclipse-che.github.io/che-devfile-registry/7.74.0/
```
3. refresh samples page
=> fix: registry index location

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Do not set 'ephemeral' storage for the 'Safe' mode 
- https://github.com/eclipse/che/issues/22638
- https://issues.redhat.com/browse/CRW-4969 
- install Eclipse Che and patch the dashboard image 
```
spec:
components:
dashboard:
deployment:
containers:
- image: quay.io/eclipse/che-dashboard:pr-967
```
- Start an empty workspace
- Add a few files to the workspace and then add a devfile with an image that doesn't exist e.g.
```yaml
schemaVersion: 2.2.0
metadata:
name: devfile-with-typo
components:
- name: tools
container:
image: quay.io/does/not/exist
```
- Select restart from local Devfile
- Wait for an error message
- Click the "Restart with default devfile" button.
- Wait for the target workspace to restart and open IDE
- See that the devfile exist and the changes are not lost
N/A
N/A
=> fix: Do not set 'ephemeral' storage for the 'Safe' mode

packages/dashboard-backend/src/routes/__tests__/factoryAcceptanceRedirect.spec.ts, packages/dashboard-backend/src/routes/factoryAcceptanceRedirect.ts
Fix workspace URL parameters after the user accepts the OAuth authorization.
fixes https://issues.redhat.com/browse/CRW-4955
=> fix: workspace URL parameters after the user accepts the OAuth authorization

packages/dashboard-frontend/src/services/oauth/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/oauth/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
* If an unauthorised error occurs on workspace start, throw the error in order to prevent the workspace to start. 
* Do not display the authorisation error on workspace start as the page is reloaded to the SCM authorisation page.
https://issues.redhat.com/browse/CRW-4957
1. Deploy che from the `che-server` related PR image: `quay.io/eclipse/che-server:pr-597` see: https://github.com/eclipse-che/che-server/pull/597
2. Configure GitHub (or other) oAuth2 flow.
3. Start a workspace from the GitHub repository, accept the authorisation page.
4. Go to the GitHub settings and revoke the authorisation.
5. Remove the GitHub token in the user settings page.
6. Stop the workspace and start it again.
See: Authorisation appears and token secret is updated in the user namespace after accepting the …
=> Do not start a workspace on SCM unauthorised error

packages/dashboard-frontend/src/services/axios-wrapper/__tests__/axiosWrapper.spec.ts, packages/dashboard-frontend/src/services/axios-wrapper/axiosWrapper.ts
Tweaks the axiosWrapper retries functionality to have exponential retries with a base of 2, and an initial delay of 500ms. 
As a result, with 3 retries, the first retry has a delay of 500ms, second has a delay of 1000ms and third with 2000ms.
https://github.com/eclipse/che/issues/22652
To simulate 401 errors and test this PR, checkout the PR branch and apply this patch:
```
diff --git a/packages/dashboard-backend/src/routes/api/helpers/getToken.ts b/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
index 59e8d76f..cd44ec45 100644
--- a/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
+++ b/packages/dashboard-backend/src/routes/api/helpers/getToken.ts
@@ -18,6 +18,9 @@ const authorizationBearerPrefix = /^Bearer /;
export function getToken(request: FastifyRequest): …
```
=> feat: exponential retries for axiosWrapper

make-release.sh
Update make-release.sh to use gh instead of hub.
https://github.com/eclipse/che/issues/22646
=> Fix: switch from hub to gh for Che #22646

README.md, packages/common/src/helpers/sanitize.ts, packages/dashboard-frontend/src/services/backend-client/factoryApi.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
Decode spaces in factory url
https://github.com/eclipse/che/issues/22458
N/A
N/A
=> fix: Decode spaces in factory url

packages/dashboard-frontend/src/store/GitOauthConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/GitOauthConfig/index.ts
chore: show authorized git services based on existed OAuth token secrets
https://github.com/eclipse/che/issues/22631
https://github.com/eclipse-che/che-server/pull/608
=> chore: show authorized git services based on existed OAuth token secrets

packages/dashboard-frontend/src/services/oauth/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/oauth/index.ts
Do not throw exceptions other then unauthorised exception on token refresh request when starting a workspace.
https://issues.redhat.com/browse/CRW-5015
1. Make sure GitHub oauth is **NOT** configured
2. Start a workspace from a public GitHub repository.
3. Stop the workspace and start it again.
See: workspace starts without any issues.
=> Do not throw other then unauthorised error on token refresh

packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/const.ts
chore: Use https://bitbucket.org as default server endpoint url for PAT
https://issues.redhat.com/browse/CRW-5291
N/A
N/A
=> chore: Use https://bitbucket.org as default server endpoint url for PAT

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.managePvcStrategy.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
This PR fixes the workspace startup process to prevent the Dashboard from overwriting the DevWorkspace Operator Config attribute every time the workspace starts.
fixes https://github.com/eclipse/che/issues/22573
1. Create a DWOC object in your workspaces namespace:
```yaml
apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
name: custom-dwoc
namespace: <your-namespace>
config:
workspace:
persistUserHome:
enabled: true
```
2. Reference the DWOC from a devfile:
```diff
schemaVersion: 2.2.0
metadata:
name: my-app
+ attributes:
+   controller.devfile.io/devworkspace-config:
+     name: custom-dwoc
+     namespace: <your-namespace>
components:
```
3. Create the workspace and verify it has a correct reference to the DWOC specified:
```sh
$ kubectl get dw -o …
```
=> Prevent overwriting the DevWorkspace Operator Config by the Dashboard

packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/ProviderIcon/__tests__/__snapshots__/ProviderIcon.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/ProviderIcon/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/__tests__/__snapshots__/index.spec.tsx.snap
Fixing wording to 'Authorized' / 'Unauthorized' for the following placeholders which are considered misle:
https://github.com/eclipse/che/issues/22600
=> fix: Fixing wording for 'Authorized' / 'Unauthorized' placehoolders

packages/dashboard-frontend/src/services/axios-wrapper/getAxiosInstance.ts, packages/dashboard-frontend/src/store/SanityCheck/index.ts
Increase the timeout in order to not to repeat the `provisionKubernetesNamespace` requests when che-server executes the provision request lasts less then 15 sec.
https://issues.redhat.com/browse/CRW-5338
1. Deploy che with the custom image: quay.io/ivinokur/che-server:[CRW-5338](https://issues.redhat.com//browse/CRW-5338). A delay is added to the GitHub user request.
2. Add a GitHub PAT token via the dashboard user preferences page.
see: The token item loads for a while, but finally appears in the list.
=> increase the axios request timeout

packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Don't inject additional environment variables into each component in DevWorkspace.
We still adding ENVs into DevWorkspaceTemplate and when devworkspace-operator merges DevWorkspace and DevWorkspaceTemplate, it'll add ENVs from DWT to the main development container.
https://github.com/eclipse/che/issues/22614
It was tested on OS cluster with custom dashboard image: [quay.io/vsvydenk/che-dashboard:no-env2](url)
I've checked that an **original.devworkspace.yaml** doesn't contain additional ENV's but flattened.devworkspace.yaml does (they were added from the DevWorkspaceTemplate that defines the editor):
I see that ENV's are present in the main development container:
Also I've tried to restart the workspace using a local devfile.yaml and it works as well.
**For reviewers:**
- deploy Che and …
=> fix: don't inject ENVs into devworkspace

packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/TokenData/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/TokenData/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/TokenData/index.tsx
Hide the token input in the PAT popup with a password input type:
https://issues.redhat.com/browse/CRW-5335
Go to the **User Preferences** -> **Personal Access Tokens** tab and add a new token or edit existed.
See: the token input is hidden.
=> Change the token data input type to password in the add/edit PAT popup

packages/dashboard-frontend/src/services/bootstrap/__tests__/index.spec.tsx
=> Fix WS message tests

packages/dashboard-frontend/src/components/Workspace/Status/Indicator/__tests__/__snapshots__/Indicator.spec.tsx.snap, packages/dashboard-frontend/src/components/Workspace/Status/Indicator/index.tsx, packages/dashboard-frontend/src/components/Workspace/Status/Label/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/Workspace/Status/getStatusIcon.tsx
Adds `aria-label` attr with the workspace's current status to the workspace status icon.
https://github.com/eclipse/che/issues/22698
=> Changes to the workspace status indicator to fix the happy-path test

packages/dashboard-backend/src/app.ts, packages/dashboard-backend/src/constants/examples.ts, packages/dashboard-backend/src/constants/schemas.ts, packages/dashboard-backend/src/routes/api/__tests__/dataResolver.spec.ts, packages/dashboard-backend/src/routes/api/dataResolver.ts, packages/dashboard-frontend/src/__tests__/workspaceCreationTimeCheck.check.tsx, packages/dashboard-frontend/src/components/Workspace/Status/index.module.css, packages/dashboard-frontend/src/services/backend-client/__tests__/dataResolverApi.spec.ts, packages/dashboard-frontend/src/services/backend-client/dataResolverApi.ts, packages/dashboard-frontend/src/services/backend-client/yamlResolverApi.ts, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/registry/__tests__/devfiles.spec.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts, packages/dashboard-frontend/src/services/workspace-client/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/services/workspace-client/helpers.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/getEditor.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/index.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/index.ts
This PR fixed reading metadata from `registry.devfile.io` deployed on the cluster.
fixes https://github.com/eclipse/che/issues/22705
=> fix: read index from the remote registry

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspacePreferencesApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspacePreferencesApi.ts
Return an empty result instead of throwing an error, if an empty data is received from the `get workspace preferences` request.
fixes https://github.com/eclipse/che/issues/22721
1. Setup GitHub oauth config.
2. Start a workspace from the GitHub repository.
3. Open browser console.
4. Go to dashboard user preferences page -> Git Services.
See: no error is present in the browser console.
=> Do not throw an error on get workspace preferences request

packages/dashboard-frontend/src/services/axios-wrapper/getAxiosInstance.ts, packages/dashboard-frontend/src/store/SanityCheck/index.ts
=> [BACKPORT] increase the axios request timeout #999

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
This PR adds the attribute `controller.devfile.io/bootstrap-devworkspace: true` when Devfile resolution via API fails or is not supported. 
resolves https://github.com/eclipse/che/issues/22697
1. Deploy Eclipse Che and the dashboard image from this PR:
```sh
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/dashboard/deployment", "value": {containers: [{image: "quay.io/eclipse/che-dashboard:pr-1016", name: che-dashboard}]}}]"
```
2. Add your SSH keys to the Dashboard, and make sure the public one is uploaded to your Git provider.
3. Copy the git+SSH URL of your git repository, and create a new workspace using this URL.
4. The workspace should start successfully with the project cloned and the Devfile applied.
=> Add attribute controller.devfile.io/bootstrap-devworkspace: true when Devfile resolution via API fails or is not supported

packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/ProviderIcon/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/const.ts, packages/dashboard-frontend/src/store/GitOauthConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/GitOauthConfig/index.ts
Use includes filter to handle the bitbucket-server oauth 2 provider. The bitbucket server oauth2 provider name is 'bitbucket', but the corresponding 'skip oauth' item is 'bitbucket-server'.
https://github.com/eclipse/che/issues/22723
1. Deploy che from the che-server PR image: `quay.io/eclipse/che-server:pr-624`
2. Register Bitbucket Server oauth2 provider.
3. Start a workspace from the Bitbucket-Server repo
4. Reject the Bitbucket-Server authorisation page.
5. Go to `User Preferences` -> `Git Services` tab, see: the authorisation flag is set to `skip authorisation` warning.
6. Click the `three dot` icon of the Bitbucket item and clear the `skip authorisation` flag.
7. Delete the workspace and start the workspace from the Bitbucket-Server again, accept the authorisation page, see: the …
=> Align the git services skip-oauth flag with oauth-1 providers

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/serverConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/__tests__/serverConfig.spec.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-backend/src/routes/api/serverConfig.ts, packages/dashboard-frontend/src/Layout/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/Layout/__tests__/index.spec.tsx, packages/dashboard-frontend/src/Layout/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/StartWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/inversify.config.ts, packages/dashboard-frontend/src/services/bootstrap/__tests__/issuesReporter.spec.tsx, packages/dashboard-frontend/src/services/bootstrap/__tests__/namespaceProvisionWarnings.spec.tsx, packages/dashboard-frontend/src/services/bootstrap/__tests__/warningsReporter.spec.tsx, packages/dashboard-frontend/src/services/bootstrap/index.ts, packages/dashboard-frontend/src/services/bootstrap/issuesReporter.ts, packages/dashboard-frontend/src/services/bootstrap/namespaceProvisionWarnings.ts, packages/dashboard-frontend/src/services/bootstrap/warningsReporter.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/stubs.ts, packages/dashboard-frontend/src/store/ServerConfig/index.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/__mocks__/storeBuilder.ts
Add meaningful Dashboard warnings during the failures on namespace provisioning.
fixes https://github.com/eclipse/che/issues/22714
1. Deploy Eclipse Che and the dashboard image from this PR:
```sh
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/dashboard/deployment", "value": {containers: [{image: "quay.io/eclipse/che-dashboard:pr-1023", name: che-dashboard}]}}]"
```
2. Turn off auto-provision for namespaces:
```sh
kubectl patch -n eclipse-che checluster/eclipse-che  --type=json -p="[{\"op\": \"replace\", \"path\": \"/spec/devEnvironments/defaultNamespace/autoProvision\", \"value\": false}]"
```
3. Delete the existing namespace:
```sh
kubectl delete namespace admin-che
```
4. Relogin the Dashboard page and the next error …
=> Add meaningful Dashboard warnings during the failures on namespace provisioning

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx
Fix for https://github.com/eclipse-che/che-dashboard/pull/1016
Apply the attribute `controller.devfile.io/bootstrap-devworkspace: true` also when devfile resolution succeded but no devfile found.
https://github.com/eclipse/che/issues/22697
1. Deploy Eclipse Che and the dashboard image from this PR:
```sh
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/dashboard/deployment", "value": {containers: [{image: "quay.io/eclipse/che-dashboard:pr-1029", name: che-dashboard}]}}]"
```
2. Add your SSH keys to the Dashboard, and make sure the public one is uploaded to your Git provider.
3. Copy the git+SSH URL of your git repository, and create a new workspace using this URL.
4. The workspace should start successfully with the project …
=> fix: apply attribute to the default configuration devfile

packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Adds the `che.eclipse.org/che-editor` annotation on workspaces that use the default editor.
This annotation is required for defaultPlugin support.
Fixes https://github.com/eclipse/che/issues/22017
https://github.com/eclipse/che/issues/22017
1. Create a workspace by clicking the dashboard samples (use default editor)
2. After the workspace is created, run:
```
oc get dw <workspacename> -n <usernamespace> -o jsonpath='{.metadata.annotations.che\.eclipse\.org/che-editor}'
```
3. Verify that the command from step 2 returns: 
```
che-incubator/che-code/latest
```
4. Create a workspace using factory url: `<CHE-HOST>/#https://github.com/che-incubator/quarkus-api-example`
5. Repeat steps 2 and 3 with the new workspace.
=> Set che-editor annotation to devworkspace when using default editor

packages/dashboard-frontend/jest.config.js, packages/dashboard-frontend/src/components/TextFileUpload/Preview/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/TextFileUpload/Preview/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/TextFileUpload/Preview/index.tsx, packages/dashboard-frontend/src/components/TextFileUpload/__mocks__/index.tsx, packages/dashboard-frontend/src/components/TextFileUpload/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/TextFileUpload/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/TextFileUpload/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/index.tsx
This PR introduces the ability to copy-paste SSH keys.
https://github.com/eclipse-che/che-dashboard/assets/16220722/3a18db0a-1669-4760-a938-975be2cc107f
resolves https://github.com/eclipse/che/issues/22719
=> Allow to copy-paste SSH keys

packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR fixed the problem with the wrong editor annotation for custom editors. It happens when we try to create a new workspace from the git repository with the custom editor in the ```.che``` directory.
For example:
Create a new workspace with the custom editor from the next link
```bash
{CHE-server}#https://github.com/olexii4/web-java-spring-boot.git
```
Check created devworkspace attributes with **swagger**
```bash
{CHE-server}/dashboard/api/swagger
```
We can see the wrong annotation ```"che.eclipse.org/che-editor": "che-incubator/che-code/latest"``` for **che-idea**.
1. Deploy Eclipse-Che with the image from this PR:
<details>
<summary>kubectl patch command</summary>
```bash
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": …
```
=> Set the editor content as an editor ID for custom editors

yarn.lock
Recreating PR from origin.
https://github.com/eclipse-che/che-dashboard/pull/1040#pullrequestreview-1822837475
Reran yarn install to rebuilt the yarn.lock file to include latest devworkspace-generator release.
There are lint errors...
https://issues.redhat.com/browse/CRW-5452
Built build/dockerfiles/Dockerfile locally
=> Update che-devworkspace-generat in yarn.lock

packages/dashboard-frontend/src/services/backend-client/serverConfigApi.ts, packages/dashboard-frontend/src/services/bootstrap/__tests__/index.spec.tsx, packages/dashboard-frontend/src/store/ServerConfig/__tests__/index.spec.ts
This PR adds axios retry functionality to `/server-config` requests.
https://github.com/eclipse/che/issues/22641
This issue can be difficult to test in a real situation, but to quickly test the issue, you can:
1. Apply this patch:
<details><summary>Patch</summary>
```
diff --git a/packages/dashboard-backend/src/routes/api/serverConfig.ts b/packages/dashboard-backend/src/routes/api/serverConfig.ts
index b952336f..0a229cea 100644
--- a/packages/dashboard-backend/src/routes/api/serverConfig.ts
+++ b/packages/dashboard-backend/src/routes/api/serverConfig.ts
@@ -16,7 +16,7 @@ import { FastifyInstance } from 'fastify';
import { baseApiPath } from '@/constants/config';
import { getDevWorkspaceClient } from '@/routes/api/helpers/getDevWorkspaceClient';
import { getServiceAccountToken } from …
```
=> fix: add retries to server-config request

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Resources/index.tsx, packages/dashboard-frontend/src/preload/__tests__/main.spec.ts, packages/dashboard-frontend/src/services/helpers/factoryFlow/buildFactoryParams.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/editorImage.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-devfile-without-components.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-devworkspace-template-with-custom-image.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-devworkspace-template-without-components.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-devworkspace-template.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-editor-devfile-with-custom-image.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-editor-devfile.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/editorImage.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts, packages/dashboard-frontend/src/store/__mocks__/devWorkspaceBuilder.ts, yarn.lock
Add a new workspace creation URL parameter named ```editor-image```
fixes https://github.com/eclipse/che/issues/22733
1. Deploy Eclipse-Che with the image from this PR:
<details>
<summary>kubectl patch command</summary>
```bash
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/dashboard/deployment", "value": {containers: [{image: "quay.io/eclipse/che-dashboard:pr-1037", name: che-dashboard}]}}]"
```
</details>
2. Create a new workspace with the custom editor image from the next link
```bash
{CHE-server}#https://github.com/eclipse-che/che-dashboard&editor-image=quay.io/mloriedo/che-code:copilot-builtin
```
3. The new workspace should be created with the custom editor image ```quay.io/mloriedo/che-code:copilot-builtin```.
It …
=> Add a new workspace creation URL parameter

packages/dashboard-backend/src/localRun/hooks/stubCheServerOptionsRequests.ts, packages/dashboard-backend/src/localRun/routes/dexCallback.ts, packages/dashboard-backend/src/localRun/routes/signOut.ts, packages/dashboard-backend/src/routes/api/__tests__/dataResolver.spec.ts, packages/dashboard-backend/src/routes/api/dataResolver.ts, packages/dashboard-backend/src/routes/api/devworkspaceTemplates.ts, packages/dashboard-backend/src/routes/api/devworkspaces.ts, packages/dashboard-backend/src/routes/api/helpers/getCertificateAuthority.ts, packages/dashboard-backend/src/routes/api/kubeConfig.ts, packages/dashboard-backend/src/routes/api/personalAccessToken.ts, packages/dashboard-backend/src/routes/api/podmanLogin.ts, packages/dashboard-backend/src/routes/api/sshKeys.ts, packages/dashboard-backend/src/routes/api/workspacePreferences.ts, packages/dashboard-backend/src/routes/factoryAcceptanceRedirect.ts, packages/dashboard-backend/src/routes/workspaceRedirect.ts, packages/dashboard-backend/src/services/logWatcher/index.ts
Fix the error for data resolver API 'POST ${baseApiPath}/data/resolver'.
https://github.com/eclipse/che/issues/22814
2. Open Swagger in the new tab.
```{CHE-server}/dashboard/api/swagger```
3. Request data resolver with the next payload:
```json
{
"url": "{CHE-server}/dashboard/devfile-registry/devfiles/index.json"
}
```
The status code should be `200`.
4. Request data resolver with non-existence payload:
```json
{
"url": "{CHE-server}/dashboard/devfile-registry/devfiles/index111.json"
}
```
The status code should be `404`.
=> Fix data resolver API

packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-devworkspace-template-with-custom-image.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/fixtures/test-editor-devfile-with-custom-image.yaml, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/editorImage.ts
fix: update editor image method
fixes https://github.com/eclipse/che/issues/22733
2. Create a new workspace with the next link:
```bash
{CHE-server}#https://github.com/eclipse-che/che-dashboard?che-editor=che-incubator/che-idea/latest&editor-image=quay.io/che-incubator/che-pycharm:next
```
3. Open Swagger in the new tab.
```{CHE-server}/dashboard/api/swagger```
4. Request the list of templates.
5. The target devWorkspaceTemplate should have a container with  the name ```che-idea-injector``` and the  image ```quay.io/che-incubator/che-pycharm:next```:
```yaml
components:
- container:
command:
- "/projector/entrypoint-init-container.sh"
cpuLimit: 500m
cpuRequest: 30m
image: quay.io/che-incubator/che-pycharm:next
memoryLimit: 128Mi …
```
=> fix: update editor image method

.deps/dev.md, .deps/prod.md, yarn.lock
Fix missing new version of devworkspace-generator in yarn lock, which is needed for downstream dependency resolution
=> Fix yarn lock release

packages/dashboard-backend/src/routes/__tests__/factoryAcceptanceRedirect.spec.ts, packages/dashboard-backend/src/routes/factoryAcceptanceRedirect.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
This PR fixes a bug when some query parameters of the factory link were dropped after the authorization redirect so the dashboard could not find the repository URL to proceed with creating the workspace.
fixes https://github.com/eclipse/che/issues/22871
1. Setup [oauth2 for BitBucket Server](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-a-bitbucket-server/).
2. Start a repository from a private BitBucket Server repository with a valid devfile.
3. Consent for the BitBucket Server authorization request.
=> Fix workspace start from Bitbucket server repository with OAuth2

packages/dashboard-frontend/src/pages/UserPreferences/GitServicesTab/index.tsx
Add gitlab to the list of allowed to revoke oauth providers
**Do not merge** before https://github.com/eclipse-che/che-server/pull/667 is merged.
fixes https://github.com/eclipse/che/issues/22832
see https://github.com/eclipse-che/che-server/pull/667
=> Add gitlab to the list of allowed to revoke oauth providers

packages/dashboard-frontend/src/services/backend-client/__tests__/yamlResolverApi.spec.ts, packages/dashboard-frontend/src/services/backend-client/yamlResolverApi.ts, packages/dashboard-frontend/src/services/bootstrap/__tests__/index.spec.tsx, packages/dashboard-frontend/src/services/registry/__tests__/fetchData.spec.ts, packages/dashboard-frontend/src/services/registry/fetchData.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/getEditor.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/index.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/__tests__/index.spec.ts, packages/dashboard-frontend/src/store/Plugins/devWorkspacePlugins/index.ts
This PR fixes the CORS issue that prevents creating a new workspace with an editor devfile published on an external resource.
fixes https://github.com/eclipse/che/issues/22875
1. Deploy Eclipse Che, and patch `CheCluster` using the following command:
```sh
kubectl patch -n eclipse-che "checluster/eclipse-che" --type=json -p="[{"op": "replace", "path": "/spec/components/dashboard/deployment", "value": {containers: [{image: "quay.io/eclipse/che-dashboard:pr-1078", name: che-dashboard}]}}]"    ```
2. Open the User Dashboard
3. Create a new workspace from this link: https://github.com/redhat-developer-demos/ansible-devspaces-demo?che-editor=https://pr-check-1899-che-plugin-registry.surge.sh/v3/plugins/che-incubator/che-code/insiders/devfile.yaml
=> Fix cors issue when fetching editor devfile

packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx
Add gitlab to the list of allowed to revoke oauth providers
fixes https://github.com/eclipse/che/issues/22832
1. Configure [Gitlab oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-gitlab/).
2. Start a workspace from a Gitlab repository with a devfile, consent the authorisation agreement.
3. Go to User Preferences -> Git Services tab.
4. Revoke the Gitlab authorisation either by clicking the three dot button or selecting the provider icon and then clicking the `Revoke` red button.
See: the Gitlab authorisation is successfully revoked.
=> Add gitlab to the list of allowed to revoke providers

.gitignore, run/local-run.sh, run/prepare-local-run.sh
This PR restores the ability to create workspaces when the dashboard is running in the local development flow.
=> Fix workspaces creation in the local development flow

packages/dashboard-frontend/src/services/devfileApi/devWorkspace/metadata.ts, packages/dashboard-frontend/src/services/devfileApi/typeguards.ts
With this fix the dashboard can correctly process DevWorkspaces without `metadata.label`.
fixes https://github.com/eclipse/che/issues/22899
See "Steps to reproduce" [in the issue](https://github.com/eclipse/che/issues/22899).
=> Fix the blank page if DevWorkspace is missing controller.devfile.io/creator label

.github/workflows/codecov.yml, .github/workflows/pr.yml, .github/workflows/release.yml
Bump GitHub actions to use NodeJS v20.
=> chore: bump GH actions to use NodeJS 20

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/podmanApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/podmanApi.ts, run/prepare-local-run.sh
feat: podman login into external docker registries on workspace start
https://github.com/eclipse-che/che/issues/22863
1. Deploy Eclipse Che on OpenShift
2. Configure valid credentials for a registry, for instance docker.io
3. Configure invalid credentials for another registry, for instance for quay.io
4. Start a workspace
5. Check in the terminal the output
```bash
$ podman login docker.io
Authenticating with existing credentials for docker.io
Existing credentials are valid. Already logged in to docker.io
$ podman login quay.io
Username: ^Cprojects $ 
$ podman login image-registry.openshift-image-registry.svc:5000
Authenticating with existing credentials for image-registry.openshift-image-registry.svc:5000
Existing credentials are valid. Already logged in to …
```
=> feat: podman login into external docker registries on workspace start

packages/dashboard-backend/src/routes/factoryAcceptanceRedirect.ts, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/index.tsx, packages/dashboard-frontend/src/store/GitOauthConfig/index.ts
* Always decode url on factory url accept.
* Restore the skip oauth functionality.
see: https://github.com/eclipse-che/che-dashboard/pull/972
https://issues.redhat.com/browse/CRW-6245
1. Configure [GitHub oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/)
2. Start a workspace from a GitHub repository with devfile.
3. When the authorisation page appears, click the `Cancel` button.
4. Go back to Dashboard -> User Preferences ->  Git Services tab
5. See: a yellow warning sign is present in the GitHub item, click the kebab icon and then the `Clear` menu button.
6. See: the yellow sign is disappeared.
=> Restore the authorisation opt-out functionality

.github/workflows/codecov.yml
Fix the codecov job so now it uses the `CODECOV_TOKEN` and can upload coverage reports.
=> fix: codecov job

.deps/EXCLUDED/prod.md, .deps/prod.md, packages/dashboard-frontend/src/components/ImportFromGit/__tests__/helpers.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/helpers.ts, packages/dashboard-frontend/src/components/ImportFromGit/index.tsx
This PR fixed the getGitRepoOptionsFromLocation method.
fixes https://github.com/eclipse-che/che/issues/22949
3. Put `https://github.com/che-incubator/quarkus-api-example?df=smoke-test.devfile.yaml` factory into **Git repo URL**.
4. Click **Create & Open**.
5. The workspace should start without problems.
=> fix: getGitRepoOptionsFromLocation method

packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/StartWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/StartWorkspace/index.tsx
The dashboard will ignore workspace status changes (except `failed` and `terminating`) on workspace startup.
https://issues.redhat.com/browse/CRW-6287
https://issues.redhat.com/browse/CRW-6281
1. Install Dev Spaces 3.13.0
2. Patch the CheCluster CR to use this dashboard image: **quay.io/eclipse/che-dashboard:pr-1109**
3. Go to User Dashboard > Create workspace page
4. Click on the "Empty Workspace" tile to start the empty workspace
=> Fix workspace startup

.deps/EXCLUDED/prod.md, .deps/dev.md, .deps/prod.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/Layout/Navigation/RecentItem/TitleWithHover/index.tsx, packages/dashboard-frontend/src/Layout/Navigation/RecentItem/__tests__/index.spec.tsx, packages/dashboard-frontend/src/Layout/Navigation/RecentItem/index.tsx, packages/dashboard-frontend/src/Layout/Navigation/RecentList.tsx, packages/dashboard-frontend/src/Layout/Navigation/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Resources/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/index.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/Dropdown/__tests__/index.spec.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/Dropdown/index.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/Provider.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/__tests__/Provider.spec.tsx, packages/dashboard-frontend/src/inversify.config.ts, packages/dashboard-frontend/src/pages/WorkspacesList/Rows.tsx, packages/dashboard-frontend/src/pages/WorkspacesList/index.tsx, packages/dashboard-frontend/src/services/helpers/location.ts, packages/dashboard-frontend/src/services/tabManager/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/tabManager/index.ts, yarn.lock
When opening a workspace, the dashboard looks for an already open tab with the same workspace. If a tab exists, the dashboard focuses it without creating a new tab.
resolves https://github.com/eclipse-che/che/issues/22933
1. Create a new workspace, or open an existing one. A new browser tab should be created.
2. Go back to the dashboard tab, and
- click the same workspace in the Recent Workspaces section, or
- click "Open" on the same workspace in the workspaces list, or
- open the workspace actions menu for the same workspace, and click the "Open" item
3. The existing workspace tab should be focused.
=> Switch to existing tab with the same workspace

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/podmanApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/podmanApi.ts
fix: podman login into external registries
https://github.com/eclipse-che/che/issues/22987
Yes
=> fix: podman login into external registries

packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/StatusIcon/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/const.ts
Since che-server returns `bitbucket-server` for self-hosted Bitbucket authenticators, both oauth1 and oauth2, remove the includes filter.
see https://github.com/eclipse-che/che-dashboard/pull/1121
fixes https://github.com/eclipse-che/che/issues/22971
**DO NOT MERGE**:  depends on https://github.com/eclipse-che/che-server/pull/689
see https://github.com/eclipse-che/che/issues/22971
=> Align the oauth items filter with changes from server

packages/dashboard-backend/package.json
Update che-devworkspace generator dependency version
fixes https://github.com/eclipse-che/che/issues/22997
Try to start a workspace from a repository with a dvfile version `2.3.0`
See: workspace starts successfully.
=> Update che-devworkspace generator dependency version

packages/dashboard-backend/src/devworkspaceClient/__mocks__/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/editorsApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/editorsApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/__tests__/editors.spec.ts, packages/dashboard-backend/src/routes/api/editors.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-frontend/src/contexts/WorkspaceActions/BulkDeleteButton/__mocks__/index.tsx
This PR adds a new route exposed by the dashboard backend:
https://github.com/eclipse-che/che/issues/22994
When testing on Eclipse Che, access the following link and verify that the `che-code/latest` devfile is returned:
```
<CHE-HOST>/dashboard/api/editors/devfile?che-editor=che-incubator/che-code/latest
```
If no `che-editor` query param is provided, then there is a 400 error:
```
<CHE-HOST>/dashboard/api/editors/devfile?che-editor=che-incubator/che-code/latest
```
If there is not editor with id `che-editor`, there is a 404 error:
```
<CHE-HOST>/dashboard/api/editors/devfile?che-editor=doesnotexist
```
Additionally, create this following devworkspace and verify that the workspace starts and verify that you can access the editor:
```
kind: DevWorkspace
apiVersion: …
```
=> Implement editors/devfile route

packages/dashboard-frontend/src/contexts/WorkspaceActions/BulkDeleteButton/__mocks__/index.tsx, packages/dashboard-frontend/src/services/oauth/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/oauth/index.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
feat: Force refresh personal access token
https://github.com/eclipse-che/che/issues/23005
N/A
N/A
N/A
=> feat: Force refresh personal access token

packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/index.tsx
This PR fixes Git provider endpoint validation.
fixes https://github.com/eclipse-che/che/issues/23013
=> fix: Git provider endpoint validation

package.json, packages/dashboard-backend/package.json, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts
This PR has for goal to fix [this issue](https://github.com/eclipse-che/che/issues/22924).
The aforementioned issue present a situation where if the persist Home option is enabled in che's conf, the kubeconfig that should be in ~/.kube/config isn't updated any more with an up-to-date token. This situation hinder further work and prevent the monitoring extension in VsCode to work properly.
So, this PR patch the function that should inject into each container the Kubeconfig with:
- A check that will not inject the kubeconfig in the case where the user manually inject the kubeconfig 
- A fetch that will take the existing kubeconfig inside the container and try to merge it with the generated one. The merge is based on the name, if a block with the same name exist in the existing kubeconfig it …
=> fix: If persistHome is enabled, the token in .kube/config isn't renewed

.ci/openshift-ci/Dockerfile
* Replaces usage of http://mirrorlist.centos.org/ repo with http://vault.centos.org/ as http://mirrorlist.centos.org/ is now down that Centos 7 is EOL as of July 1st 2024.
* Without this fix, the Dockerfile fails to build on [Openshift CI](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/eclipse-che_che-dashboard/1144/pull-ci-eclipse-che-che-dashboard-main-v14-dashboard-happy-path/1809377858603192320) with the error:
```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error" 
```
* This is more of a temporary work-around as the issue probably should be fixed in the image being used: …
=> fix: stop using mirror.centos.org repo

packages/dashboard-frontend/src/services/factory-location-adapter/__tests__/factoryLocationAdapter.spec.ts, packages/dashboard-frontend/src/services/factory-location-adapter/index.ts
Add whitespace to the `isHttpLocation` check regex pattern.
https://issues.redhat.com/browse/CRW-6790
Try to start a workspace from a repository url with whitespace, e.g. `https://vinokurig@dev.azure.com/vinokurig/public/_git/re po`
=> Add whitespace to the is Http check regex pattern

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts
Fix an error made in #1141 (a copy and paste error), I forgot to remove the ```[ -f ${kubeConfigDirectory}/config ] ``` that check if the file exists, and the goal here was either to replace the 
https://github.com/eclipse-che/che/issues/22924
1. Fix test file to match the new form of the command
2. Build the image (podman build / podman push)
3. fix che cluster with the image and delete pod
4. Start a new workspace and check that it work
5. edit the current kubeconfig by adding random char in the middle of the token
6. Reload the IDE and check that the metrics doesn't show up
7. Reload workspaces
8. Check that the metrics show up
9.  Start an old workspace (fixed by removing the ssh key :D )  that wasn't showing metrics
10. See that the metrics are up
N/A
N/A
=> fix: remove check if the .kube/config exist and prevent replacing or reading it

.deps/EXCLUDED/dev.md, .deps/dev.md, .deps/prod.md, packages/common/package.json, packages/common/src/dto/api/index.ts, packages/dashboard-backend/package.json, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/editorsApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/editorsApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/serverConfigApi.ts, packages/dashboard-backend/src/devworkspaceClient/types/index.ts, packages/dashboard-backend/src/routes/api/helpers/__mocks__/getDevWorkspaceClient.ts, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/getGitRemotes.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/getProjectFromLocation.ts, packages/dashboard-frontend/src/services/devfileApi/devfile/index.ts, packages/dashboard-frontend/src/services/devfileApi/devfile/metadata.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/editorDefinitions.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/helpers.normalizeDevfileV2.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/helpers.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/editorImage.ts, yarn.lock
- Upgrade devfile/api to 2.3.0 version
- Upgrade devworkspace generator tool to 7.89.0-next-784dff2 
https://github.com/eclipse-che/che/issues/23041
- check Build PR check
- patch OS cluster with final image and try to start a workspace
=> chore: bump devfile/api to 2.3.0; bump devworkspace generator

packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/StartWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/StartWorkspace/index.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
- Removed the unwanted ability to overwrite a newer workspace status with an older one;
- Workspace startup page: Fixed status glitches during a workspace start.
https://issues.redhat.com/browse/CRW-6287
1. Deploy Che and patch the CR using the command from the github-actions bot.
2. Create and start workspaces. There should be no `Status changed unexpectedly to "Stopped"` warning message while the workspace continues to start.
=> workspace status flickering on startup

packages/dashboard-frontend/src/components/TextFileUpload/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/TextFileUpload/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPrivateKey/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPublicKey/index.tsx
This PR fixes an issue where the trailing newline was lost when copy-pasting SSH keys.
N/A
fixes https://github.com/eclipse-che/che/issues/23073
Based on https://github.com/eclipse-che/che/issues/23073#issue-2450713392:
1. [Generate an SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) locally
2. Go to Dashboard -> User Preferences -> SSH Keys
3. Click `Add SSH Key`
4. **IMPORTANT**: extract the content of the generated public and private keys and paste it manually to the inputs.
5. Save the key
6. Try to start a workspace from an ssh url e.g. `git@github.com:vinokurig/test.git`
7. When the workspace starts, the project should be cloned.
=> fix: check if ssh key has newline at the end

.deps/dev.md, .deps/prod.md, package.json, packages/dashboard-backend/package.json, packages/dashboard-frontend/webpack.config.common.js, yarn.lock
This PR upgrades the next libs:
- axios@1.7.1 -> axios@1.7.5
- webpack@5.91.0 -> webpack@5.94.0
fixes https://issues.redhat.com/browse/CRW-6929
=> fix: upgrade axios

build/dockerfiles/skaffold.Dockerfile, packages/dashboard-frontend/src/components/ImportFromGit/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/UntrustedSourceModal/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/UntrustedSourceModal/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Resources/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx, packages/dashboard-frontend/src/pages/Loader/index.tsx, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/selectors.ts
This PR fixes
- the behavior of the Untrusted Repository modal, so that it doesn't reappear for already trusted repositories (see "Bug # 1);
- when switching to either the Logs or Events tab during the workspace creation phase, and staying there for a while, then the warning about the limit of running workspaces appears (see "Bug # 2"). The workaround for this bug is to disable the Logs and Events tab until the workspace is fully created;
- do not show the Untrusted Repository modal when starting an existing workspaces;
- do not show the Untrusted Repository modal when creating a workspace from the sample project on the Getting Started page.
<details>
<Summary>Bug # 1</Summary>
https://github.com/user-attachments/assets/0f7653b6-a6cd-4edc-b043-e53c5e1faeca
</details>
<details> …
=> Do not show modal for trusted repositories

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/index.tsx, packages/dashboard-frontend/src/services/helpers/factoryFlow/buildFactoryParams.ts
Throw an error on workspace start if ssl_exception error received
https://issues.redhat.com/browse/CRW-6940
see https://github.com/eclipse-che/che-server/pull/710
=> Throw an error on workspace start if ssl_exception error received

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/sshKeysApi/__tests__/helpers.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/sshKeysApi/helpers.ts, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPassphrase/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPassphrase/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/SshPassphrase/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/SshKeys/AddModal/Form/index.tsx
**DO NOT MERGE**
* Add a new input for `passphrase` value to the add SSH key dialog:
* Propagate the new `passphrase` value to the ssh key secret.
https://issues.redhat.com/browse/CRW-6614
1. Go to User Preferences -> Ssh Keys tab
2. Fill the public and private key inputs, enter some value to the `passphrase` input.
3. Save the key and get the `git-ssh-key` secret data.
See: the `passphrase` field is present in the data map and its value equals to the input.
=> Add passphrase input to the add SSH key dialog

packages/dashboard-frontend/src/components/WorkspaceProgress/__tests__/utils.spec.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/utils.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
Remove conditions before restart a workspace
https://issues.redhat.com/browse/CRW-6587
3. Put `https://raw.githubusercontent.com/dmytro-ndp/devfile-with-typo/main/devfile.yaml` factory into **Git repo URL**.
4. Click **Create & Open**.
5. The workspace should fails with an error **ImagePullBackOff**.
6. Open a new tab with the swagger link `{CHE-Server}/dashboard/api/swagger`.
7.  And apply the patch to fix the target devvorkspace:
```
[
{
"op": "replace",
"path": "/spec/template/components/0/container/image",
"value": "quay.io/devfile/universal-developer-image:ubi8-latest"
}
]
```
8. Open **Starting workspace** page and click **Restart**
9. The target workspace should restart without …
=> Remove conditions before restart a workspace

.github/workflows/release.yml, make-release.sh
Add more fixes to release process:
- no-immutable is required, becase yarn lock file can be modified with new che/devfile dependencies
=> fix: fix release process

packages/dashboard-backend/src/devworkspaceClient/services/gitConfigApi/__tests__/index.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/gitConfigApi/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/helpers/prepareCoreV1API.ts, packages/dashboard-frontend/src/pages/UserPreferences/GitConfig/Form/SectionUser/Email/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/pages/UserPreferences/GitConfig/Form/SectionUser/Email/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitConfig/Form/SectionUser/Email/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitConfig/Form/SectionUser/Name/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitConfig/Form/SectionUser/Name/index.tsx
If it does not exist, the Dashboard creates a `workspace-userdata-gitconfig-configmap` Configmap with a data section like this
```yaml
data:
gitconfig: |
[user]
name=""
email=""
```
This will allow users to edit this Git configuration, or import the entire `.gitconfig` file.
https://github.com/user-attachments/assets/02a3423a-e537-4063-abc4-d5ac7155dc95
resolves https://github.com/eclipse-che/che/issues/23147
See screencast section
=> feat: add ability to edit/import gitconfig when no configmap exists

packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/StartingSteps/OpenWorkspace/index.tsx
These changes fixed problems with a workspace status which may flicker from starting to running and back to starting.
A special rule was added and a timer will be restarted each time when the workspace status flicks from starting to running.
fixes https://github.com/eclipse-che/che/issues/23159
See **Steps to reproduce**  from https://github.com/eclipse-che/che/issues/23159
=> fix: Unexpected error message No IDE URL after 20 sec during workspace startup

packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx, packages/dashboard-frontend/src/store/Plugins/chePlugins/__tests__/helpers.convertToEditorPlugin.spec.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/helpers.ts, packages/dashboard-frontend/src/store/Plugins/chePlugins/index.ts
Fix hasTechPreviewTag filter.
fixes https://github.com/eclipse-che/che/issues/23161
3. Open **Editor Selector/Choose an Editor**.
4. Choose **insiders** tag for **VS Code**.
5. All editors should have a **Tech Preview** label.
=> fix: hasTechPreviewTag filter

scripts/yarn/old_version/yarn.lock
Update the v1 version of the yarn.lock file so the downstream build gets the right devworkspace generator version.
=> Update the v1 version of the yarn.lock file

packages/dashboard-frontend/src/components/UntrustedSourceModal/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Initialize/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/index.tsx, packages/dashboard-frontend/src/store/Workspaces/Preferences/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/Workspaces/Preferences/helpers.ts, packages/dashboard-frontend/src/store/Workspaces/Preferences/selectors.ts
This PR fixes a bug that blocks the creation of workspaces using a factory link to an untrusted repository.
<details><summary>Before</summary>
<p>
https://github.com/user-attachments/assets/d5aa3f73-3f29-41bf-88c4-9029daa0ed94
</p>
</details> 
<details><summary>After</summary>
<p>
https://github.com/user-attachments/assets/6aad08d1-bfc8-4798-9b39-5f049d7afdc8
</p>
</details> 
fixes https://github.com/eclipse-che/che/issues/23146
See the screencast above.
=> fix: factory URL flow with untrusted repository

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/routes/api/devworkspaceResources.ts, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/AdvancedOptions/CreateNewIfExistingField/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/AdvancedOptions/TemporaryStorageField/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/AdvancedOptions/TemporaryStorageField/index.tsx, packages/dashboard-frontend/src/services/workspace-client/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/services/workspace-client/helpers.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/index.ts
This PR changes the temporary storage component **id** to prevent showing several components on the page with the same **id**.
fixes https://github.com/eclipse-che/che/issues/23181
3. Put a valid URL into the **Git repo URL** field.
4. Try to switch temporary storage for samples.
5. The temporary storage switch works as expected.
=> fix: TemporaryStorageField widget

packages/dashboard-frontend/src/services/oauth/index.ts
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1217
=> Check for git remotes

packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx
Add the `Deprecated` tag to the editor definition.
fixes https://github.com/eclipse-che/che/issues/23172
3. Open **Editor Selector**/**Choose an Editor**
4. **IntelliJ IDEA Community** editor should have a `Deprecated` tag.
=> feat: add the 'Deprecated' tag to the editor definition

packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx
* feat: add the 'Deprecated' tag to the editor definition
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1224 to the 7.92.x branch
=> [cherry-pick] feat: add the 'Deprecated' tag to the editor definition (#1224)

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json, scripts/yarn/old_version/.deps/EXCLUDED/prod.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
This PR upgrades the **jsonpath-plus** to v10.0.1
=> chore: upgrade jsonpath-plus to 10.0.1

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json, scripts/yarn/old_version/.deps/EXCLUDED/prod.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
This PR upgrades the **jsonpath-plus** to v10.0.6
=> chore: upgrade jsonpath-plus to 10.0.6

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json, scripts/yarn/old_version/.deps/EXCLUDED/prod.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1230 to the 7.92.x branch
=> [cherry-pick] chore: upgrade jsonpath-plus to 10.0.6

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json, scripts/yarn/old_version/.deps/EXCLUDED/prod.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
This PR is a cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1234 to the 7.92.x branch
=> [cherry-pick] chore: upgrade jsonpath-plus to 10.1.0

.deps/EXCLUDED/prod.md, .deps/prod.md, package.json, scripts/yarn/old_version/.deps/EXCLUDED/prod.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
This PR upgrades the **jsonpath-plus** to v10.1.0
=> chore: upgrade jsonpath-plus to 10.1.0

packages/common/src/dto/api/index.ts, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/GitServices/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/const.ts
Allow to configure 2 gitlab providers simultaneously
https://issues.redhat.com/browse/CRW-7142
see https://github.com/eclipse-che/che-server/pull/731
=> feat: Allow to configure 2 gitlab providers simultaneously

.deps/EXCLUDED/prod.md, packages/dashboard-frontend/jest.setup.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.module.css, packages/dashboard-frontend/src/components/EditorSelector/Gallery/Entry/index.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/EditorSelector/Gallery/index.tsx, scripts/yarn/old_version/.deps/EXCLUDED/prod.md
This PR fixes UI for **Editor Selector** cards:
- align the editor provider text (Provided by ...) to the same line - bottom of tile
- clicking on the links (Jet Brains, License) will open a page in a new browser's tab
- editor dropdown will show the deprecated ones at the end of the list
fixes https://github.com/eclipse-che/che/issues/23222
2. Open **Create Workspace** page on the dashboard and  **Choose an EDitor**.
3. Check on the editor provider text (**Provided by** ...) in the bottom.
4. Click on the links (**Jet Brains, License**) should open a page in a new browser's tab.
=> Fix editor selector cards

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
Revert the condition that does not allow to resolve devfile for SSH factory urls.
fixes https://github.com/eclipse-che/che/issues/23236
1. In a remote Git repository create a custom `devfile.yaml` file.
2. Add SSH key: `User Preferences` -> `SSH keys`.
2. Start workspace from SSH url of the repository.
See: The workspace starts and the custom devfile is applied.
=> Do not skip SSH urls from resolving devfile and other che files

packages/dashboard-backend/src/routes/api/devworkspaceResources.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
Revert the condition that does not allow to resolve devfile for SSH factory urls.
Cherry pick from https://github.com/eclipse-che/che-dashboard/pull/1252
=> Do not skip SSH urls from resolving devfile (#1252)

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts
If the devfile resolve request fails with the devfile not found error, check if the url is an SSH url. If so, interrupt the workspace start with a new warning that describes the problem of the devfile resolve via a private repository SSH url.
https://issues.redhat.com/browse/CRW-7624
1. Add SSH keys to the user namespace: `User Preferences` -> `SSH Keys`
2. Start a workspace from an SSH url of a private repository.
See: the workspace start interrupts with the warning:
A new documentation link is added to the warning.
=> Improve the Devfile is not reachable warning for SSH urls

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts
If the devfile resolve request fails with the devfile not found error, check if the url is an SSH url. If so, interrupt the workspace start with a new warning that describes the problem of the devfile resolve via a private repository SSH url.
cherry pick from https://github.com/eclipse-che/che-dashboard/pull/1259
=> Improve the Devfile is not reachable warning for SSH urls (#1259)

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
Add missing ssh patterns to the SSH url check, see https://git-scm.com/docs/git-clone#_git_urls
fixes https://github.com/eclipse-che/che/issues/23268
1. Apply the pull request image: `quay.io/eclipse/che-dashboard:pr-1268`
2. Add an SSH key to the user namespace and to a bitbucket server instance.
3. Start a workspace from an SSH url of a private bitbucket server repository.
See: workspace start interrupts with the specific message:
=> Extend the ssh url pattern check

packages/common/src/dto/api/index.ts, packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/__tests__/helpers.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/personalAccessTokenApi/helpers.ts, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/DeleteModal/__tests__/stub.ts, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/List/index.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/__tests__/stub.ts, packages/dashboard-frontend/src/store/GitOauthConfig/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/GitOauthConfig/actions.ts, packages/dashboard-frontend/src/store/PersonalAccessTokens/__tests__/stub.ts
Add `isOauth` boolean parameter to the `PersonalAccessToken` type to be able to filter tokens that was generated from oAuth. The `tokenName` parameter does not work for this case, because it is set from the original kubernetes secret object name, but not from the `che.eclipse.org/scm-personal-access-token-name` label.
fixes https://github.com/eclipse-che/che/issues/23241
1. Deploy the dashboard pull request image: `quay.io/eclipse/che-dashboard:pr-1269`
2. Configure [GitHub oauth](https://eclipse.dev/che/docs/stable/administration-guide/configuring-oauth-2-for-github/), but do not authenticate it.
3. Go to the dashboard `User Preferences` -> `Personal Access Tokens` tab and add a GitHub PAT.
4. Go to the `User Preferences` -> `Git Services` tab and see that the GitHub authorisation is …
=> Add isOauth boolean parameter to the PersonalAccessToken type

.deps/EXCLUDED/prod.md, .deps/prod.md, packages/common/package.json, packages/dashboard-backend/jest.config.js, packages/dashboard-backend/package.json, packages/dashboard-backend/src/constants/devfile.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspaceApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspaceClusterApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/devWorkspaceTemplateApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceApi.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceClusterApiService.ts, packages/dashboard-backend/src/devworkspaceClient/services/devWorkspaceTemplateApi.ts, packages/dashboard-backend/src/routes/api/devworkspaceResources.ts, packages/dashboard-backend/webpack.config.common.js, packages/dashboard-frontend/package.json, scripts/yarn/old_version/.deps/EXCLUDED/prod.md, yarn.lock
Upgrade @eclipse-che/che-devworkspace-generator and @devfile/api.
fixes https://github.com/eclipse-che/che/issues/23288, https://github.com/eclipse-che/che/issues/23201
=> Upgrade @eclipse-che/che-devworkspace-generator and @devfile/api

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/fixtures/kubeconfig.yaml, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/helpers/exec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts
1. Change the parse format from JSON to YAML as the default format of the `oc` and `kubectl` tools is YAML.
2. Do not substring new line when fetching the kubeconfig file content.
fixes https://github.com/eclipse-che/che/issues/23238
1. Deploy Che with the dashboard pull request image: `quay.io/eclipse/che-dashboard:pr-1279`
2. Apply [Persistent user home](https://eclipse.dev/che/docs/stable/administration-guide/about-persistent-user-home/).
3. Start a workspace, open the `/home/user/.kube/config` file, see that the content is YAML.
4. Open a new terminal and oc login to a kubernetes cluster.
5. Restart the workspace, execute `oc whoami` from the terminal.
See: the oc command works, the kubeconfig file is valid.
=> Fix the bug when kubeconfig file content is collapsed to one line after workspace restart

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx
Remove the `Devfile resolve from a privatre repositry via an SSH url is not supported` warning and start workspace from the default devfile in this case.
https://github.com/eclipse-che/che/issues/23277
1. Apply the `che-dashboard` pull request image: `quay.io/eclipse/che-dashboard:pr-1286`
2. Add an SSH key via the user preferences page.
3. Start a workspace from a private repository with a devfile, using SSH url.
See: workspace starts without interruption, local devfile is applied.
=> Start workspace from default devfile on private repository SSH url

packages/dashboard-frontend/src/pages/UserPreferences/GitServices/List/index.tsx
This PR fixes the Git Services page with the list of the available Git providers.
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1265 to the 7.95.x branch
It needs for https://issues.redhat.com/browse/CRW-7573
See `Steps to reproduce` at https://github.com/eclipse-che/che/issues/23262
=> [cherry-pick] fix: git services page (#1265)

build/dockerfiles/Dockerfile, scripts/airgap.sh
Uses `git clone`  to get airgap samples instead of `curl` with GH token
https://issues.redhat.com/browse/CRW-7938
1. It could be tested by adding samples into packages/devfile-registry/air-gap/index.json
<details>
<summary>index.json</summary>
```json
[
{
"id": "php",
"displayName": "PHP",
"description": "PHP Stack with PHP",
"tags": [
"Tech-Preview",
"PHP",
"UBI8"
],
"url": "https://github.com/devspaces-samples/php-hello-world/tree/devspaces-3.17-rhel-8",
"icon": {
"mediatype": "image/svg+xml",
"base64data": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhLS0KCiAgICBDb3B5cmlnaHQgKGMpIDIwMTgtMjAyMSBSZWQgSGF0LCBJbmMuCiAgICBBbGwgcmlnaHRzIHJlc2VydmVkLiBUaGlzIHByb2dyYW0gYW5kIHRoZSBhY2NvbXBhbnlpbmcgbWF0ZXJpYWxzCiAgICBhcmUgbWFkZSBhdmFpbGFibGUgdW5kZXIgdGhlIHRlcm1zIG9m …
```
=> chore: use git clone instead of curl to get airgap samples

packages/dashboard-frontend/src/services/bootstrap/branding.constant.ts, packages/dashboard-frontend/src/store/Branding/actions.ts
This PR fixes the branding data merge.
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1297 to the 7.95.x branch
fixes  https://issues.redhat.com/browse/CRW-7935
=> fix: branding data merge

build/dockerfiles/Dockerfile, scripts/airgap.sh
**Cherry-pick into 7.95.x**
Uses `git clone`  to get airgap samples instead of `curl` with GH token
https://issues.redhat.com/browse/CRW-7938
1. It could be tested by adding samples into packages/devfile-registry/air-gap/index.json
<details>
<summary>index.json</summary>
```json
[
{
"id": "php",
"displayName": "PHP",
"description": "PHP Stack with PHP",
"tags": [
"Tech-Preview",
"PHP",
"UBI8"
],
"url": "https://github.com/devspaces-samples/php-hello-world/tree/devspaces-3.17-rhel-8",
"icon": {
"mediatype": "image/svg+xml",
"base64data": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhLS0KCiAgICBDb3B5cmlnaHQgKGMpIDIwMTgtMjAyMSBSZWQgSGF0LCBJbmMuCiAgICBBbGwgcmlnaHRzIHJlc2VydmVkLiBUaGlzIHByb2dyYW0gYW5kIHRoZSBhY2NvbXBhbnlpbmcgbWF0ZXJpYWxzCiAgICBhcmUgbWFkZSBhdmFpbGFi …
```
=> [cherry-pick]chore: use git clone instead of curl to get airgap samples

run/local-run.sh
Update the script to ensure it runs correctly in a local environment.
https://issues.redhat.com/browse/CRW-7938
Try to execute local-run.sh script
N/A
N/A
=> fix: use absolute path in local-run script to get air-gap samples

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/__tests__/startWorkspace.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/const.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/startWorkspace.ts
Do not dispatch a warning, if the git provider is not supported.
fixes https://github.com/eclipse-che/che/issues/23304
1. Deploy Che with the pull request image: `quay.io/eclipse/che-dashboard:pr-1306`
2. Start a workspace from an unsupported git provider repository e.g `https://gitea.com/ivinokur/test.git`
See workspace starts from the default devfile without any warnings.
=> Do not dispatch a warning, if the git provider is not supported

.deps/dev.md, packages/dashboard-frontend/package.json, packages/dashboard-frontend/src/components/BasicViewer/index.tsx, packages/dashboard-frontend/src/components/DevfileViewer/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/DevfileEditorTab/index.tsx, packages/dashboard-frontend/src/pages/WorkspaceDetails/index.tsx, packages/dashboard-frontend/src/services/backend-client/websocketClient/__tests__/index.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/helpers.ts, scripts/yarn/old_version/.deps/dev.md, scripts/yarn/old_version/.deps/prod.md, scripts/yarn/old_version/yarn.lock, yarn.lock
Reworked the **Devfile Viewer** widget. This solution does not change the final package size of 1.91 MB.
fixes https://github.com/eclipse-che/che/issues/23324
2. Create a new workspace from the source:
```
https://gist.githubusercontent.com/olexii4/dfb21012e08eedf8fc17ae608708fe87/raw/bec54efa905b915695dcb7fc5806cb4b456aa343/devfile.yaml
```
3. Open **Workspace Detail** / **Devfile** page and **Devfile Viewer** styles should be correct:
=> Fix DevfileViewer widget

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/devWorkspaceSpecTemplates.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/__mocks__/editorDefinitions.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.editorUpdate.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/getEditor.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/const.ts, packages/dashboard-frontend/src/store/DevfileRegistries/getEditor.ts
This PR fixes the editor update flow and changes the approach of how to store `editorYamlUrl` variable in the `devworkspace.metadata.annotations[REGISTRY_URL]`. 
The existing implementation allows using **editorId** instead of **URL**.
With these changes, a correct API request `http://127.0.0.1:8080/dashboard/api/editors/devfile?che-editor=${editorId}` will be stored instead of an **editorID**.
fixes https://issues.redhat.com/browse/CRW-7936
1. Deploy **Eclipse-Che** with the image from this **PR**.
2. Create a new workspace from the source:
```
https://github.com/eclipse-che/che-dashboard.git
```
3. Stop the workspace. Open **Swagger**: ```{che-server}/dashboard/api/swagger```.
Use **Devworkspace Template** API and find the **templateName**.
4. Modify(remove field `/spec/commands`) the …
=> Fix editor update flow

packages/dashboard-frontend/src/components/ImportFromGit/__tests__/__snapshots__/index.spec.tsx.snap, packages/dashboard-frontend/src/components/ImportFromGit/index.tsx
This PR changes the verbiage of the helper text under the Import from Git text box.
If you have more than zero workspaces, the verbiage doesn't make sense.
I ran the tests from the devfile command.
Verbiage update on Create Workspace page.
N/A
=> Fix Change of verbiage to helper text under the 'Import from Git' text box.

packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/prepareDevfile.spec.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/prepareDevfile.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Fetch/Devfile/index.tsx, packages/dashboard-frontend/src/services/devfile/adapter.ts
This PR fixes factory flow with a devfile that uses a parent.
fixes https://github.com/eclipse-che/che/issues/23353
2. Try to create a new workspace from the **Git repo URL**:
```
https://github.com/testsfactory/parentDevfile.git
```
3. The target workspace should be created successfully.
=> fix: factory flow with a devfile that uses a parent

packages/dashboard-frontend/src/services/registry/__tests__/devfiles.spec.ts, packages/dashboard-frontend/src/services/registry/devfiles.ts
Gets **devfiles** from the `/index/all` route for external registries.
fixes https://github.com/eclipse-che/che/issues/23352
- Deploy Che with the dashboard pull request image: `quay.io/eclipse/che-dashboard:pr-1325`.
- Open `Create-workspace` page.
- Open console on Chrome. Remove 'external-registries' item from session storage with the command: `sessionStorage.removeItem('external-registries')` and reload the page.
- Found `{che-server}/dashboard/api/data/resolver` request with params:
`{url: "https://registry.devfile.io/index/all"}`.
=> Fix devfile.io index route

packages/dashboard-backend/src/routes/api/__tests__/clusterInfo.spec.ts, packages/dashboard-backend/src/routes/api/clusterInfo.ts
Fix default OpenShift console logo.
`/static/assets/redhat.svg` -> `/static/assets/public/imgs/openshift-favicon.png`
fixes https://github.com/eclipse-che/che/issues/23389
=> fix: default OpenShift console logo

packages/dashboard-backend/src/routes/api/__tests__/clusterInfo.spec.ts, packages/dashboard-backend/src/routes/api/clusterInfo.ts
This PR fixes the default OpenShift console logo: 
`/static/assets/redhat.svg` -> `/static/assets/public/imgs/openshift-favicon.png`
cherry-pick of https://github.com/eclipse-che/che-dashboard/pull/1330 to the 7.100.x branch
=> [cherry-pick] fix: default OpenShift console logo (#1330)

packages/dashboard-frontend/src/contexts/WorkspaceActions/DeleteWarning/__tests__/index.spec.tsx, packages/dashboard-frontend/src/contexts/WorkspaceActions/DeleteWarning/index.tsx
Fix styles for delete workspace warning messages. 
Before:
After:
- deploy Che
- configure CheCluster to run more one workspace
```
spec:
devEnvironments:
maxNumberOfRunningWorkspacesPerUser: 10000
```
- run two workspaces from Dashbord samples
- try to delete a workspace
=> fix: warning message styles

packages/dashboard-frontend/src/components/ImportFromGit/__tests__/helpers.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/helpers.ts
Support Gitlab repository urls with multiple subgroups when handling branch name from Git Repo Options menu.
https://issues.redhat.com/browse/CRW-8615
1. Apply the pull request image: `quay.io/eclipse/che-dashboard:pr-1342`.
2. Go to `Create Workspace` -> `Import from Git` and input a Gitlab repository url with multiple groups, e.g. `https://gitlab.com/group422630/subgroup/test.git`.
3. Set a non default branch In the `Git Repo Options` menu, e.g. `newbranch`.
4. Click the `Create & Open` button.
See: workspace starts and the project is checkouted to the specified branch.
=> Fix set branch function for Gitlab repositories with subgroups

packages/dashboard-frontend/src/store/DevfileRegistries/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/DevfileRegistries/selectors.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/__tests__/selectors.spec.ts, packages/dashboard-frontend/src/store/ServerConfig/helpers.ts, packages/dashboard-frontend/src/store/ServerConfig/selectors.ts
This PR fixes restart from default devfile flow. 
fixes https://issues.redhat.com/browse/CRW-8865
- Use dashboard image from this PR: quay.io/eclipse/che-dashboard:pr-1344
- Make sure that your CheCluster is set to a storage strategy of `per-workspace`.
- Create a workspace using `https://github.com/cgruver/test-workspace/tree/pvc-fail`
- Create a new file in the project folder.
- Modify the devfile to point to a bad image location - change the tag to badimage
- Restart from local DevFile
- Observe the failure.
- Choose to restart from the default devfile.
- The workspace will restart.
- Check that, as a result, the workspace was restarted with per-workspace storage type, and the file exists in the project
=> fix: selectDefaultDevfile method

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/fixtures/merged_kubeconfig.yaml, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/fixtures/mounted_kubeconfig.yaml, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts
Preserve the current context from the generated kubeconfig
N/A
https://issues.redhat.com/browse/CRW-8879
1. Deploy Eclipse Che
2. Update CheCluster CR:
```yaml
spec:
devEnvironments:
persistUserHome:
enabled: true
```
3. Start a workspace
4. Edit `~/.kube/config` file like that:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: inCluster
cluster:
server: https://10.96.0.1:443
certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
insecure-skip-tls-verify: false
users:
- name: admin
user:
token: <EXISTED_TOKEN>
- name: admin-2
user:
token: XXXXX
contexts:
- name: logged-user
context:
user: admin
cluster: inCluster
name: logged-user
namespace: admin-che
- name: logged-user-2
context:
user: admin-2
cluster: inCluster
name: logged-user
namespace: admin-che …
```
=> fix: Preserve the current context from the generated kubeconfig

packages/dashboard-backend/src/devworkspaceClient/services/__tests__/fixtures/merged_kubeconfig.yaml, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/fixtures/mounted_kubeconfig.yaml, packages/dashboard-backend/src/devworkspaceClient/services/__tests__/kubeConfigApi.spec.ts, packages/dashboard-backend/src/devworkspaceClient/services/kubeConfigApi.ts
Preserve the current context from the generated kubeconfig
Original PR https://github.com/eclipse-che/che-dashboard/pull/1349
N/A
https://issues.redhat.com/browse/CRW-8879
1. Deploy Eclipse Che
2. Update CheCluster CR:
```yaml
spec:
devEnvironments:
persistUserHome:
enabled: true
```
3. Start a workspace
4. Edit `~/.kube/config` file like that:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: inCluster
cluster:
server: https://10.96.0.1:443
certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
insecure-skip-tls-verify: false
users:
- name: admin
user:
token: <EXISTED_TOKEN>
- name: admin-2
user:
token: XXXXX
contexts:
- name: logged-user
context:
user: admin
cluster: inCluster
name: logged-user
namespace: admin-che
- name: logged-user-2
context:
user: admin-2 …
```
=> fix: Preserve the current context from the generated kubeconfig (#1349)

packages/common/src/helpers/__tests__/sanitize.spec.ts, packages/common/src/helpers/sanitize.ts
This pull request adds `iss` to sanitize OAuth parameters.
fixes https://github.com/eclipse-che/che/issues/23496
1. Deploy Eclipse-Che with the image from this PR - **quay.io/eclipse/che-dashboard:pr-1366-amd64**.
2. Created a new workspace from URL `https://github.com/eclipse-che/che-dashboard.git?iss=dummy_location`.
3. Open the target workspace details page and copy **Git repo URL** . The value should be `https://github.com/eclipse-che/che-dashboard`.
=> fix: sanitize OAuth parameters

.deps/dev.md, .deps/prod.md, package.json, yarn.lock
Bump sha.js and cipher-base dependencies to fix CVEs
=> chore: bump sha.js and cipher-base deps

packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/__tests__/index.spec.tsx, packages/dashboard-frontend/src/pages/UserPreferences/PersonalAccessTokens/AddEditModal/Form/GitProviderEndpoint/index.tsx
This PR fixes validation regex for personal access token UI to allow URL parameter contain port number.
fixes https://issues.redhat.com/browse/CRW-9390
1. Deploy Eclipse-Che with the image from this PR - quay.io/eclipse/che-dashboard:pr-1376-amd64.
2. Open **User Preferences** and try to add
a personal access token for **Bitbucket Server** with a server URL, which contains the port number. 
_Example:_ `https://your-bitbucket-server-hostname.org:7999/project/repo.git`
3. The server URL, which contains the port number, should be valid in the form.
=> fix: regex check to allow url to contain port number

packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/GitRepoOptions/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/GitRepoOptions/index.tsx, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/RepoOptionsAccordion/index.tsx, packages/dashboard-frontend/src/components/ImportFromGit/__tests__/helpers.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/ImportFromGit/helpers.ts, packages/dashboard-frontend/src/components/ImportFromGit/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/__tests__/getGitRemotes.spec.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/getGitRemotes.ts, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/Apply/Devfile/index.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/CheckExistingWorkspaces/__tests__/index.spec.tsx, packages/dashboard-frontend/src/components/WorkspaceProgress/CreatingSteps/CheckExistingWorkspaces/index.tsx, packages/dashboard-frontend/src/containers/Loader/index.tsx, packages/dashboard-frontend/src/services/helpers/factoryFlow/buildFactoryParams.ts, packages/dashboard-frontend/src/store/FactoryResolver/actions.ts
* Do not hide the Git Branch input if an SSH url is entered.
* When creating a workspace from an SSH url, pass the git branch value from the input to the `checkoutFrom` devfile section.
https://github.com/eclipse-che/che/issues/23499
1. Apply dashboard pull request image: `quay.io/eclipse/che-dashboard:pr-1373-amd64`
2. Apply che-server pull request image: `quay.io/eclipse/che-server:pr-828`
3. Add SSH key to the user namespace.
4. Prepare a git repository with several branches with devfiles.
5. Enter the SSH url of the repository to the `Create Workspace` -> `Git repo URL` input
6. Open the `Git repo Options` section and fill in the `Git branch` input
7. Click the `Create Workspace` button.
See: Workspace starts from the devfile located in the specified branch. Try the steps above with …
=> Add git branch to devfile when creating a workspace from SSH url

packages/dashboard-frontend/src/services/backend-client/yamlResolverApi.ts, packages/dashboard-frontend/src/services/workspace-client/__tests__/helpers.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceEditor.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceEditor.ts, packages/dashboard-frontend/src/services/workspace-client/helpers.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/helpers.grabLink.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/__tests__/reducer.spec.ts, packages/dashboard-frontend/src/store/FactoryResolver/actions.ts, packages/dashboard-frontend/src/store/FactoryResolver/helpers.ts, packages/dashboard-frontend/src/store/FactoryResolver/reducer.ts, packages/dashboard-frontend/src/store/Workspaces/__tests__/actions.spec.ts, packages/dashboard-frontend/src/store/Workspaces/actions.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/createWorkspaceFromDevfile.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/helpers/__tests__/getCustomEditor.spec.ts, packages/dashboard-frontend/src/store/Workspaces/devWorkspaces/actions/actionCreators/helpers/getCustomEditor.ts
This PR updates the `heckForTemplatesUpdate` method to allow custom editor updates from the `.che/che-editor.yaml` file before the next workspace start.
fixes https://github.com/eclipse-che/che/issues/23467
1. Apply dashboard pull request image: quay.io/eclipse/che-dashboard:pr-1378-amd64
2. Prepare a git repository with `.che/che-editor.yaml` file with the following content:
```yaml
reference: https://eclipse-che.github.io/che-plugin-registry/main/v3/plugins/che-incubator/che-code/insiders/devfile.yaml
override:
containers:
- name: che-code-injector
memoryLimit: 2048Mi
```
3. Create a new workspace from the target repository.  Check the che-editor memory limit, it should be `2048Mi`.
4. Update `.che/che-editor.yaml` file with the following content:
```yaml
reference: …
```
=> fix: checkForTemplatesUpdate method

packages/dashboard-frontend/src/services/workspace-client/devworkspace/__tests__/devWorkspaceClient.manageContainerSccAttribute.spec.ts, packages/dashboard-frontend/src/services/workspace-client/devworkspace/devWorkspaceClient.ts
Set HOST_USERS env var depending on enabled container capabilities
N/A
https://issues.redhat.com/browse/CRW-8320
All cases on OpenShift cluster
N/A
N/A
=> chore: Set HOST_USERS env var
